In [22]:
import pandas as pd
import numpy as np
import optuna

from nltk.corpus import stopwords

from sklearn.compose import ColumnTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import StratifiedKFold, cross_val_score
from xgboost import XGBClassifier

RANDOM_STATE = 42
DATA_DIR = "../data"

PREPS = ["normal", "stem", "lemma"]
VARIANTES = ["mx", "es", "cu"]

FEATURE_COLS = [
    "n_exc", "n_int", "n_may",
    "n_emo", "n_ris", "n_neg",
    "n_elo", "n_com", "n_pun"
]

PREP_GANADOR = {
    "mx": "lemma",
    "es": "normal",
    "cu": "normal"
}

STOP_WORDS = stopwords.words("spanish")

CV = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=RANDOM_STATE
)

In [23]:
def cargar_train_ganador(variante):
    prep = PREP_GANADOR[variante]

    sufijo = "" if prep == "normal" else f"_{prep}"

    path = f"{DATA_DIR}/train_clean{sufijo}_{variante}.csv"

    df = pd.read_csv(path)

    return df

In [24]:
def build_tfidf_prep(ngram_range=(1, 2)):

    tfidf = TfidfVectorizer(
        analyzer="word",
        ngram_range=ngram_range,
        min_df=2,
        max_df=0.98,
        max_features=20000,
        lowercase=False,
        sublinear_tf=True,
        dtype=np.float32
    )

    return ColumnTransformer([
        (
            "tfidf",
            tfidf,
            "MESSAGE_CLEAN"
        ),
        (
            "ling",
            "passthrough",
            FEATURE_COLS
        )
    ])

In [25]:
def objective(trial, df_train):

    X = df_train[
        ["MESSAGE_CLEAN"] + FEATURE_COLS
    ]

    y = df_train["IS_IRONIC"].values

    scale_pos_weight = (
        (y == 0).sum() /
        (y == 1).sum()
    )

    ngram_range = trial.suggest_categorical(
        "ngram_range",
        ["1_1", "1_2"]
    )

    NGRAM_MAP = {
        "1_1": (1, 1),
        "1_2": (1, 2)
    }

    params = {
        "n_estimators": trial.suggest_int(
            "n_estimators", 100, 600, step=50
        ),

        "max_depth": trial.suggest_int(
            "max_depth", 2, 8
        ),

        "learning_rate": trial.suggest_float(
            "learning_rate",
            0.01,
            0.30,
            log=True
        ),

        "min_child_weight": trial.suggest_int(
            "min_child_weight", 1, 10
        ),

        "subsample": trial.suggest_float(
            "subsample", 0.6, 1.0
        ),

        "colsample_bytree": trial.suggest_float(
            "colsample_bytree", 0.5, 1.0
        ),

        "gamma": trial.suggest_float(
            "gamma", 0.0, 5.0
        ),

        "reg_alpha": trial.suggest_float(
            "reg_alpha",
            1e-4,
            5.0,
            log=True
        ),

        "reg_lambda": trial.suggest_float(
            "reg_lambda",
            0.1,
            10.0,
            log=True
        )
    }

    model = XGBClassifier(
        **params,
        scale_pos_weight=scale_pos_weight,
        objective="binary:logistic",
        eval_metric="logloss",
        booster="gbtree",
        tree_method="hist",
        random_state=42,
        n_jobs=-1
    )

    pipeline = Pipeline([
        (
            "prep",
            build_tfidf_prep(
                NGRAM_MAP[ngram_range]
            )
        ),
        ("clf", model)
    ])

    scores = cross_val_score(
        pipeline,
        X,
        y,
        cv=CV,
        scoring="f1_macro",
        n_jobs=1
    )

    return scores.mean()

In [26]:
def optimizar_variante(variante, n_trials=50):

    df_train = cargar_train_ganador(variante)

    print(
        f"\nOptimización XGBoost | "
        f"{variante.upper()} | "
        f"prep={PREP_GANADOR[variante]}"
    )

    study = optuna.create_study(
        direction="maximize",
        sampler=optuna.samplers.TPESampler(
            seed=RANDOM_STATE
        )
    )

    study.optimize(
        lambda trial: objective(
            trial,
            df_train
        ),
        n_trials=n_trials
    )

    print("\nMejor F1-Macro CV:")
    print(study.best_value)

    print("\nMejores hiperparámetros:")
    print(study.best_params)

    return study

In [27]:
study_mx = optimizar_variante("mx", n_trials=50)
study_es = optimizar_variante("es", n_trials=50)
study_cu = optimizar_variante("cu", n_trials=50)

[I 2026-09-21 15:58:20,330] A new study created in memory with name: no-name-963396a1-3c40-44d0-8256-cf68697039d6

Optimización XGBoost | MX | prep=lemma

[I 2026-09-21 15:58:27,245] Trial 0 finished with value: 0.611432874222849 and parameters: {'ngram_range': '1_2', 'n_estimators': 500, 'max_depth': 6, 'learning_rate': 0.01700037298921102, 'min_child_weight': 2, 'subsample': 0.6232334448672797, 'colsample_bytree': 0.9330880728874675, 'gamma': 3.005575058716044, 'reg_alpha': 0.21242802137208885, 'reg_lambda': 0.10994335574766201}. Best is trial 0 with value: 0.611432874222849.
[I 2026-09-21 15:58:28,467] Trial 1 finished with value: 0.5869644192508019 and parameters: {'ngram_range': '1_1', 'n_estimators': 200, 'max_depth': 3, 'learning_rate': 0.018659959624904916, 'min_child_weight': 4, 'subsample': 0.8099025726528951, 'colsample_bytree': 0.7159725093210578, 'gamma': 1.4561457009902097, 'reg_alpha': 0.07500295933641415, 'reg_lambda': 0.19010245319870356}. Best is trial 0 with value: 0.611432874222849.
[I 2026-09-21 15:58:33,120] Trial 2 finished with value: 0.6022000356498525 and parameters: {'ngram_range': '1_2', 'n_estimators': 350, 'max_depth': 7, 'learning_rate': 0.019721610970574007, 'min_child_weight': 6, 'subsample': 0.836965827544817, 'colsample_bytree': 0.5232252063599989, 'gamma': 3.0377242595071916, 'reg_alpha': 0.00063283099528693, 'reg_lambda': 0.1349283426801325}. Best is trial 0 with value: 0.611432874222849.
[I 2026-09-21 15:58:37,548] Trial 3 finished with value: 0.5914949456131116 and parameters: {'ngram_range': '1_2', 'n_estimators': 500, 'max_depth': 4, 'learning_rate': 0.013940346079873234, 'min_child_weight': 7, 'subsample': 0.7760609974958406, 'colsample_bytree': 0.5610191174223894, 'gamma': 2.475884550556351, 'reg_alpha': 0.00014507434860119788, 'reg_lambda': 6.586289317583113}. Best is trial 0 with value: 0.611432874222849.
[I 2026-09-21 15:58:40,067] Trial 4 finished with value: 0.5937759868502793 and parameters: {'ngram_range': '1_2', 'n_estimators': 250, 'max_depth': 5, 'learning_rate': 0.06420330336297862, 'min_child_weight': 2, 'subsample': 0.9878338511058234, 'colsample_bytree': 0.8875664116805573, 'gamma': 4.697494707820946, 'reg_alpha': 1.6023850290194919, 'reg_lambda': 1.5696396388661147}. Best is trial 0 with value: 0.611432874222849.
[I 2026-09-21 15:58:41,023] Trial 5 finished with value: 0.5859716380319757 and parameters: {'ngram_range': '1_1', 'n_estimators': 200, 'max_depth': 2, 'learning_rate': 0.03023795012558475, 'min_child_weight': 4, 'subsample': 0.7085396127095583, 'colsample_bytree': 0.9143687545759647, 'gamma': 1.7837666334679465, 'reg_alpha': 0.002089790902378636, 'reg_lambda': 1.2172847081122433}. Best is trial 0 with value: 0.611432874222849.
[I 2026-09-21 15:58:43,377] Trial 6 finished with value: 0.6026958473275219 and parameters: {'ngram_range': '1_2', 'n_estimators': 100, 'max_depth': 8, 'learning_rate': 0.13826083091896751, 'min_child_weight': 2, 'subsample': 0.602208846849441, 'colsample_bytree': 0.9077307142274171, 'gamma': 3.534286719238086, 'reg_alpha': 0.2664298103063688, 'reg_lambda': 3.487712624545931}. Best is trial 0 with value: 0.611432874222849.
[I 2026-09-21 15:58:46,390] Trial 7 finished with value: 0.5950437788335934 and parameters: {'ngram_range': '1_2', 'n_estimators': 150, 'max_depth': 8, 'learning_rate': 0.08330803890301997, 'min_child_weight': 4, 'subsample': 0.6254233401144095, 'colsample_bytree': 0.6554911608578311, 'gamma': 1.6259166101337352, 'reg_alpha': 0.2681621920201289, 'reg_lambda': 1.8841476921545086}. Best is trial 0 with value: 0.611432874222849.
[I 2026-09-21 15:58:47,566] Trial 8 finished with value: 0.6083501436823084 and parameters: {'ngram_range': '1_1', 'n_estimators': 150, 'max_depth': 6, 'learning_rate': 0.13297554090738672, 'min_child_weight': 6, 'subsample': 0.9083868719818244, 'colsample_bytree': 0.7468977981821954, 'gamma': 2.6136641469099704, 'reg_alpha': 0.01020945174752076, 'reg_lambda': 0.11241862095793062}. Best is trial 0 with value: 0.611432874222849.
[I 2026-09-21 15:58:49,662] Trial 9 finished with value: 0.58781144324861 and parameters: {'ngram_range': '1_1', 'n_estimators': 450, 'max_depth': 4, 'learning_rate': 0.056392399916675585, 'min_child_weight': 10, 'subsample': 0.69971689165955, 'colsample_bytree': 0.7051914615178149, 'gamma': 3.7777556927152434, 'reg_alpha': 0.0011888189431127753, 'reg_lambda': 0.14254757044027438}. Best is trial 0 with value: 0.611432874222849.
[I 2026-09-21 15:58:53,846] Trial 10 finished with value: 0.5868039522062946 and parameters: {'ngram_range': '1_2', 'n_estimators': 400, 'max_depth': 3, 'learning_rate': 0.010997892892266298, 'min_child_weight': 1, 'subsample': 0.60534964551543, 'colsample_bytree': 0.9733411210431508, 'gamma': 3.8612153893692973, 'reg_alpha': 0.32770250592194367, 'reg_lambda': 1.5566568870534958}. Best is trial 0 with value: 0.611432874222849.
[I 2026-09-21 15:58:59,756] Trial 11 finished with value: 0.6188663416968325 and parameters: {'ngram_range': '1_2', 'n_estimators': 600, 'max_depth': 8, 'learning_rate': 0.07304927740834256, 'min_child_weight': 1, 'subsample': 0.7513679225176725, 'colsample_bytree': 0.6753925417546123, 'gamma': 3.1839585869363174, 'reg_alpha': 0.1741493648382391, 'reg_lambda': 0.24145573549605287}. Best is trial 11 with value: 0.6188663416968325.
[I 2026-09-21 15:59:07,365] Trial 12 finished with value: 0.6143597199348575 and parameters: {'ngram_range': '1_2', 'n_estimators': 600, 'max_depth': 6, 'learning_rate': 0.018786116016690106, 'min_child_weight': 2, 'subsample': 0.7558003068509603, 'colsample_bytree': 0.7963957779148585, 'gamma': 2.0179225549095037, 'reg_alpha': 0.09716582657241407, 'reg_lambda': 0.11026728283159373}. Best is trial 11 with value: 0.6188663416968325.
[I 2026-09-21 15:59:11,416] Trial 13 finished with value: 0.6086075382692068 and parameters: {'ngram_range': '1_2', 'n_estimators': 500, 'max_depth': 7, 'learning_rate': 0.19932263240965287, 'min_child_weight': 1, 'subsample': 0.835256888380768, 'colsample_bytree': 0.7152454854487923, 'gamma': 2.808838689389039, 'reg_alpha': 0.21073927406884943, 'reg_lambda': 0.3924974447570267}. Best is trial 11 with value: 0.6188663416968325.
[I 2026-09-21 15:59:17,848] Trial 14 finished with value: 0.6142732003826704 and parameters: {'ngram_range': '1_2', 'n_estimators': 600, 'max_depth': 5, 'learning_rate': 0.014632856912149241, 'min_child_weight': 1, 'subsample': 0.7242923580691191, 'colsample_bytree': 0.6324359078408217, 'gamma': 3.1958095986922466, 'reg_alpha': 0.016143758927437777, 'reg_lambda': 0.16682217433605268}. Best is trial 11 with value: 0.6188663416968325.
[I 2026-09-21 15:59:24,741] Trial 15 finished with value: 0.6082008846411412 and parameters: {'ngram_range': '1_2', 'n_estimators': 500, 'max_depth': 8, 'learning_rate': 0.03295853430591153, 'min_child_weight': 3, 'subsample': 0.6516950844850968, 'colsample_bytree': 0.7126234746520337, 'gamma': 3.1113648072485627, 'reg_alpha': 0.02154194988281593, 'reg_lambda': 0.2760545384070896}. Best is trial 11 with value: 0.6188663416968325.
[I 2026-09-21 15:59:29,086] Trial 16 finished with value: 0.6111156395826313 and parameters: {'ngram_range': '1_2', 'n_estimators': 500, 'max_depth': 8, 'learning_rate': 0.08488551392011433, 'min_child_weight': 2, 'subsample': 0.7782143099827518, 'colsample_bytree': 0.6988259489335907, 'gamma': 4.937268513767705, 'reg_alpha': 0.3214062097826876, 'reg_lambda': 0.15848605142516747}. Best is trial 11 with value: 0.6188663416968325.
[I 2026-09-21 15:59:35,261] Trial 17 finished with value: 0.6070628802097084 and parameters: {'ngram_range': '1_2', 'n_estimators': 550, 'max_depth': 7, 'learning_rate': 0.02635642490969418, 'min_child_weight': 4, 'subsample': 0.770130759107676, 'colsample_bytree': 0.6661643989755973, 'gamma': 2.3979637199643284, 'reg_alpha': 2.2513822920667588, 'reg_lambda': 0.20645263348505555}. Best is trial 11 with value: 0.6188663416968325.
[I 2026-09-21 15:59:40,334] Trial 18 finished with value: 0.5967094334202783 and parameters: {'ngram_range': '1_2', 'n_estimators': 600, 'max_depth': 5, 'learning_rate': 0.11794336921502395, 'min_child_weight': 5, 'subsample': 0.766677485556959, 'colsample_bytree': 0.7271322969692551, 'gamma': 2.3221357543794876, 'reg_alpha': 0.1277555714905882, 'reg_lambda': 0.13685138400316008}. Best is trial 11 with value: 0.6188663416968325.
[I 2026-09-21 15:59:44,073] Trial 19 finished with value: 0.6066108047626576 and parameters: {'ngram_range': '1_2', 'n_estimators': 500, 'max_depth': 8, 'learning_rate': 0.1783790561817449, 'min_child_weight': 4, 'subsample': 0.8092307116442001, 'colsample_bytree': 0.5794295377888534, 'gamma': 3.2782791753848084, 'reg_alpha': 0.08946234142208252, 'reg_lambda': 0.20095382998952155}. Best is trial 11 with value: 0.6188663416968325.
[I 2026-09-21 15:59:51,112] Trial 20 finished with value: 0.6123447076735618 and parameters: {'ngram_range': '1_2', 'n_estimators': 600, 'max_depth': 7, 'learning_rate': 0.079064148375292, 'min_child_weight': 1, 'subsample': 0.8327281576000329, 'colsample_bytree': 0.7959579764150779, 'gamma': 1.7868016572614833, 'reg_alpha': 0.12539519912219105, 'reg_lambda': 0.15531217199162967}. Best is trial 11 with value: 0.6188663416968325.
[I 2026-09-21 15:59:57,856] Trial 21 finished with value: 0.6210736207281977 and parameters: {'ngram_range': '1_2', 'n_estimators': 600, 'max_depth': 6, 'learning_rate': 0.0240724908318712, 'min_child_weight': 2, 'subsample': 0.7716278322867981, 'colsample_bytree': 0.5710977788343404, 'gamma': 3.2642770207543514, 'reg_alpha': 0.004137868227753053, 'reg_lambda': 0.8906562222499459}. Best is trial 21 with value: 0.6210736207281977.
[I 2026-09-21 16:00:03,279] Trial 22 finished with value: 0.6092747075488028 and parameters: {'ngram_range': '1_2', 'n_estimators': 550, 'max_depth': 7, 'learning_rate': 0.10560925952905824, 'min_child_weight': 1, 'subsample': 0.7266746160174933, 'colsample_bytree': 0.5829721788789687, 'gamma': 2.043707766971801, 'reg_alpha': 0.2980274640022075, 'reg_lambda': 0.5790186907561293}. Best is trial 21 with value: 0.6210736207281977.
[I 2026-09-21 16:00:10,350] Trial 23 finished with value: 0.609046658667294 and parameters: {'ngram_range': '1_2', 'n_estimators': 550, 'max_depth': 7, 'learning_rate': 0.02084844015975976, 'min_child_weight': 2, 'subsample': 0.8326392344915142, 'colsample_bytree': 0.5614775014428041, 'gamma': 2.2740412505986214, 'reg_alpha': 0.047220959920253484, 'reg_lambda': 0.12967243636376555}. Best is trial 21 with value: 0.6210736207281977.
[I 2026-09-21 16:00:17,008] Trial 24 finished with value: 0.6173416135806928 and parameters: {'ngram_range': '1_2', 'n_estimators': 550, 'max_depth': 6, 'learning_rate': 0.02787636020598024, 'min_child_weight': 2, 'subsample': 0.7422289006339727, 'colsample_bytree': 0.7646118491851922, 'gamma': 3.523831708643642, 'reg_alpha': 0.08419073923164574, 'reg_lambda': 0.16620552544678588}. Best is trial 21 with value: 0.6210736207281977.
[I 2026-09-21 16:00:21,207] Trial 25 finished with value: 0.6073530554045258 and parameters: {'ngram_range': '1_2', 'n_estimators': 550, 'max_depth': 5, 'learning_rate': 0.1856060539077163, 'min_child_weight': 2, 'subsample': 0.7626714857415943, 'colsample_bytree': 0.6910534736751734, 'gamma': 3.715872783948806, 'reg_alpha': 0.027360147038130358, 'reg_lambda': 0.27010784872351323}. Best is trial 21 with value: 0.6210736207281977.
[I 2026-09-21 16:00:27,366] Trial 26 finished with value: 0.6148183590404579 and parameters: {'ngram_range': '1_2', 'n_estimators': 500, 'max_depth': 7, 'learning_rate': 0.0409975075919481, 'min_child_weight': 1, 'subsample': 0.7883950673802153, 'colsample_bytree': 0.6034894678722469, 'gamma': 3.0852407681698577, 'reg_alpha': 0.033432424955457056, 'reg_lambda': 0.29790942938787845}. Best is trial 21 with value: 0.6210736207281977.
[I 2026-09-21 16:00:34,033] Trial 27 finished with value: 0.6209780049196107 and parameters: {'ngram_range': '1_2', 'n_estimators': 600, 'max_depth': 7, 'learning_rate': 0.033090664586432596, 'min_child_weight': 1, 'subsample': 0.7973377868111278, 'colsample_bytree': 0.6369844257792723, 'gamma': 3.6420333129921705, 'reg_alpha': 0.002313817822345676, 'reg_lambda': 0.5244693458054961}. Best is trial 21 with value: 0.6210736207281977.
[I 2026-09-21 16:00:40,135] Trial 28 finished with value: 0.6144977177423048 and parameters: {'ngram_range': '1_2', 'n_estimators': 550, 'max_depth': 7, 'learning_rate': 0.03255473210072069, 'min_child_weight': 1, 'subsample': 0.7592485182238577, 'colsample_bytree': 0.6803261639873719, 'gamma': 4.6317848467733675, 'reg_alpha': 0.0007608263719179077, 'reg_lambda': 0.3562936921351537}. Best is trial 21 with value: 0.6210736207281977.
[I 2026-09-21 16:00:45,951] Trial 29 finished with value: 0.617326827926456 and parameters: {'ngram_range': '1_2', 'n_estimators': 550, 'max_depth': 8, 'learning_rate': 0.07926321232399954, 'min_child_weight': 2, 'subsample': 0.7486865522859388, 'colsample_bytree': 0.7762615781032365, 'gamma': 2.8108584598962594, 'reg_alpha': 0.15154731970714652, 'reg_lambda': 0.23592152785280782}. Best is trial 21 with value: 0.6210736207281977.
[I 2026-09-21 16:00:53,441] Trial 30 finished with value: 0.6181335086587566 and parameters: {'ngram_range': '1_2', 'n_estimators': 600, 'max_depth': 7, 'learning_rate': 0.024071012385426825, 'min_child_weight': 3, 'subsample': 0.7819858338788345, 'colsample_bytree': 0.7195412304969993, 'gamma': 3.3183851924886536, 'reg_alpha': 0.00508112617879671, 'reg_lambda': 0.9037326841602742}. Best is trial 21 with value: 0.6210736207281977.
[I 2026-09-21 16:01:00,086] Trial 31 finished with value: 0.6166025501670573 and parameters: {'ngram_range': '1_2', 'n_estimators': 600, 'max_depth': 8, 'learning_rate': 0.050286280834196916, 'min_child_weight': 1, 'subsample': 0.7121284980218382, 'colsample_bytree': 0.6480342193418763, 'gamma': 3.2729688453817576, 'reg_alpha': 0.0005029221311225357, 'reg_lambda': 0.8542179752185096}. Best is trial 21 with value: 0.6210736207281977.
[I 2026-09-21 16:01:06,006] Trial 32 finished with value: 0.6118873487076234 and parameters: {'ngram_range': '1_2', 'n_estimators': 600, 'max_depth': 6, 'learning_rate': 0.04861362555975651, 'min_child_weight': 4, 'subsample': 0.7687321428163791, 'colsample_bytree': 0.6600547453527636, 'gamma': 2.8868125123963693, 'reg_alpha': 0.0025577458053282764, 'reg_lambda': 1.2834016116183438}. Best is trial 21 with value: 0.6210736207281977.
[I 2026-09-21 16:01:13,085] Trial 33 finished with value: 0.6165455000741292 and parameters: {'ngram_range': '1_2', 'n_estimators': 600, 'max_depth': 6, 'learning_rate': 0.017045142151145137, 'min_child_weight': 2, 'subsample': 0.7988184317056994, 'colsample_bytree': 0.6144993345958804, 'gamma': 3.566156501000184, 'reg_alpha': 0.0034295857948490743, 'reg_lambda': 1.0418053963590126}. Best is trial 21 with value: 0.6210736207281977.
[I 2026-09-21 16:01:21,214] Trial 34 finished with value: 0.6132059295413164 and parameters: {'ngram_range': '1_2', 'n_estimators': 600, 'max_depth': 8, 'learning_rate': 0.02264334371827272, 'min_child_weight': 2, 'subsample': 0.8264576835610954, 'colsample_bytree': 0.6965621444399445, 'gamma': 3.3558978406648765, 'reg_alpha': 0.005454047332953266, 'reg_lambda': 0.3127366659916248}. Best is trial 21 with value: 0.6210736207281977.
[I 2026-09-21 16:01:26,768] Trial 35 finished with value: 0.6088396142748553 and parameters: {'ngram_range': '1_2', 'n_estimators': 600, 'max_depth': 8, 'learning_rate': 0.10680150235068585, 'min_child_weight': 1, 'subsample': 0.7738820280666375, 'colsample_bytree': 0.7800153529318907, 'gamma': 3.258314290761217, 'reg_alpha': 0.024174072198091697, 'reg_lambda': 0.2790527841327346}. Best is trial 21 with value: 0.6210736207281977.
[I 2026-09-21 16:01:32,924] Trial 36 finished with value: 0.6108727376522596 and parameters: {'ngram_range': '1_2', 'n_estimators': 600, 'max_depth': 7, 'learning_rate': 0.03766142872992295, 'min_child_weight': 1, 'subsample': 0.7776874424145677, 'colsample_bytree': 0.5615231234777132, 'gamma': 3.978027683150681, 'reg_alpha': 0.004395170857082015, 'reg_lambda': 0.515524218698072}. Best is trial 21 with value: 0.6210736207281977.
[I 2026-09-21 16:01:39,457] Trial 37 finished with value: 0.6171708779549794 and parameters: {'ngram_range': '1_2', 'n_estimators': 550, 'max_depth': 8, 'learning_rate': 0.06113748180820913, 'min_child_weight': 1, 'subsample': 0.7697639064041685, 'colsample_bytree': 0.6585610430179306, 'gamma': 2.424145154267791, 'reg_alpha': 0.006370973326812023, 'reg_lambda': 0.8536135451474473}. Best is trial 21 with value: 0.6210736207281977.
[I 2026-09-21 16:01:46,229] Trial 38 finished with value: 0.6157747394118461 and parameters: {'ngram_range': '1_2', 'n_estimators': 600, 'max_depth': 6, 'learning_rate': 0.02544696630375967, 'min_child_weight': 2, 'subsample': 0.7278376965804001, 'colsample_bytree': 0.5919169503085538, 'gamma': 3.58081028418429, 'reg_alpha': 0.025379704266068004, 'reg_lambda': 0.4753269654561356}. Best is trial 21 with value: 0.6210736207281977.
[I 2026-09-21 16:01:53,314] Trial 39 finished with value: 0.6235171902192473 and parameters: {'ngram_range': '1_2', 'n_estimators': 550, 'max_depth': 7, 'learning_rate': 0.01659694548952407, 'min_child_weight': 3, 'subsample': 0.7375238849252976, 'colsample_bytree': 0.6616935367367804, 'gamma': 3.5691762015269073, 'reg_alpha': 0.0004084687876720793, 'reg_lambda': 0.5745153746962762}. Best is trial 39 with value: 0.6235171902192473.
[I 2026-09-21 16:01:59,978] Trial 40 finished with value: 0.6177077336201087 and parameters: {'ngram_range': '1_2', 'n_estimators': 550, 'max_depth': 7, 'learning_rate': 0.02062814537856444, 'min_child_weight': 2, 'subsample': 0.7954741161054816, 'colsample_bytree': 0.627208557794608, 'gamma': 3.806718089418956, 'reg_alpha': 0.00038513815747655094, 'reg_lambda': 0.9524221093953116}. Best is trial 39 with value: 0.6235171902192473.
[I 2026-09-21 16:02:07,570] Trial 41 finished with value: 0.6128532237190972 and parameters: {'ngram_range': '1_2', 'n_estimators': 550, 'max_depth': 8, 'learning_rate': 0.011196214640218522, 'min_child_weight': 4, 'subsample': 0.7309954405112321, 'colsample_bytree': 0.6323913512584081, 'gamma': 3.74586555420289, 'reg_alpha': 0.0009169913671516663, 'reg_lambda': 0.4481129461888257}. Best is trial 39 with value: 0.6235171902192473.
[I 2026-09-21 16:02:13,251] Trial 42 finished with value: 0.613110373132453 and parameters: {'ngram_range': '1_2', 'n_estimators': 600, 'max_depth': 7, 'learning_rate': 0.04794370923840231, 'min_child_weight': 1, 'subsample': 0.8209986589374394, 'colsample_bytree': 0.5789964255691701, 'gamma': 3.86082990459186, 'reg_alpha': 0.0002929034072020874, 'reg_lambda': 0.6498502015975471}. Best is trial 39 with value: 0.6235171902192473.
[I 2026-09-21 16:02:18,830] Trial 43 finished with value: 0.6209766316147768 and parameters: {'ngram_range': '1_2', 'n_estimators': 550, 'max_depth': 5, 'learning_rate': 0.026953474470362525, 'min_child_weight': 2, 'subsample': 0.7646283817973837, 'colsample_bytree': 0.548111685109271, 'gamma': 3.1455302994403973, 'reg_alpha': 0.0005265643889156709, 'reg_lambda': 0.7405011946688328}. Best is trial 39 with value: 0.6235171902192473.
[I 2026-09-21 16:02:25,093] Trial 44 finished with value: 0.6178641956802335 and parameters: {'ngram_range': '1_2', 'n_estimators': 550, 'max_depth': 6, 'learning_rate': 0.023532700477798967, 'min_child_weight': 3, 'subsample': 0.7426705659528762, 'colsample_bytree': 0.6353085372208684, 'gamma': 3.6816379288933976, 'reg_alpha': 0.000282306060152474, 'reg_lambda': 0.781225137345057}. Best is trial 39 with value: 0.6235171902192473.
[I 2026-09-21 16:02:31,314] Trial 45 finished with value: 0.6200607845281881 and parameters: {'ngram_range': '1_2', 'n_estimators': 600, 'max_depth': 6, 'learning_rate': 0.016807361314696945, 'min_child_weight': 2, 'subsample': 0.761322539965054, 'colsample_bytree': 0.528728888726547, 'gamma': 3.8745732101050328, 'reg_alpha': 0.001914128283798804, 'reg_lambda': 0.5207517846398316}. Best is trial 39 with value: 0.6235171902192473.

Mejor F1-Macro CV:
0.6235171902192473

Mejores hiperparámetros:
{'ngram_range': '1_2', 'n_estimators': 550, 'max_depth': 7, 'learning_rate': 0.01659694548952407, 'min_child_weight': 3, 'subsample': 0.7375238849252976, 'colsample_bytree': 0.6616935367367804, 'gamma': 3.5691762015269073, 'reg_alpha': 0.0004084687876720793, 'reg_lambda': 0.5745153746962762}

Optimización XGBoost | ES | prep=normal

[I 2026-09-21 16:03:06,409] Trial 0 finished with value: 0.6950482057849255 and parameters: {'ngram_range': '1_2', 'n_estimators': 500, 'max_depth': 6, 'learning_rate': 0.01700037298921102, 'min_child_weight': 2, 'subsample': 0.6232334448672797, 'colsample_bytree': 0.9330880728874675, 'gamma': 3.005575058716044, 'reg_alpha': 0.21242802137208885, 'reg_lambda': 0.10994335574766201}. Best is trial 0 with value: 0.6950482057849255.
[I 2026-09-21 16:03:07,600] Trial 1 finished with value: 0.6770818539665628 and parameters: {'ngram_range': '1_1', 'n_estimators': 200, 'max_depth': 3, 'learning_rate': 0.018659959624904916, 'min_child_weight': 4, 'subsample': 0.8099025726528951, 'colsample_bytree': 0.7159725093210578, 'gamma': 1.4561457009902097, 'reg_alpha': 0.07500295933641415, 'reg_lambda': 0.19010245319870356}. Best is trial 0 with value: 0.6950482057849255.
[I 2026-09-21 16:03:14,841] Trial 2 finished with value: 0.6911593593657821 and parameters: {'ngram_range': '1_2', 'n_estimators': 350, 'max_depth': 7, 'learning_rate': 0.019721610970574007, 'min_child_weight': 6, 'subsample': 0.836965827544817, 'colsample_bytree': 0.5232252063599989, 'gamma': 3.0377242595071916, 'reg_alpha': 0.00063283099528693, 'reg_lambda': 0.1349283426801325}. Best is trial 0 with value: 0.6950482057849255.
[I 2026-09-21 16:03:21,982] Trial 3 finished with value: 0.6806548389139395 and parameters: {'ngram_range': '1_2', 'n_estimators': 500, 'max_depth': 4, 'learning_rate': 0.013940346079873234, 'min_child_weight': 7, 'subsample': 0.7760609974958406, 'colsample_bytree': 0.5610191174223894, 'gamma': 2.475884550556351, 'reg_alpha': 0.00014507434860119788, 'reg_lambda': 6.586289317583113}. Best is trial 0 with value: 0.6950482057849255.
[I 2026-09-21 16:03:25,552] Trial 4 finished with value: 0.6823776421955622 and parameters: {'ngram_range': '1_2', 'n_estimators': 250, 'max_depth': 5, 'learning_rate': 0.06420330336297862, 'min_child_weight': 2, 'subsample': 0.9878338511058234, 'colsample_bytree': 0.8875664116805573, 'gamma': 4.697494707820946, 'reg_alpha': 1.6023850290194919, 'reg_lambda': 1.5696396388661147}. Best is trial 0 with value: 0.6950482057849255.
[I 2026-09-21 16:03:26,653] Trial 5 finished with value: 0.6733972227908825 and parameters: {'ngram_range': '1_1', 'n_estimators': 200, 'max_depth': 2, 'learning_rate': 0.03023795012558475, 'min_child_weight': 4, 'subsample': 0.7085396127095583, 'colsample_bytree': 0.9143687545759647, 'gamma': 1.7837666334679465, 'reg_alpha': 0.002089790902378636, 'reg_lambda': 1.2172847081122433}. Best is trial 0 with value: 0.6950482057849255.
[I 2026-09-21 16:03:29,796] Trial 6 finished with value: 0.6794832886699785 and parameters: {'ngram_range': '1_2', 'n_estimators': 100, 'max_depth': 8, 'learning_rate': 0.13826083091896751, 'min_child_weight': 2, 'subsample': 0.602208846849441, 'colsample_bytree': 0.9077307142274171, 'gamma': 3.534286719238086, 'reg_alpha': 0.2664298103063688, 'reg_lambda': 3.487712624545931}. Best is trial 0 with value: 0.6950482057849255.
[I 2026-09-21 16:03:34,097] Trial 7 finished with value: 0.6753362706534369 and parameters: {'ngram_range': '1_2', 'n_estimators': 150, 'max_depth': 8, 'learning_rate': 0.08330803890301997, 'min_child_weight': 4, 'subsample': 0.6254233401144095, 'colsample_bytree': 0.6554911608578311, 'gamma': 1.6259166101337352, 'reg_alpha': 0.2681621920201289, 'reg_lambda': 1.8841476921545086}. Best is trial 0 with value: 0.6950482057849255.
[I 2026-09-21 16:03:35,401] Trial 8 finished with value: 0.6860466252699552 and parameters: {'ngram_range': '1_1', 'n_estimators': 150, 'max_depth': 6, 'learning_rate': 0.13297554090738672, 'min_child_weight': 6, 'subsample': 0.9083868719818244, 'colsample_bytree': 0.7468977981821954, 'gamma': 2.6136641469099704, 'reg_alpha': 0.01020945174752076, 'reg_lambda': 0.11241862095793062}. Best is trial 0 with value: 0.6950482057849255.
[I 2026-09-21 16:03:37,537] Trial 9 finished with value: 0.6885176392406847 and parameters: {'ngram_range': '1_1', 'n_estimators': 450, 'max_depth': 4, 'learning_rate': 0.056392399916675585, 'min_child_weight': 10, 'subsample': 0.69971689165955, 'colsample_bytree': 0.7051914615178149, 'gamma': 3.7777556927152434, 'reg_alpha': 0.0011888189431127753, 'reg_lambda': 0.14254757044027438}. Best is trial 0 with value: 0.6950482057849255.
[I 2026-09-21 16:03:43,617] Trial 10 finished with value: 0.676729470450939 and parameters: {'ngram_range': '1_2', 'n_estimators': 400, 'max_depth': 3, 'learning_rate': 0.010997892892266298, 'min_child_weight': 1, 'subsample': 0.60534964551543, 'colsample_bytree': 0.9733411210431508, 'gamma': 3.8612153893692973, 'reg_alpha': 0.32770250592194367, 'reg_lambda': 1.5566568870534958}. Best is trial 0 with value: 0.6950482057849255.
[I 2026-09-21 16:03:50,084] Trial 11 finished with value: 0.6790818661989848 and parameters: {'ngram_range': '1_2', 'n_estimators': 300, 'max_depth': 6, 'learning_rate': 0.012366957934873812, 'min_child_weight': 7, 'subsample': 0.626927965681923, 'colsample_bytree': 0.7889807923368855, 'gamma': 3.3572128321999046, 'reg_alpha': 0.0010767890347676986, 'reg_lambda': 0.22526879406529676}. Best is trial 0 with value: 0.6950482057849255.
[I 2026-09-21 16:03:59,089] Trial 12 finished with value: 0.6874872465646099 and parameters: {'ngram_range': '1_2', 'n_estimators': 400, 'max_depth': 7, 'learning_rate': 0.0278831361445616, 'min_child_weight': 1, 'subsample': 0.6937285540741707, 'colsample_bytree': 0.5983254697005944, 'gamma': 1.7945815483809504, 'reg_alpha': 2.686946486735592, 'reg_lambda': 0.14325328802570483}. Best is trial 0 with value: 0.6950482057849255.
[I 2026-09-21 16:04:07,957] Trial 13 finished with value: 0.6929336891670251 and parameters: {'ngram_range': '1_2', 'n_estimators': 400, 'max_depth': 8, 'learning_rate': 0.027754176205728006, 'min_child_weight': 3, 'subsample': 0.8151659265162021, 'colsample_bytree': 0.7510534415932039, 'gamma': 3.193305415596994, 'reg_alpha': 0.0020580520194473048, 'reg_lambda': 0.23815709732946774}. Best is trial 0 with value: 0.6950482057849255.
[I 2026-09-21 16:04:18,400] Trial 14 finished with value: 0.6935447492582527 and parameters: {'ngram_range': '1_2', 'n_estimators': 500, 'max_depth': 7, 'learning_rate': 0.01744258338849307, 'min_child_weight': 3, 'subsample': 0.8030174008726784, 'colsample_bytree': 0.8798813812856644, 'gamma': 2.8744213882799166, 'reg_alpha': 0.00047923544788216576, 'reg_lambda': 0.2529180134753956}. Best is trial 0 with value: 0.6950482057849255.
[I 2026-09-21 16:04:27,258] Trial 15 finished with value: 0.6874787940119328 and parameters: {'ngram_range': '1_2', 'n_estimators': 500, 'max_depth': 5, 'learning_rate': 0.016716768233389214, 'min_child_weight': 2, 'subsample': 0.6559952035471742, 'colsample_bytree': 0.9924418319405208, 'gamma': 2.204271042446511, 'reg_alpha': 0.3330112015052987, 'reg_lambda': 0.28124192600730674}. Best is trial 0 with value: 0.6950482057849255.
[I 2026-09-21 16:04:39,822] Trial 16 finished with value: 0.6847624120163177 and parameters: {'ngram_range': '1_2', 'n_estimators': 600, 'max_depth': 7, 'learning_rate': 0.01271280847327374, 'min_child_weight': 4, 'subsample': 0.9054861091728086, 'colsample_bytree': 0.8258667796955006, 'gamma': 3.120853437294955, 'reg_alpha': 0.00013822861308206846, 'reg_lambda': 0.24297617232692625}. Best is trial 0 with value: 0.6950482057849255.
[I 2026-09-21 16:04:45,690] Trial 17 finished with value: 0.6841574943412914 and parameters: {'ngram_range': '1_2', 'n_estimators': 400, 'max_depth': 4, 'learning_rate': 0.01819901841857369, 'min_child_weight': 2, 'subsample': 0.6487054956206165, 'colsample_bytree': 0.8641156434545518, 'gamma': 3.5586314369942054, 'reg_alpha': 0.03142543344922242, 'reg_lambda': 0.3114239017000859}. Best is trial 0 with value: 0.6950482057849255.
[I 2026-09-21 16:04:55,097] Trial 18 finished with value: 0.683456899298917 and parameters: {'ngram_range': '1_2', 'n_estimators': 500, 'max_depth': 8, 'learning_rate': 0.016690987159191085, 'min_child_weight': 4, 'subsample': 0.7781361456094092, 'colsample_bytree': 0.764405301623514, 'gamma': 4.33123433844047, 'reg_alpha': 1.786464526142349, 'reg_lambda': 0.10320831657205871}. Best is trial 0 with value: 0.6950482057849255.
[I 2026-09-21 16:05:00,263] Trial 19 finished with value: 0.703953521389756 and parameters: {'ngram_range': '1_1', 'n_estimators': 550, 'max_depth': 6, 'learning_rate': 0.018576966954164022, 'min_child_weight': 1, 'subsample': 0.6402182019004918, 'colsample_bytree': 0.8953495839474268, 'gamma': 1.9385073783826383, 'reg_alpha': 0.14534984477447524, 'reg_lambda': 0.11013004277239107}. Best is trial 19 with value: 0.703953521389756.
[I 2026-09-21 16:05:05,666] Trial 20 finished with value: 0.6924008450278957 and parameters: {'ngram_range': '1_1', 'n_estimators': 550, 'max_depth': 6, 'learning_rate': 0.011636819952061516, 'min_child_weight': 1, 'subsample': 0.6124060302601342, 'colsample_bytree': 0.8877260305772916, 'gamma': 1.4229224841663966, 'reg_alpha': 1.9629439465166676, 'reg_lambda': 0.13105811235979734}. Best is trial 19 with value: 0.703953521389756.
[I 2026-09-21 16:05:15,477] Trial 21 finished with value: 0.6859483724971962 and parameters: {'ngram_range': '1_2', 'n_estimators': 600, 'max_depth': 6, 'learning_rate': 0.024600625019218385, 'min_child_weight': 3, 'subsample': 0.6891797160396702, 'colsample_bytree': 0.9380435209153019, 'gamma': 4.630675032037297, 'reg_alpha': 0.12443296028276146, 'reg_lambda': 0.1817049412186152}. Best is trial 19 with value: 0.703953521389756.
[I 2026-09-21 16:05:25,018] Trial 22 finished with value: 0.6874721095083703 and parameters: {'ngram_range': '1_2', 'n_estimators': 600, 'max_depth': 6, 'learning_rate': 0.02473640535620627, 'min_child_weight': 3, 'subsample': 0.6028669567863707, 'colsample_bytree': 0.9039351335291694, 'gamma': 3.491118154028172, 'reg_alpha': 2.463282962309203, 'reg_lambda': 0.10500440334828211}. Best is trial 19 with value: 0.703953521389756.
[I 2026-09-21 16:05:30,868] Trial 23 finished with value: 0.7027906502797476 and parameters: {'ngram_range': '1_1', 'n_estimators': 600, 'max_depth': 7, 'learning_rate': 0.01771577659357478, 'min_child_weight': 1, 'subsample': 0.6303051992671185, 'colsample_bytree': 0.859729724252038, 'gamma': 2.857247801887616, 'reg_alpha': 0.010502961436418434, 'reg_lambda': 0.1963144073111506}. Best is trial 19 with value: 0.703953521389756.
[I 2026-09-21 16:05:36,101] Trial 24 finished with value: 0.6925060207480184 and parameters: {'ngram_range': '1_1', 'n_estimators': 600, 'max_depth': 6, 'learning_rate': 0.011016181220623608, 'min_child_weight': 2, 'subsample': 0.6182548919490769, 'colsample_bytree': 0.9053603597280893, 'gamma': 1.6019744683934547, 'reg_alpha': 0.010445779768866412, 'reg_lambda': 0.12906601939712672}. Best is trial 19 with value: 0.703953521389756.
[I 2026-09-21 16:05:40,525] Trial 25 finished with value: 0.6890265666467617 and parameters: {'ngram_range': '1_1', 'n_estimators': 600, 'max_depth': 8, 'learning_rate': 0.0411737617839423, 'min_child_weight': 1, 'subsample': 0.6117156976985951, 'colsample_bytree': 0.9493414650069407, 'gamma': 3.9043441130517555, 'reg_alpha': 0.012645117011754992, 'reg_lambda': 0.13234212038624332}. Best is trial 19 with value: 0.703953521389756.
[I 2026-09-21 16:05:44,707] Trial 26 finished with value: 0.7016840691744227 and parameters: {'ngram_range': '1_1', 'n_estimators': 550, 'max_depth': 5, 'learning_rate': 0.020014373218376007, 'min_child_weight': 1, 'subsample': 0.6307834992863288, 'colsample_bytree': 0.8909142631543122, 'gamma': 2.5470169785371266, 'reg_alpha': 0.042716078949874565, 'reg_lambda': 0.16789067945639824}. Best is trial 19 with value: 0.703953521389756.
[I 2026-09-21 16:05:50,301] Trial 27 finished with value: 0.6954718705030248 and parameters: {'ngram_range': '1_1', 'n_estimators': 600, 'max_depth': 8, 'learning_rate': 0.026137944577970935, 'min_child_weight': 1, 'subsample': 0.6854732481279812, 'colsample_bytree': 0.8843547691455699, 'gamma': 3.282695072679654, 'reg_alpha': 0.005021002174422555, 'reg_lambda': 0.18675653156337074}. Best is trial 19 with value: 0.703953521389756.
[I 2026-09-21 16:05:54,802] Trial 28 finished with value: 0.6970875300132808 and parameters: {'ngram_range': '1_1', 'n_estimators': 500, 'max_depth': 6, 'learning_rate': 0.025039027755445923, 'min_child_weight': 1, 'subsample': 0.6772458985236145, 'colsample_bytree': 0.8254406259073279, 'gamma': 1.0985696918534669, 'reg_alpha': 0.1157987982618236, 'reg_lambda': 0.2911560374569844}. Best is trial 19 with value: 0.703953521389756.
[I 2026-09-21 16:05:59,748] Trial 29 finished with value: 0.6992150870396348 and parameters: {'ngram_range': '1_1', 'n_estimators': 550, 'max_depth': 6, 'learning_rate': 0.016621236533338846, 'min_child_weight': 1, 'subsample': 0.6075360060587935, 'colsample_bytree': 0.9264155561890826, 'gamma': 2.3905980937685483, 'reg_alpha': 0.07422984707637759, 'reg_lambda': 0.18826128338364803}. Best is trial 19 with value: 0.703953521389756.
[I 2026-09-21 16:06:05,948] Trial 30 finished with value: 0.6911561272752931 and parameters: {'ngram_range': '1_1', 'n_estimators': 600, 'max_depth': 7, 'learning_rate': 0.024096243058597033, 'min_child_weight': 1, 'subsample': 0.7037608568441976, 'colsample_bytree': 0.9452131469563005, 'gamma': 2.0070960298625415, 'reg_alpha': 0.3500300325441204, 'reg_lambda': 0.13844642107364002}. Best is trial 19 with value: 0.703953521389756.
[I 2026-09-21 16:06:11,382] Trial 31 finished with value: 0.6976661699571333 and parameters: {'ngram_range': '1_1', 'n_estimators': 500, 'max_depth': 7, 'learning_rate': 0.01702652774934117, 'min_child_weight': 1, 'subsample': 0.7149761526385674, 'colsample_bytree': 0.8802030489429972, 'gamma': 1.2387868098236292, 'reg_alpha': 0.11287705550311611, 'reg_lambda': 0.12037049227219641}. Best is trial 19 with value: 0.703953521389756.
[I 2026-09-21 16:06:16,323] Trial 32 finished with value: 0.7028367482460365 and parameters: {'ngram_range': '1_1', 'n_estimators': 550, 'max_depth': 7, 'learning_rate': 0.014536256218086144, 'min_child_weight': 3, 'subsample': 0.6128698754601454, 'colsample_bytree': 0.9382571567328691, 'gamma': 3.1303885759586665, 'reg_alpha': 0.007322149732087141, 'reg_lambda': 0.335272094838156}. Best is trial 19 with value: 0.703953521389756.
[I 2026-09-21 16:06:22,721] Trial 33 finished with value: 0.7015176961687172 and parameters: {'ngram_range': '1_1', 'n_estimators': 550, 'max_depth': 8, 'learning_rate': 0.013660558013173764, 'min_child_weight': 1, 'subsample': 0.6639770091465789, 'colsample_bytree': 0.8295505255127194, 'gamma': 2.115305500631524, 'reg_alpha': 0.016030686493437477, 'reg_lambda': 0.35219624219471796}. Best is trial 19 with value: 0.703953521389756.
[I 2026-09-21 16:06:27,951] Trial 34 finished with value: 0.6989691422336131 and parameters: {'ngram_range': '1_1', 'n_estimators': 600, 'max_depth': 6, 'learning_rate': 0.021404376984734536, 'min_child_weight': 1, 'subsample': 0.6669825733966359, 'colsample_bytree': 0.905445170166141, 'gamma': 2.5375937067370797, 'reg_alpha': 0.1079460551205751, 'reg_lambda': 0.34392363393379055}. Best is trial 19 with value: 0.703953521389756.
[I 2026-09-21 16:06:31,838] Trial 35 finished with value: 0.6949074143557873 and parameters: {'ngram_range': '1_1', 'n_estimators': 600, 'max_depth': 5, 'learning_rate': 0.011861846017396838, 'min_child_weight': 3, 'subsample': 0.610046638154456, 'colsample_bytree': 0.8038429845493988, 'gamma': 2.3286939062333114, 'reg_alpha': 0.0025570583349416483, 'reg_lambda': 0.14853203063725964}. Best is trial 19 with value: 0.703953521389756.
[I 2026-09-21 16:06:36,476] Trial 36 finished with value: 0.703313623231729 and parameters: {'ngram_range': '1_1', 'n_estimators': 550, 'max_depth': 6, 'learning_rate': 0.022542755594018738, 'min_child_weight': 1, 'subsample': 0.6307014041196, 'colsample_bytree': 0.815096174694646, 'gamma': 2.1514541406645757, 'reg_alpha': 0.19412717140588356, 'reg_lambda': 0.16840257616645016}. Best is trial 19 with value: 0.703953521389756.
[I 2026-09-21 16:06:41,323] Trial 37 finished with value: 0.6970720672475268 and parameters: {'ngram_range': '1_1', 'n_estimators': 600, 'max_depth': 6, 'learning_rate': 0.022056575425692608, 'min_child_weight': 2, 'subsample': 0.6096139994471244, 'colsample_bytree': 0.8742298112327651, 'gamma': 1.9606001703690525, 'reg_alpha': 0.5313966593566477, 'reg_lambda': 0.10772865240126459}. Best is trial 19 with value: 0.703953521389756.
[I 2026-09-21 16:06:46,816] Trial 38 finished with value: 0.6945871564609901 and parameters: {'ngram_range': '1_1', 'n_estimators': 600, 'max_depth': 6, 'learning_rate': 0.011526404136851411, 'min_child_weight': 1, 'subsample': 0.6571524545912727, 'colsample_bytree': 0.9127620160794192, 'gamma': 2.8850303404827975, 'reg_alpha': 0.43307410221098197, 'reg_lambda': 0.14100826199902877}. Best is trial 19 with value: 0.703953521389756.
[I 2026-09-21 16:06:51,704] Trial 39 finished with value: 0.6997075289132775 and parameters: {'ngram_range': '1_1', 'n_estimators': 600, 'max_depth': 6, 'learning_rate': 0.015309447944521395, 'min_child_weight': 3, 'subsample': 0.6406442466347715, 'colsample_bytree': 0.996974183781746, 'gamma': 2.6874975642292123, 'reg_alpha': 0.01334537047883992, 'reg_lambda': 0.29220399242191486}. Best is trial 19 with value: 0.703953521389756.
[I 2026-09-21 16:06:57,332] Trial 40 finished with value: 0.6954531968082613 and parameters: {'ngram_range': '1_1', 'n_estimators': 550, 'max_depth': 7, 'learning_rate': 0.011300157738896716, 'min_child_weight': 1, 'subsample': 0.609208088770162, 'colsample_bytree': 0.9059886516554071, 'gamma': 3.0101708708431523, 'reg_alpha': 0.012223427883138424, 'reg_lambda': 0.1893507391437064}. Best is trial 19 with value: 0.703953521389756.
[I 2026-09-21 16:07:03,332] Trial 41 finished with value: 0.6998264990920985 and parameters: {'ngram_range': '1_1', 'n_estimators': 600, 'max_depth': 8, 'learning_rate': 0.01346818829846609, 'min_child_weight': 2, 'subsample': 0.6025327948370326, 'colsample_bytree': 0.8877983427719286, 'gamma': 3.221791965808608, 'reg_alpha': 0.001339512767329962, 'reg_lambda': 0.20826324685946504}. Best is trial 19 with value: 0.703953521389756.
[I 2026-09-21 16:07:07,389] Trial 42 finished with value: 0.6982930051342613 and parameters: {'ngram_range': '1_1', 'n_estimators': 600, 'max_depth': 5, 'learning_rate': 0.020359925172475063, 'min_child_weight': 2, 'subsample': 0.6280333939365405, 'colsample_bytree': 0.8011227609283054, 'gamma': 2.219593032422672, 'reg_alpha': 0.2152642020933018, 'reg_lambda': 0.1455627450776711}. Best is trial 19 with value: 0.703953521389756.
[I 2026-09-21 16:07:11,803] Trial 43 finished with value: 0.6950907016419914 and parameters: {'ngram_range': '1_1', 'n_estimators': 600, 'max_depth': 5, 'learning_rate': 0.01754949314210848, 'min_child_weight': 1, 'subsample': 0.6449492704312306, 'colsample_bytree': 0.8512391368286037, 'gamma': 2.3933480423038453, 'reg_alpha': 0.06145427515335504, 'reg_lambda': 0.14971210699701928}. Best is trial 19 with value: 0.703953521389756.
[I 2026-09-21 16:07:14,700] Trial 44 finished with value: 0.6911181251413414 and parameters: {'ngram_range': '1_1', 'n_estimators': 450, 'max_depth': 4, 'learning_rate': 0.017299456902099268, 'min_child_weight': 1, 'subsample': 0.6421546589483879, 'colsample_bytree': 0.8774951341826489, 'gamma': 1.995898643232575, 'reg_alpha': 0.05448825641962219, 'reg_lambda': 0.2307660687400115}. Best is trial 19 with value: 0.703953521389756.
[I 2026-09-21 16:07:19,167] Trial 45 finished with value: 0.6982625308733805 and parameters: {'ngram_range': '1_1', 'n_estimators': 600, 'max_depth': 5, 'learning_rate': 0.028437259757150234, 'min_child_weight': 1, 'subsample': 0.6263034115759473, 'colsample_bytree': 0.9286555284110055, 'gamma': 2.4581872972290437, 'reg_alpha': 0.2324341539627277, 'reg_lambda': 0.252892719001838}. Best is trial 19 with value: 0.703953521389756.

Mejor F1-Macro CV:
0.703953521389756

Mejores hiperparámetros:
{'ngram_range': '1_1', 'n_estimators': 550, 'max_depth': 6, 'learning_rate': 0.018576966954164022, 'min_child_weight': 1, 'subsample': 0.6402182019004918, 'colsample_bytree': 0.8953495839474268, 'gamma': 1.9385073783826383, 'reg_alpha': 0.14534984477447524, 'reg_lambda': 0.11013004277239107}

Optimización XGBoost | CU | prep=normal

[I 2026-09-21 16:07:48,340] Trial 0 finished with value: 0.6561369545795308 and parameters: {'ngram_range': '1_2', 'n_estimators': 500, 'max_depth': 6, 'learning_rate': 0.01700037298921102, 'min_child_weight': 2, 'subsample': 0.6232334448672797, 'colsample_bytree': 0.9330880728874675, 'gamma': 3.005575058716044, 'reg_alpha': 0.21242802137208885, 'reg_lambda': 0.10994335574766201}. Best is trial 0 with value: 0.6561369545795308.
[I 2026-09-21 16:07:49,616] Trial 1 finished with value: 0.6509671728456838 and parameters: {'ngram_range': '1_1', 'n_estimators': 200, 'max_depth': 3, 'learning_rate': 0.018659959624904916, 'min_child_weight': 4, 'subsample': 0.8099025726528951, 'colsample_bytree': 0.7159725093210578, 'gamma': 1.4561457009902097, 'reg_alpha': 0.07500295933641415, 'reg_lambda': 0.19010245319870356}. Best is trial 0 with value: 0.6561369545795308.
[I 2026-09-21 16:07:56,497] Trial 2 finished with value: 0.6528777972774844 and parameters: {'ngram_range': '1_2', 'n_estimators': 350, 'max_depth': 7, 'learning_rate': 0.019721610970574007, 'min_child_weight': 6, 'subsample': 0.836965827544817, 'colsample_bytree': 0.5232252063599989, 'gamma': 3.0377242595071916, 'reg_alpha': 0.00063283099528693, 'reg_lambda': 0.1349283426801325}. Best is trial 0 with value: 0.6561369545795308.
[I 2026-09-21 16:08:03,228] Trial 3 finished with value: 0.6463506959045457 and parameters: {'ngram_range': '1_2', 'n_estimators': 500, 'max_depth': 4, 'learning_rate': 0.013940346079873234, 'min_child_weight': 7, 'subsample': 0.7760609974958406, 'colsample_bytree': 0.5610191174223894, 'gamma': 2.475884550556351, 'reg_alpha': 0.00014507434860119788, 'reg_lambda': 6.586289317583113}. Best is trial 0 with value: 0.6561369545795308.
[I 2026-09-21 16:08:06,779] Trial 4 finished with value: 0.6472268795978771 and parameters: {'ngram_range': '1_2', 'n_estimators': 250, 'max_depth': 5, 'learning_rate': 0.06420330336297862, 'min_child_weight': 2, 'subsample': 0.9878338511058234, 'colsample_bytree': 0.8875664116805573, 'gamma': 4.697494707820946, 'reg_alpha': 1.6023850290194919, 'reg_lambda': 1.5696396388661147}. Best is trial 0 with value: 0.6561369545795308.
[I 2026-09-21 16:08:07,906] Trial 5 finished with value: 0.6497592426434998 and parameters: {'ngram_range': '1_1', 'n_estimators': 200, 'max_depth': 2, 'learning_rate': 0.03023795012558475, 'min_child_weight': 4, 'subsample': 0.7085396127095583, 'colsample_bytree': 0.9143687545759647, 'gamma': 1.7837666334679465, 'reg_alpha': 0.002089790902378636, 'reg_lambda': 1.2172847081122433}. Best is trial 0 with value: 0.6561369545795308.
[I 2026-09-21 16:08:11,191] Trial 6 finished with value: 0.6295670753977579 and parameters: {'ngram_range': '1_2', 'n_estimators': 100, 'max_depth': 8, 'learning_rate': 0.13826083091896751, 'min_child_weight': 2, 'subsample': 0.602208846849441, 'colsample_bytree': 0.9077307142274171, 'gamma': 3.534286719238086, 'reg_alpha': 0.2664298103063688, 'reg_lambda': 3.487712624545931}. Best is trial 0 with value: 0.6561369545795308.
[I 2026-09-21 16:08:15,572] Trial 7 finished with value: 0.6313355969890666 and parameters: {'ngram_range': '1_2', 'n_estimators': 150, 'max_depth': 8, 'learning_rate': 0.08330803890301997, 'min_child_weight': 4, 'subsample': 0.6254233401144095, 'colsample_bytree': 0.6554911608578311, 'gamma': 1.6259166101337352, 'reg_alpha': 0.2681621920201289, 'reg_lambda': 1.8841476921545086}. Best is trial 0 with value: 0.6561369545795308.
[I 2026-09-21 16:08:17,064] Trial 8 finished with value: 0.6411481092666704 and parameters: {'ngram_range': '1_1', 'n_estimators': 150, 'max_depth': 6, 'learning_rate': 0.13297554090738672, 'min_child_weight': 6, 'subsample': 0.9083868719818244, 'colsample_bytree': 0.7468977981821954, 'gamma': 2.6136641469099704, 'reg_alpha': 0.01020945174752076, 'reg_lambda': 0.11241862095793062}. Best is trial 0 with value: 0.6561369545795308.
[I 2026-09-21 16:08:19,490] Trial 9 finished with value: 0.6269255432374304 and parameters: {'ngram_range': '1_1', 'n_estimators': 450, 'max_depth': 4, 'learning_rate': 0.056392399916675585, 'min_child_weight': 10, 'subsample': 0.69971689165955, 'colsample_bytree': 0.7051914615178149, 'gamma': 3.7777556927152434, 'reg_alpha': 0.0011888189431127753, 'reg_lambda': 0.14254757044027438}. Best is trial 0 with value: 0.6561369545795308.
[I 2026-09-21 16:08:25,362] Trial 10 finished with value: 0.6481049336917607 and parameters: {'ngram_range': '1_2', 'n_estimators': 400, 'max_depth': 3, 'learning_rate': 0.010997892892266298, 'min_child_weight': 1, 'subsample': 0.60534964551543, 'colsample_bytree': 0.9733411210431508, 'gamma': 3.8612153893692973, 'reg_alpha': 0.32770250592194367, 'reg_lambda': 1.5566568870534958}. Best is trial 0 with value: 0.6561369545795308.
[I 2026-09-21 16:08:31,727] Trial 11 finished with value: 0.6312926398913239 and parameters: {'ngram_range': '1_2', 'n_estimators': 300, 'max_depth': 6, 'learning_rate': 0.012366957934873812, 'min_child_weight': 7, 'subsample': 0.626927965681923, 'colsample_bytree': 0.7889807923368855, 'gamma': 3.3572128321999046, 'reg_alpha': 0.0010767890347676986, 'reg_lambda': 0.22526879406529676}. Best is trial 0 with value: 0.6561369545795308.
[I 2026-09-21 16:08:40,943] Trial 12 finished with value: 0.6459579318463089 and parameters: {'ngram_range': '1_2', 'n_estimators': 400, 'max_depth': 7, 'learning_rate': 0.0278831361445616, 'min_child_weight': 1, 'subsample': 0.6937285540741707, 'colsample_bytree': 0.5983254697005944, 'gamma': 1.7945815483809504, 'reg_alpha': 2.686946486735592, 'reg_lambda': 0.14325328802570483}. Best is trial 0 with value: 0.6561369545795308.
[I 2026-09-21 16:08:49,808] Trial 13 finished with value: 0.643391529991867 and parameters: {'ngram_range': '1_2', 'n_estimators': 400, 'max_depth': 8, 'learning_rate': 0.027754176205728006, 'min_child_weight': 3, 'subsample': 0.8151659265162021, 'colsample_bytree': 0.7510534415932039, 'gamma': 3.193305415596994, 'reg_alpha': 0.0020580520194473048, 'reg_lambda': 0.23815709732946774}. Best is trial 0 with value: 0.6561369545795308.
[I 2026-09-21 16:09:01,372] Trial 14 finished with value: 0.6597292982677381 and parameters: {'ngram_range': '1_2', 'n_estimators': 600, 'max_depth': 5, 'learning_rate': 0.010121471544216328, 'min_child_weight': 1, 'subsample': 0.7560762637635987, 'colsample_bytree': 0.9517616828186402, 'gamma': 2.1944383463728157, 'reg_alpha': 0.00012718928455652444, 'reg_lambda': 0.10524765495983048}. Best is trial 14 with value: 0.6597292982677381.
[I 2026-09-21 16:09:10,327] Trial 15 finished with value: 0.6639776909850441 and parameters: {'ngram_range': '1_2', 'n_estimators': 500, 'max_depth': 5, 'learning_rate': 0.012783238088262355, 'min_child_weight': 3, 'subsample': 0.7235344806832062, 'colsample_bytree': 0.9470327636274011, 'gamma': 1.9575183472049567, 'reg_alpha': 0.005464473878189262, 'reg_lambda': 0.1423222807732052}. Best is trial 15 with value: 0.6639776909850441.
[I 2026-09-21 16:09:21,406] Trial 16 finished with value: 0.6488478586496007 and parameters: {'ngram_range': '1_2', 'n_estimators': 600, 'max_depth': 6, 'learning_rate': 0.011931432240954014, 'min_child_weight': 4, 'subsample': 0.8144053619979188, 'colsample_bytree': 0.8686460751285218, 'gamma': 2.33787251822715, 'reg_alpha': 0.0001632239797658963, 'reg_lambda': 0.18855565436891109}. Best is trial 15 with value: 0.6639776909850441.
[I 2026-09-21 16:09:27,235] Trial 17 finished with value: 0.6590460055824012 and parameters: {'ngram_range': '1_2', 'n_estimators': 450, 'max_depth': 3, 'learning_rate': 0.014975138268110129, 'min_child_weight': 2, 'subsample': 0.6879464411456082, 'colsample_bytree': 0.8745475600544477, 'gamma': 2.8879051884502913, 'reg_alpha': 0.001073294926348788, 'reg_lambda': 0.3049753951212839}. Best is trial 15 with value: 0.6639776909850441.
[I 2026-09-21 16:09:34,354] Trial 18 finished with value: 0.6478122295575147 and parameters: {'ngram_range': '1_2', 'n_estimators': 600, 'max_depth': 3, 'learning_rate': 0.025534157577519093, 'min_child_weight': 5, 'subsample': 0.770582438648878, 'colsample_bytree': 0.9240849721816181, 'gamma': 1.4892970352286312, 'reg_alpha': 0.0014275889077650314, 'reg_lambda': 0.11868150260172068}. Best is trial 15 with value: 0.6639776909850441.
[I 2026-09-21 16:09:39,160] Trial 19 finished with value: 0.6610772213096527 and parameters: {'ngram_range': '1_1', 'n_estimators': 550, 'max_depth': 5, 'learning_rate': 0.015213012087481253, 'min_child_weight': 1, 'subsample': 0.6771966932460015, 'colsample_bytree': 0.9043701326726447, 'gamma': 1.2726474070518794, 'reg_alpha': 0.0030651929387015193, 'reg_lambda': 0.10982100956989327}. Best is trial 15 with value: 0.6639776909850441.
[I 2026-09-21 16:09:44,041] Trial 20 finished with value: 0.657761801024993 and parameters: {'ngram_range': '1_1', 'n_estimators': 550, 'max_depth': 5, 'learning_rate': 0.011291208284904541, 'min_child_weight': 1, 'subsample': 0.6175768550842304, 'colsample_bytree': 0.892818465077003, 'gamma': 0.9799124920186656, 'reg_alpha': 0.150322115479581, 'reg_lambda': 0.13099611651644538}. Best is trial 15 with value: 0.6639776909850441.
[I 2026-09-21 16:09:54,361] Trial 21 finished with value: 0.6451834838887869 and parameters: {'ngram_range': '1_2', 'n_estimators': 600, 'max_depth': 5, 'learning_rate': 0.010105671419993889, 'min_child_weight': 5, 'subsample': 0.7063934515809632, 'colsample_bytree': 0.9650943067173611, 'gamma': 3.100902244991925, 'reg_alpha': 0.0006733784264024063, 'reg_lambda': 0.11028179815291612}. Best is trial 15 with value: 0.6639776909850441.
[I 2026-09-21 16:10:04,031] Trial 22 finished with value: 0.6556881406510324 and parameters: {'ngram_range': '1_2', 'n_estimators': 550, 'max_depth': 5, 'learning_rate': 0.020026487965594565, 'min_child_weight': 1, 'subsample': 0.7308681339956808, 'colsample_bytree': 0.829413433859884, 'gamma': 1.2902336803391856, 'reg_alpha': 0.0020056805667034773, 'reg_lambda': 0.24984772598746902}. Best is trial 15 with value: 0.6639776909850441.
[I 2026-09-21 16:10:07,769] Trial 23 finished with value: 0.6605439550905665 and parameters: {'ngram_range': '1_1', 'n_estimators': 450, 'max_depth': 5, 'learning_rate': 0.01882857792008122, 'min_child_weight': 3, 'subsample': 0.6983405328554558, 'colsample_bytree': 0.9329459343829776, 'gamma': 0.4031348589778919, 'reg_alpha': 0.004115818450419879, 'reg_lambda': 0.12225139150836285}. Best is trial 15 with value: 0.6639776909850441.
[I 2026-09-21 16:10:11,936] Trial 24 finished with value: 0.6565955494098348 and parameters: {'ngram_range': '1_1', 'n_estimators': 500, 'max_depth': 5, 'learning_rate': 0.011124644612209767, 'min_child_weight': 3, 'subsample': 0.6392604824989742, 'colsample_bytree': 0.9455810099392782, 'gamma': 0.1807484907619977, 'reg_alpha': 0.004249934406760192, 'reg_lambda': 0.11788479312387437}. Best is trial 15 with value: 0.6639776909850441.
[I 2026-09-21 16:10:16,911] Trial 25 finished with value: 0.6534045344057466 and parameters: {'ngram_range': '1_1', 'n_estimators': 500, 'max_depth': 6, 'learning_rate': 0.0432454427695586, 'min_child_weight': 1, 'subsample': 0.6269497853490419, 'colsample_bytree': 0.9751362037148597, 'gamma': 1.7568333120179016, 'reg_alpha': 0.004978331765799753, 'reg_lambda': 0.1199497792075727}. Best is trial 15 with value: 0.6639776909850441.
[I 2026-09-21 16:10:21,230] Trial 26 finished with value: 0.6586565153403134 and parameters: {'ngram_range': '1_1', 'n_estimators': 550, 'max_depth': 5, 'learning_rate': 0.021325443791294998, 'min_child_weight': 3, 'subsample': 0.6445905991735794, 'colsample_bytree': 0.9167260415444698, 'gamma': 1.0297127097392076, 'reg_alpha': 0.0007312528999431078, 'reg_lambda': 0.17338635826841067}. Best is trial 15 with value: 0.6639776909850441.
[I 2026-09-21 16:10:25,598] Trial 27 finished with value: 0.6534655611523744 and parameters: {'ngram_range': '1_1', 'n_estimators': 400, 'max_depth': 6, 'learning_rate': 0.030055992632662776, 'min_child_weight': 1, 'subsample': 0.6132661212320708, 'colsample_bytree': 0.967477278367564, 'gamma': 0.7190961846590187, 'reg_alpha': 0.0037187967742101776, 'reg_lambda': 0.10708547035102423}. Best is trial 15 with value: 0.6639776909850441.
[I 2026-09-21 16:10:29,056] Trial 28 finished with value: 0.6597156493439222 and parameters: {'ngram_range': '1_1', 'n_estimators': 550, 'max_depth': 4, 'learning_rate': 0.012258840787318898, 'min_child_weight': 4, 'subsample': 0.6762058675080979, 'colsample_bytree': 0.8220267862887609, 'gamma': 1.7444763108064807, 'reg_alpha': 0.002160058018448197, 'reg_lambda': 0.11667867362399253}. Best is trial 15 with value: 0.6639776909850441.
[I 2026-09-21 16:10:33,801] Trial 29 finished with value: 0.6596664086068037 and parameters: {'ngram_range': '1_1', 'n_estimators': 450, 'max_depth': 6, 'learning_rate': 0.010853362486467693, 'min_child_weight': 2, 'subsample': 0.6588887422439617, 'colsample_bytree': 0.9913036722682305, 'gamma': 1.2235212715875892, 'reg_alpha': 0.000825281094973696, 'reg_lambda': 0.19354227597150414}. Best is trial 15 with value: 0.6639776909850441.
[I 2026-09-21 16:10:44,425] Trial 30 finished with value: 0.6530714575594461 and parameters: {'ngram_range': '1_2', 'n_estimators': 550, 'max_depth': 6, 'learning_rate': 0.019203394545150645, 'min_child_weight': 2, 'subsample': 0.7678864666135952, 'colsample_bytree': 0.964406267224999, 'gamma': 2.0246283505021765, 'reg_alpha': 0.017238003995730507, 'reg_lambda': 0.1484859459356272}. Best is trial 15 with value: 0.6639776909850441.
[I 2026-09-21 16:10:48,535] Trial 31 finished with value: 0.6644206174255011 and parameters: {'ngram_range': '1_1', 'n_estimators': 500, 'max_depth': 5, 'learning_rate': 0.03290070837626756, 'min_child_weight': 2, 'subsample': 0.6794287498453179, 'colsample_bytree': 0.8968866894385593, 'gamma': 0.02860077698247082, 'reg_alpha': 0.003263139755848535, 'reg_lambda': 0.20833031125708917}. Best is trial 31 with value: 0.6644206174255011.
[I 2026-09-21 16:10:52,858] Trial 32 finished with value: 0.6462196727016145 and parameters: {'ngram_range': '1_1', 'n_estimators': 550, 'max_depth': 5, 'learning_rate': 0.04563459101939318, 'min_child_weight': 3, 'subsample': 0.7380660143996686, 'colsample_bytree': 0.9543633239669161, 'gamma': 1.0139162661037215, 'reg_alpha': 0.004023833670032595, 'reg_lambda': 0.11438549258076167}. Best is trial 31 with value: 0.6644206174255011.
[I 2026-09-21 16:10:57,186] Trial 33 finished with value: 0.653302633777409 and parameters: {'ngram_range': '1_1', 'n_estimators': 550, 'max_depth': 5, 'learning_rate': 0.03136774905158229, 'min_child_weight': 3, 'subsample': 0.6147785912763347, 'colsample_bytree': 0.9336190055150492, 'gamma': 0.3822031801257318, 'reg_alpha': 0.01530853856141213, 'reg_lambda': 0.15570937103517343}. Best is trial 31 with value: 0.6644206174255011.
[I 2026-09-21 16:11:01,856] Trial 34 finished with value: 0.6635472369964026 and parameters: {'ngram_range': '1_1', 'n_estimators': 550, 'max_depth': 5, 'learning_rate': 0.023864392326725853, 'min_child_weight': 2, 'subsample': 0.68322724875011, 'colsample_bytree': 0.9967703515217641, 'gamma': 1.9410999625690484, 'reg_alpha': 0.0027438103402676723, 'reg_lambda': 0.12147256210477372}. Best is trial 31 with value: 0.6644206174255011.
[I 2026-09-21 16:11:06,042] Trial 35 finished with value: 0.6624261486087025 and parameters: {'ngram_range': '1_1', 'n_estimators': 500, 'max_depth': 5, 'learning_rate': 0.01715125887950906, 'min_child_weight': 2, 'subsample': 0.6660445873293057, 'colsample_bytree': 0.9723543903651376, 'gamma': 1.6381460238182228, 'reg_alpha': 0.0021412841600767793, 'reg_lambda': 0.11102785368658954}. Best is trial 31 with value: 0.6644206174255011.
[I 2026-09-21 16:11:10,098] Trial 36 finished with value: 0.6576029718343015 and parameters: {'ngram_range': '1_1', 'n_estimators': 550, 'max_depth': 4, 'learning_rate': 0.02380217866018483, 'min_child_weight': 1, 'subsample': 0.6665961600270759, 'colsample_bytree': 0.9910253502997184, 'gamma': 2.142011399703669, 'reg_alpha': 0.0003826757583588755, 'reg_lambda': 0.13966375553540902}. Best is trial 31 with value: 0.6644206174255011.
[I 2026-09-21 16:11:15,785] Trial 37 finished with value: 0.6657682104178313 and parameters: {'ngram_range': '1_1', 'n_estimators': 550, 'max_depth': 6, 'learning_rate': 0.01600436534189987, 'min_child_weight': 1, 'subsample': 0.6926313544843302, 'colsample_bytree': 0.9454259746560817, 'gamma': 1.7668908604921798, 'reg_alpha': 0.0006355245104995689, 'reg_lambda': 0.11972684148846344}. Best is trial 37 with value: 0.6657682104178313.
[I 2026-09-21 16:11:24,288] Trial 38 finished with value: 0.6504255268709415 and parameters: {'ngram_range': '1_2', 'n_estimators': 500, 'max_depth': 5, 'learning_rate': 0.017325693870429693, 'min_child_weight': 4, 'subsample': 0.696276260305004, 'colsample_bytree': 0.936185085112355, 'gamma': 1.6344041531033453, 'reg_alpha': 0.01222362130833503, 'reg_lambda': 0.19970059902284745}. Best is trial 37 with value: 0.6657682104178313.
[I 2026-09-21 16:11:28,481] Trial 39 finished with value: 0.6665622610215698 and parameters: {'ngram_range': '1_1', 'n_estimators': 600, 'max_depth': 4, 'learning_rate': 0.021187376439248576, 'min_child_weight': 2, 'subsample': 0.679064775548546, 'colsample_bytree': 0.9984406625629536, 'gamma': 1.5234621896540699, 'reg_alpha': 0.0052269265404755955, 'reg_lambda': 0.15877742777317128}. Best is trial 39 with value: 0.6665622610215698.
[I 2026-09-21 16:11:34,258] Trial 40 finished with value: 0.6575648240084864 and parameters: {'ngram_range': '1_1', 'n_estimators': 550, 'max_depth': 6, 'learning_rate': 0.01154440450724044, 'min_child_weight': 1, 'subsample': 0.6288381812674657, 'colsample_bytree': 0.910394431030602, 'gamma': 1.6779961008109987, 'reg_alpha': 0.0013930267652124664, 'reg_lambda': 0.12316249633053905}. Best is trial 39 with value: 0.6665622610215698.
[I 2026-09-21 16:11:38,677] Trial 41 finished with value: 0.6595188383354298 and parameters: {'ngram_range': '1_1', 'n_estimators': 550, 'max_depth': 5, 'learning_rate': 0.012192774339267116, 'min_child_weight': 3, 'subsample': 0.678472738368486, 'colsample_bytree': 0.930109269951628, 'gamma': 2.1614204059128572, 'reg_alpha': 0.007645264739713988, 'reg_lambda': 0.16060066349630417}. Best is trial 39 with value: 0.6665622610215698.
[I 2026-09-21 16:11:42,309] Trial 42 finished with value: 0.6574579536937059 and parameters: {'ngram_range': '1_1', 'n_estimators': 550, 'max_depth': 4, 'learning_rate': 0.022033116256750734, 'min_child_weight': 3, 'subsample': 0.7005764244839993, 'colsample_bytree': 0.9749291650174282, 'gamma': 2.190186922487828, 'reg_alpha': 0.0008596482902849816, 'reg_lambda': 0.12466518092777375}. Best is trial 39 with value: 0.6665622610215698.
[I 2026-09-21 16:11:47,223] Trial 43 finished with value: 0.6573665584694649 and parameters: {'ngram_range': '1_1', 'n_estimators': 600, 'max_depth': 5, 'learning_rate': 0.01821739345855603, 'min_child_weight': 2, 'subsample': 0.6231356549809726, 'colsample_bytree': 0.9867855588202479, 'gamma': 2.6569399214124405, 'reg_alpha': 0.004072850418238001, 'reg_lambda': 0.185213269982514}. Best is trial 39 with value: 0.6665622610215698.
[I 2026-09-21 16:11:51,596] Trial 44 finished with value: 0.6583937038937051 and parameters: {'ngram_range': '1_1', 'n_estimators': 550, 'max_depth': 5, 'learning_rate': 0.02791049307156685, 'min_child_weight': 2, 'subsample': 0.6823313834121361, 'colsample_bytree': 0.9268590063845105, 'gamma': 1.8803107125631378, 'reg_alpha': 0.006924355945127777, 'reg_lambda': 0.18662465879379053}. Best is trial 39 with value: 0.6665622610215698.

Mejor F1-Macro CV:
0.6665622610215698

Mejores hiperparámetros:
{'ngram_range': '1_1', 'n_estimators': 600, 'max_depth': 4, 'learning_rate': 0.021187376439248576, 'min_child_weight': 2, 'subsample': 0.679064775548546, 'colsample_bytree': 0.9984406625629536, 'gamma': 1.5234621896540699, 'reg_alpha': 0.0052269265404755955, 'reg_lambda': 0.15877742777317128}

In [28]:
resumen_optuna = pd.DataFrame([
    {
        "variante": "mx",
        "preprocessing": PREP_GANADOR["mx"],
        "best_f1_macro_cv": study_mx.best_value,
        **study_mx.best_params
    },
    {
        "variante": "es",
        "preprocessing": PREP_GANADOR["es"],
        "best_f1_macro_cv": study_es.best_value,
        **study_es.best_params
    },
    {
        "variante": "cu",
        "preprocessing": PREP_GANADOR["cu"],
        "best_f1_macro_cv": study_cu.best_value,
        **study_cu.best_params
    }
])

resumen_optuna

,variante,preprocessing,best_f1_macro_cv,ngram_range,n_estimators,max_depth,learning_rate,min_child_weight,subsample,colsample_bytree,gamma,reg_alpha,reg_lambda
0,mx,lemma,0.623517,1_2,550,7,0.016597,3,0.737524,0.661694,3.569176,0.000408,0.574515
1,es,normal,0.703954,1_1,550,6,0.018577,1,0.640218,0.895350,1.938507,0.145350,0.110130
2,cu,normal,0.666562,1_1,600,4,0.021187,2,0.679065,0.998441,1.523462,0.005227,0.158777

In [29]:
f1_base = {
    "mx": 0.600949,
    "es": 0.686399,
    "cu": 0.653014
}

comparacion = resumen_optuna[
    ["variante", "preprocessing", "best_f1_macro_cv", "ngram_range"]
].copy()

comparacion["f1_xgb_base"] = comparacion["variante"].map(f1_base)

comparacion["mejora_optuna"] = (
    comparacion["best_f1_macro_cv"]
    - comparacion["f1_xgb_base"]
)

comparacion = comparacion[
    [
        "variante",
        "preprocessing",
        "f1_xgb_base",
        "best_f1_macro_cv",
        "mejora_optuna",
        "ngram_range"
    ]
]

comparacion

,variante,preprocessing,f1_xgb_base,best_f1_macro_cv,mejora_optuna,ngram_range
0,mx,lemma,0.600949,0.623517,0.022568,1_2
1,es,normal,0.686399,0.703954,0.017555,1_1
2,cu,normal,0.653014,0.666562,0.013548,1_1

In [30]:
def objective_final(trial, df_train):

    X = df_train[
        ["MESSAGE_CLEAN"] + FEATURE_COLS
    ]

    y = df_train["IS_IRONIC"].values

    scale_pos_weight = (
        (y == 0).sum() /
        (y == 1).sum()
    )

    params = {
        "n_estimators": trial.suggest_int(
            "n_estimators", 50, 600, step=50
        ),

        "max_depth": trial.suggest_int(
            "max_depth", 2, 10
        ),

        "learning_rate": trial.suggest_float(
            "learning_rate",
            0.01,
            0.30,
            log=True
        ),

        "min_child_weight": trial.suggest_int(
            "min_child_weight", 1, 10
        ),

        "subsample": trial.suggest_float(
            "subsample", 0.5, 1.0
        ),

        "colsample_bytree": trial.suggest_float(
            "colsample_bytree", 0.4, 1.0
        ),

        "gamma": trial.suggest_float(
            "gamma", 0.0, 5.0
        ),

        "reg_alpha": trial.suggest_float(
            "reg_alpha",
            1e-4,
            5.0,
            log=True
        ),

        "reg_lambda": trial.suggest_float(
            "reg_lambda",
            0.01,
            10.0,
            log=True
        )
    }

    model = XGBClassifier(
        **params,
        scale_pos_weight=scale_pos_weight,
        objective="binary:logistic",
        eval_metric="logloss",
        booster="gbtree",
        tree_method="hist",
        random_state=RANDOM_STATE,
        n_jobs=-1
    )

    pipeline = Pipeline([
        (
            "prep",
            build_tfidf_prep((1, 2))
        ),
        ("clf", model)
    ])

    scores = cross_val_score(
        pipeline,
        X,
        y,
        cv=CV,
        scoring="f1_macro",
        n_jobs=1
    )

    return scores.mean()

In [31]:
def optimizar_variante_final(variante, n_trials=50):

    df_train = cargar_train_ganador(variante)

    study = optuna.create_study(
        direction="maximize",
        sampler=optuna.samplers.TPESampler(
            seed=RANDOM_STATE
        )
    )

    study.optimize(
        lambda trial: objective_final(
            trial,
            df_train
        ),
        n_trials=n_trials
    )

    print(
        f"{variante.upper()} | "
        f"F1-Macro={study.best_value:.6f}"
    )

    print(study.best_params)

    return study

In [32]:
study_mx_final = optimizar_variante_final(
    "mx",
    n_trials=50
)

study_es_final = optimizar_variante_final(
    "es",
    n_trials=50
)

study_cu_final = optimizar_variante_final(
    "cu",
    n_trials=50
)

[I 2026-09-21 16:12:17,016] A new study created in memory with name: no-name-1bcaf185-9800-4c88-9567-66713a5f0f5b
[I 2026-09-21 16:12:21,338] Trial 0 finished with value: 0.5898527423946123 and parameters: {'n_estimators': 250, 'max_depth': 10, 'learning_rate': 0.1205712628744377, 'min_child_weight': 6, 'subsample': 0.5780093202212182, 'colsample_bytree': 0.49359671220172163, 'gamma': 0.2904180608409973, 'reg_alpha': 1.1752647960576206, 'reg_lambda': 0.6358358856676253}. Best is trial 0 with value: 0.5898527423946123.
[I 2026-09-21 16:12:24,152] Trial 1 finished with value: 0.5863772669119584 and parameters: {'n_estimators': 450, 'max_depth': 2, 'learning_rate': 0.2708160864249968, 'min_child_weight': 9, 'subsample': 0.6061695553391381, 'colsample_bytree': 0.5090949803242604, 'gamma': 0.9170225492671691, 'reg_alpha': 0.0026892128247368906, 'reg_lambda': 0.3752055855124282}. Best is trial 0 with value: 0.5898527423946123.
[I 2026-09-21 16:12:27,070] Trial 2 finished with value: 0.6037626774725553 and parameters: {'n_estimators': 300, 'max_depth': 4, 'learning_rate': 0.08012737503998542, 'min_child_weight': 2, 'subsample': 0.6460723242676091, 'colsample_bytree': 0.619817105976215, 'gamma': 2.28034992108518, 'reg_alpha': 0.48923586931905244, 'reg_lambda': 0.039721107273819126}. Best is trial 2 with value: 0.6037626774725553.
[I 2026-09-21 16:12:30,289] Trial 3 finished with value: 0.5862059412037197 and parameters: {'n_estimators': 350, 'max_depth': 7, 'learning_rate': 0.011711509955524094, 'min_child_weight': 7, 'subsample': 0.5852620618436457, 'colsample_bytree': 0.43903095579116774, 'gamma': 4.7444276862666666, 'reg_alpha': 3.447275228705856, 'reg_lambda': 2.6619018884890564}. Best is trial 2 with value: 0.6037626774725553.
[I 2026-09-21 16:12:32,023] Trial 4 finished with value: 0.5882739079839359 and parameters: {'n_estimators': 200, 'max_depth': 2, 'learning_rate': 0.1024932221692416, 'min_child_weight': 5, 'subsample': 0.5610191174223894, 'colsample_bytree': 0.6971061460667621, 'gamma': 0.17194260557609198, 'reg_alpha': 1.8744302901656154, 'reg_lambda': 0.059750279999602945}. Best is trial 2 with value: 0.6037626774725553.
[I 2026-09-21 16:12:35,525] Trial 5 finished with value: 0.5990681312204966 and parameters: {'n_estimators': 400, 'max_depth': 4, 'learning_rate': 0.05864129169696527, 'min_child_weight': 6, 'subsample': 0.5924272277627636, 'colsample_bytree': 0.9817507766587351, 'gamma': 3.8756641168055728, 'reg_alpha': 2.5982285195767814, 'reg_lambda': 4.83595277646595}. Best is trial 2 with value: 0.6037626774725553.
[I 2026-09-21 16:12:42,870] Trial 6 finished with value: 0.6097376768114048 and parameters: {'n_estimators': 400, 'max_depth': 10, 'learning_rate': 0.01351182947645082, 'min_child_weight': 2, 'subsample': 0.522613644455269, 'colsample_bytree': 0.5951981984579586, 'gamma': 1.9433864484474102, 'reg_alpha': 0.001883913511943895, 'reg_lambda': 3.063462210622083}. Best is trial 6 with value: 0.6097376768114048.
[I 2026-09-21 16:12:45,197] Trial 7 finished with value: 0.6090392754831586 and parameters: {'n_estimators': 250, 'max_depth': 4, 'learning_rate': 0.06333268775321843, 'min_child_weight': 2, 'subsample': 0.9010984903770198, 'colsample_bytree': 0.44473038620786254, 'gamma': 4.9344346830025865, 'reg_alpha': 0.425358393373768, 'reg_lambda': 0.039459088111000004}. Best is trial 6 with value: 0.6097376768114048.
[I 2026-09-21 16:12:46,777] Trial 8 finished with value: 0.5884588125642812 and parameters: {'n_estimators': 50, 'max_depth': 9, 'learning_rate': 0.11069143219393454, 'min_child_weight': 8, 'subsample': 0.8856351733429728, 'colsample_bytree': 0.44442679104045424, 'gamma': 1.7923286427213632, 'reg_alpha': 0.0003503202443763074, 'reg_lambda': 3.8842777547031417}. Best is trial 6 with value: 0.6097376768114048.
[I 2026-09-21 16:12:50,728] Trial 9 finished with value: 0.5936151175473783 and parameters: {'n_estimators': 400, 'max_depth': 4, 'learning_rate': 0.012413189635294229, 'min_child_weight': 4, 'subsample': 0.6625916610133735, 'colsample_bytree': 0.8377637070028385, 'gamma': 3.1877873567760657, 'reg_alpha': 1.475659183168782, 'reg_lambda': 0.26100256506134767}. Best is trial 6 with value: 0.6097376768114048.
[I 2026-09-21 16:12:53,678] Trial 10 finished with value: 0.5863240075212982 and parameters: {'n_estimators': 200, 'max_depth': 7, 'learning_rate': 0.010165153289426599, 'min_child_weight': 8, 'subsample': 0.641495425707468, 'colsample_bytree': 0.6511402524184409, 'gamma': 2.5522076344962668, 'reg_alpha': 0.00015163142102274098, 'reg_lambda': 5.4217241059780585}. Best is trial 6 with value: 0.6097376768114048.
[I 2026-09-21 16:13:00,155] Trial 11 finished with value: 0.6002402263069928 and parameters: {'n_estimators': 500, 'max_depth': 7, 'learning_rate': 0.03487908516668871, 'min_child_weight': 1, 'subsample': 0.5048526073975149, 'colsample_bytree': 0.6867026310025903, 'gamma': 2.518069947139868, 'reg_alpha': 0.000239457815284188, 'reg_lambda': 9.22119700635711}. Best is trial 6 with value: 0.6097376768114048.
[I 2026-09-21 16:13:03,341] Trial 12 finished with value: 0.615276732177619 and parameters: {'n_estimators': 250, 'max_depth': 10, 'learning_rate': 0.06683573849679036, 'min_child_weight': 3, 'subsample': 0.7890278658400848, 'colsample_bytree': 0.5021709338053387, 'gamma': 4.287767884787277, 'reg_alpha': 0.022001831598053367, 'reg_lambda': 0.37203887020388676}. Best is trial 12 with value: 0.615276732177619.
[I 2026-09-21 16:13:09,073] Trial 13 finished with value: 0.6081305901475713 and parameters: {'n_estimators': 350, 'max_depth': 10, 'learning_rate': 0.01400752034690876, 'min_child_weight': 3, 'subsample': 0.5036624571427474, 'colsample_bytree': 0.5564077836165877, 'gamma': 3.236264543305638, 'reg_alpha': 0.06980297979840236, 'reg_lambda': 1.3523428241544742}. Best is trial 12 with value: 0.615276732177619.
[I 2026-09-21 16:13:16,052] Trial 14 finished with value: 0.6017213860165361 and parameters: {'n_estimators': 350, 'max_depth': 9, 'learning_rate': 0.011861894843839788, 'min_child_weight': 2, 'subsample': 0.7926329187575657, 'colsample_bytree': 0.6808917297374496, 'gamma': 1.0934563355932783, 'reg_alpha': 0.012788860404671303, 'reg_lambda': 2.253652948435472}. Best is trial 12 with value: 0.615276732177619.
[I 2026-09-21 16:13:22,379] Trial 15 finished with value: 0.6075007172110074 and parameters: {'n_estimators': 400, 'max_depth': 10, 'learning_rate': 0.021801484407643686, 'min_child_weight': 4, 'subsample': 0.6799187465798557, 'colsample_bytree': 0.5003263669305892, 'gamma': 2.074787295407342, 'reg_alpha': 0.0007180565551987451, 'reg_lambda': 4.559427450975094}. Best is trial 12 with value: 0.615276732177619.
[I 2026-09-21 16:13:28,078] Trial 16 finished with value: 0.6056507024606935 and parameters: {'n_estimators': 400, 'max_depth': 10, 'learning_rate': 0.017780746878966337, 'min_child_weight': 3, 'subsample': 0.848609810623492, 'colsample_bytree': 0.6133163548423057, 'gamma': 4.018490880583425, 'reg_alpha': 0.00803690866010703, 'reg_lambda': 4.631743367931014}. Best is trial 12 with value: 0.615276732177619.
[I 2026-09-21 16:13:31,393] Trial 17 finished with value: 0.6030977284916187 and parameters: {'n_estimators': 300, 'max_depth': 9, 'learning_rate': 0.06840078527540437, 'min_child_weight': 2, 'subsample': 0.5260826847547203, 'colsample_bytree': 0.4209128179080315, 'gamma': 4.599848432784208, 'reg_alpha': 0.003986036709452274, 'reg_lambda': 0.4857032886629016}. Best is trial 12 with value: 0.615276732177619.
[I 2026-09-21 16:13:36,905] Trial 18 finished with value: 0.6187638809245332 and parameters: {'n_estimators': 400, 'max_depth': 10, 'learning_rate': 0.0281441868131273, 'min_child_weight': 3, 'subsample': 0.7009078674717488, 'colsample_bytree': 0.7478466631276325, 'gamma': 4.445308445804967, 'reg_alpha': 0.011167693295782965, 'reg_lambda': 0.24062863967479511}. Best is trial 18 with value: 0.6187638809245332.
[I 2026-09-21 16:13:42,620] Trial 19 finished with value: 0.6215176535412399 and parameters: {'n_estimators': 400, 'max_depth': 9, 'learning_rate': 0.036313222657702045, 'min_child_weight': 3, 'subsample': 0.7628904861402903, 'colsample_bytree': 0.8461307322279774, 'gamma': 3.3152743190232457, 'reg_alpha': 0.010295306691623568, 'reg_lambda': 0.06381715791213628}. Best is trial 19 with value: 0.6215176535412399.
[I 2026-09-21 16:13:48,895] Trial 20 finished with value: 0.6120086174702756 and parameters: {'n_estimators': 350, 'max_depth': 9, 'learning_rate': 0.01670713536928864, 'min_child_weight': 2, 'subsample': 0.7412596849260826, 'colsample_bytree': 0.8504856694816235, 'gamma': 3.411127738547118, 'reg_alpha': 0.0017627207604156382, 'reg_lambda': 0.03853811339008367}. Best is trial 19 with value: 0.6215176535412399.
[I 2026-09-21 16:13:53,166] Trial 21 finished with value: 0.6132891047845062 and parameters: {'n_estimators': 400, 'max_depth': 9, 'learning_rate': 0.0685933186844566, 'min_child_weight': 3, 'subsample': 0.6879754169902875, 'colsample_bytree': 0.8274445144480465, 'gamma': 4.398566384693804, 'reg_alpha': 0.011477649457800313, 'reg_lambda': 0.16809492188029318}. Best is trial 19 with value: 0.6215176535412399.
[I 2026-09-21 16:13:56,125] Trial 22 finished with value: 0.6025275304349662 and parameters: {'n_estimators': 300, 'max_depth': 10, 'learning_rate': 0.09291492098446653, 'min_child_weight': 4, 'subsample': 0.7706543638293802, 'colsample_bytree': 0.4919728154027331, 'gamma': 4.296766326450984, 'reg_alpha': 0.020104760321125913, 'reg_lambda': 1.647146165292406}. Best is trial 19 with value: 0.6215176535412399.
[I 2026-09-21 16:14:02,021] Trial 23 finished with value: 0.6068989892779223 and parameters: {'n_estimators': 400, 'max_depth': 10, 'learning_rate': 0.02998998701224042, 'min_child_weight': 4, 'subsample': 0.7424063706000154, 'colsample_bytree': 0.8044268298981657, 'gamma': 3.548413923437473, 'reg_alpha': 0.13754840319552786, 'reg_lambda': 0.43024467421610396}. Best is trial 19 with value: 0.6215176535412399.
[I 2026-09-21 16:14:08,391] Trial 24 finished with value: 0.615760862565561 and parameters: {'n_estimators': 400, 'max_depth': 9, 'learning_rate': 0.038690197487989395, 'min_child_weight': 1, 'subsample': 0.7757344150815771, 'colsample_bytree': 0.8397031779297852, 'gamma': 3.360013666445778, 'reg_alpha': 0.05767521674285736, 'reg_lambda': 0.0437573281738429}. Best is trial 19 with value: 0.6215176535412399.
[I 2026-09-21 16:14:14,437] Trial 25 finished with value: 0.614814958102172 and parameters: {'n_estimators': 350, 'max_depth': 9, 'learning_rate': 0.0168902351115292, 'min_child_weight': 3, 'subsample': 0.6663380692077434, 'colsample_bytree': 0.8400519970531709, 'gamma': 4.6518035258365655, 'reg_alpha': 0.004929611278005213, 'reg_lambda': 0.272074844989935}. Best is trial 19 with value: 0.6215176535412399.
[I 2026-09-21 16:14:19,827] Trial 26 finished with value: 0.6139196914017797 and parameters: {'n_estimators': 300, 'max_depth': 8, 'learning_rate': 0.023958073178706088, 'min_child_weight': 3, 'subsample': 0.7158368439148765, 'colsample_bytree': 0.9638035779710422, 'gamma': 2.8052255995952144, 'reg_alpha': 0.025714311746336038, 'reg_lambda': 0.06660792156309508}. Best is trial 19 with value: 0.6215176535412399.
[I 2026-09-21 16:14:23,604] Trial 27 finished with value: 0.6119870551688666 and parameters: {'n_estimators': 300, 'max_depth': 10, 'learning_rate': 0.05877299384701431, 'min_child_weight': 3, 'subsample': 0.8560565035153589, 'colsample_bytree': 0.7682178812637172, 'gamma': 4.2832906590674344, 'reg_alpha': 0.011916506850087674, 'reg_lambda': 0.1381468536673488}. Best is trial 19 with value: 0.6215176535412399.
[I 2026-09-21 16:14:30,433] Trial 28 finished with value: 0.6151087462545421 and parameters: {'n_estimators': 450, 'max_depth': 10, 'learning_rate': 0.03758162840484547, 'min_child_weight': 3, 'subsample': 0.7491559028503991, 'colsample_bytree': 0.7957995378778979, 'gamma': 2.4145517137408903, 'reg_alpha': 0.3234013122307707, 'reg_lambda': 0.1225993438821003}. Best is trial 19 with value: 0.6215176535412399.
[I 2026-09-21 16:14:35,607] Trial 29 finished with value: 0.6161352073107593 and parameters: {'n_estimators': 350, 'max_depth': 8, 'learning_rate': 0.058494422611602294, 'min_child_weight': 2, 'subsample': 0.7760952497308377, 'colsample_bytree': 0.8514466416338196, 'gamma': 2.600731595629025, 'reg_alpha': 0.007377154351513151, 'reg_lambda': 0.06586924451088237}. Best is trial 19 with value: 0.6215176535412399.
[I 2026-09-21 16:14:40,929] Trial 30 finished with value: 0.6087727385307622 and parameters: {'n_estimators': 450, 'max_depth': 8, 'learning_rate': 0.08225400499524585, 'min_child_weight': 2, 'subsample': 0.7588517019612461, 'colsample_bytree': 0.836091952914365, 'gamma': 2.1959930211146164, 'reg_alpha': 0.024935798513373342, 'reg_lambda': 0.044098613481662524}. Best is trial 19 with value: 0.6215176535412399.
[I 2026-09-21 16:14:47,480] Trial 31 finished with value: 0.6178427139174071 and parameters: {'n_estimators': 450, 'max_depth': 9, 'learning_rate': 0.04232195261234245, 'min_child_weight': 2, 'subsample': 0.7695027613264603, 'colsample_bytree': 0.9209908343539265, 'gamma': 2.9225318892024648, 'reg_alpha': 0.08281560607858612, 'reg_lambda': 0.037576538552828546}. Best is trial 19 with value: 0.6215176535412399.
[I 2026-09-21 16:14:51,821] Trial 32 finished with value: 0.5966871471280897 and parameters: {'n_estimators': 300, 'max_depth': 9, 'learning_rate': 0.029439313018001338, 'min_child_weight': 4, 'subsample': 0.6483111752949035, 'colsample_bytree': 0.6887430164848081, 'gamma': 4.610041536731764, 'reg_alpha': 0.06076163074044382, 'reg_lambda': 0.4637110169218008}. Best is trial 19 with value: 0.6215176535412399.
[I 2026-09-21 16:14:56,944] Trial 33 finished with value: 0.6131899635704059 and parameters: {'n_estimators': 350, 'max_depth': 7, 'learning_rate': 0.048837697484799665, 'min_child_weight': 2, 'subsample': 0.8096281872900913, 'colsample_bytree': 0.9406409412324268, 'gamma': 2.6241350850904857, 'reg_alpha': 0.037771163936724854, 'reg_lambda': 0.06607920719902757}. Best is trial 19 with value: 0.6215176535412399.
[I 2026-09-21 16:15:03,861] Trial 34 finished with value: 0.6127165367632544 and parameters: {'n_estimators': 450, 'max_depth': 9, 'learning_rate': 0.02036702955206864, 'min_child_weight': 3, 'subsample': 0.7832498344843961, 'colsample_bytree': 0.8943310805164804, 'gamma': 4.109889249631216, 'reg_alpha': 0.01940241608859526, 'reg_lambda': 0.035541891783679995}. Best is trial 19 with value: 0.6215176535412399.
[I 2026-09-21 16:15:08,463] Trial 35 finished with value: 0.6156814081091841 and parameters: {'n_estimators': 350, 'max_depth': 7, 'learning_rate': 0.0629068186340659, 'min_child_weight': 2, 'subsample': 0.7029583035155789, 'colsample_bytree': 0.8717200833925043, 'gamma': 3.4525362581897565, 'reg_alpha': 0.007931649713081027, 'reg_lambda': 0.029414139527013255}. Best is trial 19 with value: 0.6215176535412399.
[I 2026-09-21 16:15:14,681] Trial 36 finished with value: 0.618798803374317 and parameters: {'n_estimators': 450, 'max_depth': 9, 'learning_rate': 0.047408043786266604, 'min_child_weight': 3, 'subsample': 0.8094909227840439, 'colsample_bytree': 0.9212851068507643, 'gamma': 2.5277652886112336, 'reg_alpha': 0.046887914505970095, 'reg_lambda': 0.015777236807749673}. Best is trial 19 with value: 0.6215176535412399.
[I 2026-09-21 16:15:20,744] Trial 37 finished with value: 0.6106104981779197 and parameters: {'n_estimators': 450, 'max_depth': 8, 'learning_rate': 0.03667800288416616, 'min_child_weight': 2, 'subsample': 0.8823065740132654, 'colsample_bytree': 0.9536246686476284, 'gamma': 3.537010361382988, 'reg_alpha': 0.02009678670441158, 'reg_lambda': 0.015710331071802097}. Best is trial 19 with value: 0.6215176535412399.
[I 2026-09-21 16:15:27,970] Trial 38 finished with value: 0.6164923923943542 and parameters: {'n_estimators': 400, 'max_depth': 10, 'learning_rate': 0.01802847746046895, 'min_child_weight': 3, 'subsample': 0.7999594623039007, 'colsample_bytree': 0.7847295683426267, 'gamma': 3.033537880853776, 'reg_alpha': 0.010027753536085541, 'reg_lambda': 0.1051271071562066}. Best is trial 19 with value: 0.6215176535412399.
[I 2026-09-21 16:15:32,506] Trial 39 finished with value: 0.6090397652167795 and parameters: {'n_estimators': 400, 'max_depth': 10, 'learning_rate': 0.0825655236196349, 'min_child_weight': 3, 'subsample': 0.8086374728296064, 'colsample_bytree': 0.8878939233584512, 'gamma': 3.2438941696012273, 'reg_alpha': 0.03891277170287869, 'reg_lambda': 0.06249912979486232}. Best is trial 19 with value: 0.6215176535412399.
[I 2026-09-21 16:15:37,473] Trial 40 finished with value: 0.6187343063096181 and parameters: {'n_estimators': 300, 'max_depth': 10, 'learning_rate': 0.04943647737851722, 'min_child_weight': 3, 'subsample': 0.7516005944321433, 'colsample_bytree': 0.881754649392085, 'gamma': 3.0250201188954913, 'reg_alpha': 0.0064039898910638205, 'reg_lambda': 0.023647375190423477}. Best is trial 19 with value: 0.6215176535412399.
[I 2026-09-21 16:15:43,115] Trial 41 finished with value: 0.6123309146912219 and parameters: {'n_estimators': 500, 'max_depth': 9, 'learning_rate': 0.05647774060289375, 'min_child_weight': 3, 'subsample': 0.8932261737079666, 'colsample_bytree': 0.8717087000525257, 'gamma': 2.6297322103824845, 'reg_alpha': 0.049273120279175464, 'reg_lambda': 0.017364472943208014}. Best is trial 19 with value: 0.6215176535412399.
[I 2026-09-21 16:15:49,454] Trial 42 finished with value: 0.6085129541292013 and parameters: {'n_estimators': 400, 'max_depth': 9, 'learning_rate': 0.042524789352319625, 'min_child_weight': 3, 'subsample': 0.7358857017211834, 'colsample_bytree': 0.9930197697440667, 'gamma': 2.651232573440285, 'reg_alpha': 0.010633980976663033, 'reg_lambda': 0.024248868652668447}. Best is trial 19 with value: 0.6215176535412399.
[I 2026-09-21 16:15:56,833] Trial 43 finished with value: 0.613118735047645 and parameters: {'n_estimators': 400, 'max_depth': 10, 'learning_rate': 0.026241122948342466, 'min_child_weight': 2, 'subsample': 0.7149210205493106, 'colsample_bytree': 0.9598288959409707, 'gamma': 3.4619352063493194, 'reg_alpha': 0.005125943891137885, 'reg_lambda': 0.013574865005565819}. Best is trial 19 with value: 0.6215176535412399.
[I 2026-09-21 16:16:02,865] Trial 44 finished with value: 0.6235511031225696 and parameters: {'n_estimators': 400, 'max_depth': 10, 'learning_rate': 0.04491374744048731, 'min_child_weight': 2, 'subsample': 0.75566978597302, 'colsample_bytree': 0.9840928543673289, 'gamma': 3.425616639542556, 'reg_alpha': 0.13117500224018816, 'reg_lambda': 0.02769780508602773}. Best is trial 44 with value: 0.6235511031225696.
[I 2026-09-21 16:16:07,130] Trial 45 finished with value: 0.6258329468316003 and parameters: {'n_estimators': 300, 'max_depth': 10, 'learning_rate': 0.06299349502760707, 'min_child_weight': 3, 'subsample': 0.7683638216913562, 'colsample_bytree': 0.8927108853657487, 'gamma': 3.7946171538376783, 'reg_alpha': 0.018155069209867845, 'reg_lambda': 0.021785298629927417}. Best is trial 45 with value: 0.6258329468316003.
[I 2026-09-21 16:16:12,422] Trial 46 finished with value: 0.6228231827820314 and parameters: {'n_estimators': 300, 'max_depth': 10, 'learning_rate': 0.04635300799324709, 'min_child_weight': 1, 'subsample': 0.7566849015607942, 'colsample_bytree': 0.8932758266331092, 'gamma': 2.9664747794760373, 'reg_alpha': 0.6021415034434291, 'reg_lambda': 0.03364082486160869}. Best is trial 45 with value: 0.6258329468316003.
[I 2026-09-21 16:16:17,023] Trial 47 finished with value: 0.6070047745883038 and parameters: {'n_estimators': 250, 'max_depth': 10, 'learning_rate': 0.053055191447013476, 'min_child_weight': 1, 'subsample': 0.7241377332007769, 'colsample_bytree': 0.9272933881457305, 'gamma': 3.162465870717858, 'reg_alpha': 0.6669866893928471, 'reg_lambda': 0.06606352041468179}. Best is trial 45 with value: 0.6258329468316003.

MX | F1-Macro=0.625833
{'n_estimators': 300, 'max_depth': 10, 'learning_rate': 0.06299349502760707, 'min_child_weight': 3, 'subsample': 0.7683638216913562, 'colsample_bytree': 0.8927108853657487, 'gamma': 3.7946171538376783, 'reg_alpha': 0.018155069209867845, 'reg_lambda': 0.021785298629927417}

[I 2026-09-21 16:16:34,696] Trial 0 finished with value: 0.6719321629450314 and parameters: {'n_estimators': 250, 'max_depth': 10, 'learning_rate': 0.1205712628744377, 'min_child_weight': 6, 'subsample': 0.5780093202212182, 'colsample_bytree': 0.49359671220172163, 'gamma': 0.2904180608409973, 'reg_alpha': 1.1752647960576206, 'reg_lambda': 0.6358358856676253}. Best is trial 0 with value: 0.6719321629450314.
[I 2026-09-21 16:16:38,800] Trial 1 finished with value: 0.6531506160589203 and parameters: {'n_estimators': 450, 'max_depth': 2, 'learning_rate': 0.2708160864249968, 'min_child_weight': 9, 'subsample': 0.6061695553391381, 'colsample_bytree': 0.5090949803242604, 'gamma': 0.9170225492671691, 'reg_alpha': 0.0026892128247368906, 'reg_lambda': 0.3752055855124282}. Best is trial 0 with value: 0.6719321629450314.
[I 2026-09-21 16:16:42,721] Trial 2 finished with value: 0.6844135925874208 and parameters: {'n_estimators': 300, 'max_depth': 4, 'learning_rate': 0.08012737503998542, 'min_child_weight': 2, 'subsample': 0.6460723242676091, 'colsample_bytree': 0.619817105976215, 'gamma': 2.28034992108518, 'reg_alpha': 0.48923586931905244, 'reg_lambda': 0.039721107273819126}. Best is trial 2 with value: 0.6844135925874208.
[I 2026-09-21 16:16:48,912] Trial 3 finished with value: 0.6660254134145115 and parameters: {'n_estimators': 350, 'max_depth': 7, 'learning_rate': 0.011711509955524094, 'min_child_weight': 7, 'subsample': 0.5852620618436457, 'colsample_bytree': 0.43903095579116774, 'gamma': 4.7444276862666666, 'reg_alpha': 3.447275228705856, 'reg_lambda': 2.6619018884890564}. Best is trial 2 with value: 0.6844135925874208.
[I 2026-09-21 16:16:51,265] Trial 4 finished with value: 0.6857307303026062 and parameters: {'n_estimators': 200, 'max_depth': 2, 'learning_rate': 0.1024932221692416, 'min_child_weight': 5, 'subsample': 0.5610191174223894, 'colsample_bytree': 0.6971061460667621, 'gamma': 0.17194260557609198, 'reg_alpha': 1.8744302901656154, 'reg_lambda': 0.059750279999602945}. Best is trial 4 with value: 0.6857307303026062.
[I 2026-09-21 16:16:56,481] Trial 5 finished with value: 0.6725350751115299 and parameters: {'n_estimators': 400, 'max_depth': 4, 'learning_rate': 0.05864129169696527, 'min_child_weight': 6, 'subsample': 0.5924272277627636, 'colsample_bytree': 0.9817507766587351, 'gamma': 3.8756641168055728, 'reg_alpha': 2.5982285195767814, 'reg_lambda': 4.83595277646595}. Best is trial 4 with value: 0.6857307303026062.
[I 2026-09-21 16:17:08,143] Trial 6 finished with value: 0.6908644960727646 and parameters: {'n_estimators': 400, 'max_depth': 10, 'learning_rate': 0.01351182947645082, 'min_child_weight': 2, 'subsample': 0.522613644455269, 'colsample_bytree': 0.5951981984579586, 'gamma': 1.9433864484474102, 'reg_alpha': 0.001883913511943895, 'reg_lambda': 3.063462210622083}. Best is trial 6 with value: 0.6908644960727646.
[I 2026-09-21 16:17:11,266] Trial 7 finished with value: 0.6960706135782309 and parameters: {'n_estimators': 250, 'max_depth': 4, 'learning_rate': 0.06333268775321843, 'min_child_weight': 2, 'subsample': 0.9010984903770198, 'colsample_bytree': 0.44473038620786254, 'gamma': 4.9344346830025865, 'reg_alpha': 0.425358393373768, 'reg_lambda': 0.039459088111000004}. Best is trial 7 with value: 0.6960706135782309.
[I 2026-09-21 16:17:13,483] Trial 8 finished with value: 0.6803977262822055 and parameters: {'n_estimators': 50, 'max_depth': 9, 'learning_rate': 0.11069143219393454, 'min_child_weight': 8, 'subsample': 0.8856351733429728, 'colsample_bytree': 0.44442679104045424, 'gamma': 1.7923286427213632, 'reg_alpha': 0.0003503202443763074, 'reg_lambda': 3.8842777547031417}. Best is trial 7 with value: 0.6960706135782309.
[I 2026-09-21 16:17:19,383] Trial 9 finished with value: 0.6759389406633788 and parameters: {'n_estimators': 400, 'max_depth': 4, 'learning_rate': 0.012413189635294229, 'min_child_weight': 4, 'subsample': 0.6625916610133735, 'colsample_bytree': 0.8377637070028385, 'gamma': 3.1877873567760657, 'reg_alpha': 1.475659183168782, 'reg_lambda': 0.26100256506134767}. Best is trial 7 with value: 0.6960706135782309.
[I 2026-09-21 16:17:22,918] Trial 10 finished with value: 0.6823068010815355 and parameters: {'n_estimators': 400, 'max_depth': 2, 'learning_rate': 0.10809366764261572, 'min_child_weight': 4, 'subsample': 0.8220612945327417, 'colsample_bytree': 0.5245713049729106, 'gamma': 4.835916885255543, 'reg_alpha': 0.14265015918349772, 'reg_lambda': 0.10829744586712202}. Best is trial 7 with value: 0.6960706135782309.
[I 2026-09-21 16:17:33,090] Trial 11 finished with value: 0.6863279759698677 and parameters: {'n_estimators': 500, 'max_depth': 7, 'learning_rate': 0.03487908516668871, 'min_child_weight': 1, 'subsample': 0.5048526073975149, 'colsample_bytree': 0.6867026310025903, 'gamma': 2.518069947139868, 'reg_alpha': 0.000239457815284188, 'reg_lambda': 9.22119700635711}. Best is trial 7 with value: 0.6960706135782309.
[I 2026-09-21 16:17:37,429] Trial 12 finished with value: 0.6918529950515858 and parameters: {'n_estimators': 250, 'max_depth': 10, 'learning_rate': 0.06683573849679036, 'min_child_weight': 3, 'subsample': 0.7890278658400848, 'colsample_bytree': 0.5021709338053387, 'gamma': 4.287767884787277, 'reg_alpha': 0.022001831598053367, 'reg_lambda': 0.37203887020388676}. Best is trial 7 with value: 0.6960706135782309.
[I 2026-09-21 16:17:39,979] Trial 13 finished with value: 0.6856093401054009 and parameters: {'n_estimators': 200, 'max_depth': 4, 'learning_rate': 0.0937554525418995, 'min_child_weight': 1, 'subsample': 0.9048532270800027, 'colsample_bytree': 0.42774215403060023, 'gamma': 4.667121425683664, 'reg_alpha': 0.5454554970637162, 'reg_lambda': 0.313853501403984}. Best is trial 7 with value: 0.6960706135782309.
[I 2026-09-21 16:17:43,539] Trial 14 finished with value: 0.6871814267978801 and parameters: {'n_estimators': 250, 'max_depth': 9, 'learning_rate': 0.12278601294837672, 'min_child_weight': 2, 'subsample': 0.9457397455652957, 'colsample_bytree': 0.5772049508932441, 'gamma': 3.9922169672328343, 'reg_alpha': 0.02134004781578425, 'reg_lambda': 0.04231319702149358}. Best is trial 7 with value: 0.6960706135782309.
[I 2026-09-21 16:17:48,568] Trial 15 finished with value: 0.6841793155216186 and parameters: {'n_estimators': 300, 'max_depth': 9, 'learning_rate': 0.04548623953882436, 'min_child_weight': 4, 'subsample': 0.8711645107106444, 'colsample_bytree': 0.44370223705172196, 'gamma': 4.04007108966959, 'reg_alpha': 0.03807524178516362, 'reg_lambda': 0.4144839810167538}. Best is trial 7 with value: 0.6960706135782309.
[I 2026-09-21 16:17:50,667] Trial 16 finished with value: 0.6815135460305864 and parameters: {'n_estimators': 150, 'max_depth': 3, 'learning_rate': 0.04165874834597467, 'min_child_weight': 3, 'subsample': 0.9395396910540766, 'colsample_bytree': 0.531617406939754, 'gamma': 4.286964819959511, 'reg_alpha': 0.02294714325727392, 'reg_lambda': 0.011891997000999462}. Best is trial 7 with value: 0.6960706135782309.
[I 2026-09-21 16:17:54,521] Trial 17 finished with value: 0.6924444679626771 and parameters: {'n_estimators': 200, 'max_depth': 6, 'learning_rate': 0.042942124131726885, 'min_child_weight': 1, 'subsample': 0.7526717486908431, 'colsample_bytree': 0.5773535120330491, 'gamma': 4.559674860846331, 'reg_alpha': 0.5082997350159874, 'reg_lambda': 0.0712948651763065}. Best is trial 7 with value: 0.6960706135782309.
[I 2026-09-21 16:17:57,150] Trial 18 finished with value: 0.6863986080463829 and parameters: {'n_estimators': 150, 'max_depth': 7, 'learning_rate': 0.061622633789472414, 'min_child_weight': 1, 'subsample': 0.890485626678411, 'colsample_bytree': 0.4753051132169086, 'gamma': 4.654948411168692, 'reg_alpha': 3.837332368477087, 'reg_lambda': 0.023477800393015554}. Best is trial 7 with value: 0.6960706135782309.
[I 2026-09-21 16:18:02,234] Trial 19 finished with value: 0.6884338800626186 and parameters: {'n_estimators': 400, 'max_depth': 4, 'learning_rate': 0.03500702768870616, 'min_child_weight': 2, 'subsample': 0.833367422886448, 'colsample_bytree': 0.6813052181941834, 'gamma': 3.6850640582035044, 'reg_alpha': 0.11550816480619719, 'reg_lambda': 0.018028411673980775}. Best is trial 7 with value: 0.6960706135782309.
[I 2026-09-21 16:18:05,100] Trial 20 finished with value: 0.684693300462311 and parameters: {'n_estimators': 200, 'max_depth': 4, 'learning_rate': 0.04914073961229835, 'min_child_weight': 4, 'subsample': 0.9271345989807196, 'colsample_bytree': 0.4709382338440179, 'gamma': 4.216580884896981, 'reg_alpha': 0.7598218575003869, 'reg_lambda': 0.164386908542648}. Best is trial 7 with value: 0.6960706135782309.
[I 2026-09-21 16:18:09,120] Trial 21 finished with value: 0.6924268042852706 and parameters: {'n_estimators': 300, 'max_depth': 5, 'learning_rate': 0.044493262304500424, 'min_child_weight': 2, 'subsample': 0.8379383433330222, 'colsample_bytree': 0.41188547235371326, 'gamma': 4.9683258161549295, 'reg_alpha': 0.029622225194478664, 'reg_lambda': 0.03435980231148084}. Best is trial 7 with value: 0.6960706135782309.
[I 2026-09-21 16:18:11,274] Trial 22 finished with value: 0.6833896222116228 and parameters: {'n_estimators': 150, 'max_depth': 3, 'learning_rate': 0.03277313488256521, 'min_child_weight': 2, 'subsample': 0.8110144763603028, 'colsample_bytree': 0.5056549737147963, 'gamma': 4.913141741968357, 'reg_alpha': 0.019074145719983823, 'reg_lambda': 0.029868433768244933}. Best is trial 7 with value: 0.6960706135782309.
[I 2026-09-21 16:18:16,834] Trial 23 finished with value: 0.6953255128342883 and parameters: {'n_estimators': 400, 'max_depth': 5, 'learning_rate': 0.020659107613160962, 'min_child_weight': 1, 'subsample': 0.8697962649561374, 'colsample_bytree': 0.4171225514565066, 'gamma': 4.889131688699334, 'reg_alpha': 0.0795126219667686, 'reg_lambda': 0.10799258683325404}. Best is trial 7 with value: 0.6960706135782309.
[I 2026-09-21 16:18:23,784] Trial 24 finished with value: 0.692945061442416 and parameters: {'n_estimators': 500, 'max_depth': 6, 'learning_rate': 0.025032623918312333, 'min_child_weight': 2, 'subsample': 0.8032866076994091, 'colsample_bytree': 0.4551592378441585, 'gamma': 4.520104099946793, 'reg_alpha': 0.03375694444250971, 'reg_lambda': 0.4024483384957298}. Best is trial 7 with value: 0.6960706135782309.
[I 2026-09-21 16:18:30,509] Trial 25 finished with value: 0.6894947525474968 and parameters: {'n_estimators': 350, 'max_depth': 7, 'learning_rate': 0.012096954278135008, 'min_child_weight': 3, 'subsample': 0.8887378267400723, 'colsample_bytree': 0.4503853232751711, 'gamma': 4.207227785705281, 'reg_alpha': 0.19819989848579456, 'reg_lambda': 0.043356486868802925}. Best is trial 7 with value: 0.6960706135782309.
[I 2026-09-21 16:18:34,169] Trial 26 finished with value: 0.6843052910910791 and parameters: {'n_estimators': 250, 'max_depth': 5, 'learning_rate': 0.035920223220969404, 'min_child_weight': 3, 'subsample': 0.993088586964616, 'colsample_bytree': 0.48302351396636556, 'gamma': 4.794639565651566, 'reg_alpha': 0.06922670091495893, 'reg_lambda': 0.07539692408162897}. Best is trial 7 with value: 0.6960706135782309.
[I 2026-09-21 16:18:40,416] Trial 27 finished with value: 0.6911263604496174 and parameters: {'n_estimators': 450, 'max_depth': 5, 'learning_rate': 0.019525148781085893, 'min_child_weight': 1, 'subsample': 0.7514611638594597, 'colsample_bytree': 0.4182474533233554, 'gamma': 3.9811460783776, 'reg_alpha': 0.23799759088436703, 'reg_lambda': 0.11303400968825902}. Best is trial 7 with value: 0.6960706135782309.
[I 2026-09-21 16:18:43,757] Trial 28 finished with value: 0.6917680348848734 and parameters: {'n_estimators': 250, 'max_depth': 4, 'learning_rate': 0.030560250270176018, 'min_child_weight': 2, 'subsample': 0.8949016206602234, 'colsample_bytree': 0.43814072843402013, 'gamma': 3.2757455413722614, 'reg_alpha': 0.11580843572293326, 'reg_lambda': 0.04802216480393005}. Best is trial 7 with value: 0.6960706135782309.
[I 2026-09-21 16:18:47,111] Trial 29 finished with value: 0.6875496168699242 and parameters: {'n_estimators': 300, 'max_depth': 5, 'learning_rate': 0.09747461415069894, 'min_child_weight': 2, 'subsample': 0.87922918983314, 'colsample_bytree': 0.5619033216459206, 'gamma': 4.811354672247127, 'reg_alpha': 0.8582123431057964, 'reg_lambda': 0.058531752567955356}. Best is trial 7 with value: 0.6960706135782309.
[I 2026-09-21 16:18:51,251] Trial 30 finished with value: 0.6884303450905654 and parameters: {'n_estimators': 300, 'max_depth': 4, 'learning_rate': 0.01587843046753512, 'min_child_weight': 2, 'subsample': 0.9854559086057743, 'colsample_bytree': 0.4671518434390765, 'gamma': 4.746115366412723, 'reg_alpha': 0.33889774144616697, 'reg_lambda': 0.18423952261915258}. Best is trial 7 with value: 0.6960706135782309.
[I 2026-09-21 16:18:52,958] Trial 31 finished with value: 0.6821000051197685 and parameters: {'n_estimators': 100, 'max_depth': 3, 'learning_rate': 0.07405900706884867, 'min_child_weight': 1, 'subsample': 0.849786525127309, 'colsample_bytree': 0.4413429452524596, 'gamma': 4.5139302800504515, 'reg_alpha': 0.3145894537153932, 'reg_lambda': 0.05795874103471144}. Best is trial 7 with value: 0.6960706135782309.
[I 2026-09-21 16:18:55,239] Trial 32 finished with value: 0.6892971631682985 and parameters: {'n_estimators': 150, 'max_depth': 4, 'learning_rate': 0.09802584069552496, 'min_child_weight': 2, 'subsample': 0.9394772551715488, 'colsample_bytree': 0.5019769752614492, 'gamma': 4.653872622873809, 'reg_alpha': 0.19125098877837848, 'reg_lambda': 0.026054025200356174}. Best is trial 7 with value: 0.6960706135782309.
[I 2026-09-21 16:18:58,950] Trial 33 finished with value: 0.6959093203888745 and parameters: {'n_estimators': 350, 'max_depth': 6, 'learning_rate': 0.08264094193227965, 'min_child_weight': 2, 'subsample': 0.9016199570008255, 'colsample_bytree': 0.42417853797552524, 'gamma': 4.59847992700711, 'reg_alpha': 0.5160979464405814, 'reg_lambda': 0.028172762268268526}. Best is trial 7 with value: 0.6960706135782309.
[I 2026-09-21 16:19:03,728] Trial 34 finished with value: 0.6885036800055329 and parameters: {'n_estimators': 400, 'max_depth': 4, 'learning_rate': 0.030972976020465403, 'min_child_weight': 1, 'subsample': 0.8718830048217991, 'colsample_bytree': 0.42339761654003766, 'gamma': 4.688060616122675, 'reg_alpha': 0.6055736041185655, 'reg_lambda': 0.022952219941648394}. Best is trial 7 with value: 0.6960706135782309.
[I 2026-09-21 16:19:07,773] Trial 35 finished with value: 0.689825516323222 and parameters: {'n_estimators': 250, 'max_depth': 6, 'learning_rate': 0.04483224134887838, 'min_child_weight': 2, 'subsample': 0.8629553548909329, 'colsample_bytree': 0.461564970330906, 'gamma': 4.403311649436917, 'reg_alpha': 0.3916587482234731, 'reg_lambda': 0.013793825783215937}. Best is trial 7 with value: 0.6960706135782309.
[I 2026-09-21 16:19:11,744] Trial 36 finished with value: 0.6946671203845568 and parameters: {'n_estimators': 400, 'max_depth': 6, 'learning_rate': 0.0969691998183091, 'min_child_weight': 2, 'subsample': 0.9489556088357891, 'colsample_bytree': 0.4099824177887054, 'gamma': 4.009599221243657, 'reg_alpha': 0.2519793380814077, 'reg_lambda': 0.021265818556116915}. Best is trial 7 with value: 0.6960706135782309.
[I 2026-09-21 16:19:15,881] Trial 37 finished with value: 0.6945184744463478 and parameters: {'n_estimators': 400, 'max_depth': 6, 'learning_rate': 0.07392074237910433, 'min_child_weight': 2, 'subsample': 0.969429484816096, 'colsample_bytree': 0.5334653428299522, 'gamma': 4.664576914848539, 'reg_alpha': 0.10040506449805889, 'reg_lambda': 0.017336505783856468}. Best is trial 7 with value: 0.6960706135782309.
[I 2026-09-21 16:19:19,552] Trial 38 finished with value: 0.6971452015224118 and parameters: {'n_estimators': 300, 'max_depth': 4, 'learning_rate': 0.07386282215033478, 'min_child_weight': 2, 'subsample': 0.8842509554947436, 'colsample_bytree': 0.44316645389505754, 'gamma': 3.944882141890936, 'reg_alpha': 0.7308218161211187, 'reg_lambda': 0.053955346798936175}. Best is trial 38 with value: 0.6971452015224118.
[I 2026-09-21 16:19:23,945] Trial 39 finished with value: 0.6905597186899675 and parameters: {'n_estimators': 350, 'max_depth': 7, 'learning_rate': 0.08013016619304275, 'min_child_weight': 1, 'subsample': 0.9394496497804667, 'colsample_bytree': 0.45706580847492245, 'gamma': 3.5505415205469326, 'reg_alpha': 0.6580271645257129, 'reg_lambda': 0.07298105616440696}. Best is trial 38 with value: 0.6971452015224118.
[I 2026-09-21 16:19:26,661] Trial 40 finished with value: 0.6850159518118211 and parameters: {'n_estimators': 250, 'max_depth': 5, 'learning_rate': 0.16865677380531838, 'min_child_weight': 3, 'subsample': 0.9287757717778331, 'colsample_bytree': 0.41974073648372734, 'gamma': 4.904850419718129, 'reg_alpha': 0.6090151357771738, 'reg_lambda': 0.013214014473346712}. Best is trial 38 with value: 0.6971452015224118.
[I 2026-09-21 16:19:30,789] Trial 41 finished with value: 0.6862789839371999 and parameters: {'n_estimators': 450, 'max_depth': 7, 'learning_rate': 0.11453169531244728, 'min_child_weight': 3, 'subsample': 0.9810167336852512, 'colsample_bytree': 0.4409425051767722, 'gamma': 4.028796192905603, 'reg_alpha': 0.2517537194233216, 'reg_lambda': 0.019783462272734777}. Best is trial 38 with value: 0.6971452015224118.
[I 2026-09-21 16:19:35,668] Trial 42 finished with value: 0.6956457857001076 and parameters: {'n_estimators': 350, 'max_depth': 6, 'learning_rate': 0.04464723170159427, 'min_child_weight': 1, 'subsample': 0.9002292724159514, 'colsample_bytree': 0.4760595208772, 'gamma': 4.285027500735427, 'reg_alpha': 0.22334262269877356, 'reg_lambda': 0.022910932053943355}. Best is trial 38 with value: 0.6971452015224118.
[I 2026-09-21 16:19:39,646] Trial 43 finished with value: 0.6925587621122462 and parameters: {'n_estimators': 350, 'max_depth': 5, 'learning_rate': 0.050823319401992605, 'min_child_weight': 2, 'subsample': 0.8595466414805074, 'colsample_bytree': 0.4051570220457347, 'gamma': 4.496624422387349, 'reg_alpha': 1.5603564173348234, 'reg_lambda': 0.04213274662342107}. Best is trial 38 with value: 0.6971452015224118.
[I 2026-09-21 16:19:43,294] Trial 44 finished with value: 0.696975485981093 and parameters: {'n_estimators': 350, 'max_depth': 4, 'learning_rate': 0.07368669741797794, 'min_child_weight': 2, 'subsample': 0.8853101962507134, 'colsample_bytree': 0.4402638987731744, 'gamma': 4.521877514237644, 'reg_alpha': 0.6570723368081096, 'reg_lambda': 0.08039450047382186}. Best is trial 38 with value: 0.6971452015224118.
[I 2026-09-21 16:19:46,602] Trial 45 finished with value: 0.6871900862407896 and parameters: {'n_estimators': 350, 'max_depth': 3, 'learning_rate': 0.0766977993673413, 'min_child_weight': 2, 'subsample': 0.8940674940817023, 'colsample_bytree': 0.4318047465015177, 'gamma': 4.947055708543486, 'reg_alpha': 1.6840332796036837, 'reg_lambda': 0.04578570391508358}. Best is trial 38 with value: 0.6971452015224118.
[I 2026-09-21 16:19:50,476] Trial 46 finished with value: 0.6996178330103717 and parameters: {'n_estimators': 350, 'max_depth': 4, 'learning_rate': 0.056711980076742594, 'min_child_weight': 2, 'subsample': 0.8803247637584026, 'colsample_bytree': 0.40811016128299665, 'gamma': 4.295929034861811, 'reg_alpha': 0.5937939906306184, 'reg_lambda': 0.019432777107298887}. Best is trial 46 with value: 0.6996178330103717.
[I 2026-09-21 16:19:54,240] Trial 47 finished with value: 0.694242074945836 and parameters: {'n_estimators': 300, 'max_depth': 5, 'learning_rate': 0.06487987703879515, 'min_child_weight': 2, 'subsample': 0.8447237438745211, 'colsample_bytree': 0.49920403606335984, 'gamma': 4.3149631017328485, 'reg_alpha': 0.6598045226335791, 'reg_lambda': 0.0433739131226741}. Best is trial 46 with value: 0.6996178330103717.

ES | F1-Macro=0.699641
{'n_estimators': 250, 'max_depth': 4, 'learning_rate': 0.06147854456275125, 'min_child_weight': 2, 'subsample': 0.8689001939048056, 'colsample_bytree': 0.40158494903420716, 'gamma': 4.927235313372161, 'reg_alpha': 0.10115112375831407, 'reg_lambda': 0.03316725102868027}

[I 2026-09-21 16:20:09,399] Trial 0 finished with value: 0.6051133749683603 and parameters: {'n_estimators': 250, 'max_depth': 10, 'learning_rate': 0.1205712628744377, 'min_child_weight': 6, 'subsample': 0.5780093202212182, 'colsample_bytree': 0.49359671220172163, 'gamma': 0.2904180608409973, 'reg_alpha': 1.1752647960576206, 'reg_lambda': 0.6358358856676253}. Best is trial 0 with value: 0.6051133749683603.
[I 2026-09-21 16:20:13,631] Trial 1 finished with value: 0.6013256765181734 and parameters: {'n_estimators': 450, 'max_depth': 2, 'learning_rate': 0.2708160864249968, 'min_child_weight': 9, 'subsample': 0.6061695553391381, 'colsample_bytree': 0.5090949803242604, 'gamma': 0.9170225492671691, 'reg_alpha': 0.0026892128247368906, 'reg_lambda': 0.3752055855124282}. Best is trial 0 with value: 0.6051133749683603.
[I 2026-09-21 16:20:17,810] Trial 2 finished with value: 0.641149408607129 and parameters: {'n_estimators': 300, 'max_depth': 4, 'learning_rate': 0.08012737503998542, 'min_child_weight': 2, 'subsample': 0.6460723242676091, 'colsample_bytree': 0.619817105976215, 'gamma': 2.28034992108518, 'reg_alpha': 0.48923586931905244, 'reg_lambda': 0.039721107273819126}. Best is trial 2 with value: 0.641149408607129.
[I 2026-09-21 16:20:23,599] Trial 3 finished with value: 0.6380630930782454 and parameters: {'n_estimators': 350, 'max_depth': 7, 'learning_rate': 0.011711509955524094, 'min_child_weight': 7, 'subsample': 0.5852620618436457, 'colsample_bytree': 0.43903095579116774, 'gamma': 4.7444276862666666, 'reg_alpha': 3.447275228705856, 'reg_lambda': 2.6619018884890564}. Best is trial 2 with value: 0.641149408607129.
[I 2026-09-21 16:20:26,116] Trial 4 finished with value: 0.6293766225019353 and parameters: {'n_estimators': 200, 'max_depth': 2, 'learning_rate': 0.1024932221692416, 'min_child_weight': 5, 'subsample': 0.5610191174223894, 'colsample_bytree': 0.6971061460667621, 'gamma': 0.17194260557609198, 'reg_alpha': 1.8744302901656154, 'reg_lambda': 0.059750279999602945}. Best is trial 2 with value: 0.641149408607129.
[I 2026-09-21 16:20:31,837] Trial 5 finished with value: 0.6289141138473674 and parameters: {'n_estimators': 400, 'max_depth': 4, 'learning_rate': 0.05864129169696527, 'min_child_weight': 6, 'subsample': 0.5924272277627636, 'colsample_bytree': 0.9817507766587351, 'gamma': 3.8756641168055728, 'reg_alpha': 2.5982285195767814, 'reg_lambda': 4.83595277646595}. Best is trial 2 with value: 0.641149408607129.
[I 2026-09-21 16:20:44,523] Trial 6 finished with value: 0.6396999868004523 and parameters: {'n_estimators': 400, 'max_depth': 10, 'learning_rate': 0.01351182947645082, 'min_child_weight': 2, 'subsample': 0.522613644455269, 'colsample_bytree': 0.5951981984579586, 'gamma': 1.9433864484474102, 'reg_alpha': 0.001883913511943895, 'reg_lambda': 3.063462210622083}. Best is trial 2 with value: 0.641149408607129.
[I 2026-09-21 16:20:47,830] Trial 7 finished with value: 0.6570159032752049 and parameters: {'n_estimators': 250, 'max_depth': 4, 'learning_rate': 0.06333268775321843, 'min_child_weight': 2, 'subsample': 0.9010984903770198, 'colsample_bytree': 0.44473038620786254, 'gamma': 4.9344346830025865, 'reg_alpha': 0.425358393373768, 'reg_lambda': 0.039459088111000004}. Best is trial 7 with value: 0.6570159032752049.
[I 2026-09-21 16:20:50,205] Trial 8 finished with value: 0.6284930869322588 and parameters: {'n_estimators': 50, 'max_depth': 9, 'learning_rate': 0.11069143219393454, 'min_child_weight': 8, 'subsample': 0.8856351733429728, 'colsample_bytree': 0.44442679104045424, 'gamma': 1.7923286427213632, 'reg_alpha': 0.0003503202443763074, 'reg_lambda': 3.8842777547031417}. Best is trial 7 with value: 0.6570159032752049.
[I 2026-09-21 16:20:56,428] Trial 9 finished with value: 0.6444450164935348 and parameters: {'n_estimators': 400, 'max_depth': 4, 'learning_rate': 0.012413189635294229, 'min_child_weight': 4, 'subsample': 0.6625916610133735, 'colsample_bytree': 0.8377637070028385, 'gamma': 3.1877873567760657, 'reg_alpha': 1.475659183168782, 'reg_lambda': 0.26100256506134767}. Best is trial 7 with value: 0.6570159032752049.
[I 2026-09-21 16:21:00,079] Trial 10 finished with value: 0.6334410726300617 and parameters: {'n_estimators': 400, 'max_depth': 2, 'learning_rate': 0.10809366764261572, 'min_child_weight': 4, 'subsample': 0.8220612945327417, 'colsample_bytree': 0.5245713049729106, 'gamma': 4.835916885255543, 'reg_alpha': 0.14265015918349772, 'reg_lambda': 0.10829744586712202}. Best is trial 7 with value: 0.6570159032752049.
[I 2026-09-21 16:21:03,674] Trial 11 finished with value: 0.6393122285990441 and parameters: {'n_estimators': 300, 'max_depth': 2, 'learning_rate': 0.01031740940634193, 'min_child_weight': 2, 'subsample': 0.5357517500434517, 'colsample_bytree': 0.7761210237323287, 'gamma': 4.019743140783603, 'reg_alpha': 0.21213093107223746, 'reg_lambda': 0.19352401114887052}. Best is trial 7 with value: 0.6570159032752049.
[I 2026-09-21 16:21:06,091] Trial 12 finished with value: 0.6497988316320082 and parameters: {'n_estimators': 150, 'max_depth': 3, 'learning_rate': 0.07534645639645056, 'min_child_weight': 1, 'subsample': 0.8802027266135349, 'colsample_bytree': 0.824079383944654, 'gamma': 4.083642415876732, 'reg_alpha': 4.473966665610072, 'reg_lambda': 0.08575922829380093}. Best is trial 7 with value: 0.6570159032752049.
[I 2026-09-21 16:21:08,957] Trial 13 finished with value: 0.6502124295401807 and parameters: {'n_estimators': 200, 'max_depth': 4, 'learning_rate': 0.0937554525418995, 'min_child_weight': 1, 'subsample': 0.9048532270800027, 'colsample_bytree': 0.45293690030023254, 'gamma': 4.667121425683664, 'reg_alpha': 0.5870313294211307, 'reg_lambda': 0.18380864336479333}. Best is trial 7 with value: 0.6570159032752049.
[I 2026-09-21 16:21:12,219] Trial 14 finished with value: 0.6568051422725126 and parameters: {'n_estimators': 250, 'max_depth': 6, 'learning_rate': 0.15541087276205268, 'min_child_weight': 1, 'subsample': 0.9807020474226158, 'colsample_bytree': 0.548755494250854, 'gamma': 4.163955268794648, 'reg_alpha': 0.27464054144411915, 'reg_lambda': 0.03478623149979069}. Best is trial 7 with value: 0.6570159032752049.
[I 2026-09-21 16:21:15,627] Trial 15 finished with value: 0.6449969609973826 and parameters: {'n_estimators': 250, 'max_depth': 5, 'learning_rate': 0.0795139171391898, 'min_child_weight': 4, 'subsample': 0.9955651967817174, 'colsample_bytree': 0.45010267717674335, 'gamma': 3.3639524494892266, 'reg_alpha': 0.16747208505007874, 'reg_lambda': 0.01978193203877408}. Best is trial 7 with value: 0.6570159032752049.
[I 2026-09-21 16:21:20,403] Trial 16 finished with value: 0.6523080779497905 and parameters: {'n_estimators': 300, 'max_depth': 6, 'learning_rate': 0.04373594475822771, 'min_child_weight': 1, 'subsample': 0.987721290535632, 'colsample_bytree': 0.6362372468913723, 'gamma': 4.632152225337767, 'reg_alpha': 0.6623658361939269, 'reg_lambda': 0.09127815582979859}. Best is trial 7 with value: 0.6570159032752049.
[I 2026-09-21 16:21:22,224] Trial 17 finished with value: 0.6534966625427301 and parameters: {'n_estimators': 100, 'max_depth': 3, 'learning_rate': 0.05320296623711675, 'min_child_weight': 1, 'subsample': 0.8679680048604289, 'colsample_bytree': 0.4273191887879826, 'gamma': 4.543306498110172, 'reg_alpha': 0.881521987825526, 'reg_lambda': 0.018518215831731185}. Best is trial 7 with value: 0.6570159032752049.
[I 2026-09-21 16:21:24,439] Trial 18 finished with value: 0.6506691501673154 and parameters: {'n_estimators': 150, 'max_depth': 7, 'learning_rate': 0.15717208208515995, 'min_child_weight': 1, 'subsample': 0.974979640738526, 'colsample_bytree': 0.4632111538597608, 'gamma': 4.553523269179031, 'reg_alpha': 3.5469633108968255, 'reg_lambda': 0.018002185975228808}. Best is trial 7 with value: 0.6570159032752049.
[I 2026-09-21 16:21:28,252] Trial 19 finished with value: 0.6411127416229757 and parameters: {'n_estimators': 400, 'max_depth': 5, 'learning_rate': 0.15745446945630148, 'min_child_weight': 3, 'subsample': 0.9034760394117363, 'colsample_bytree': 0.4657002164909924, 'gamma': 4.575995111562802, 'reg_alpha': 0.4912718943451162, 'reg_lambda': 0.12132460978700095}. Best is trial 7 with value: 0.6570159032752049.
[I 2026-09-21 16:21:32,314] Trial 20 finished with value: 0.6516726198031455 and parameters: {'n_estimators': 200, 'max_depth': 6, 'learning_rate': 0.04839544035620927, 'min_child_weight': 1, 'subsample': 0.8938383058090832, 'colsample_bytree': 0.6130676097822209, 'gamma': 3.95775358744893, 'reg_alpha': 0.026935425016604606, 'reg_lambda': 0.028301473455770748}. Best is trial 7 with value: 0.6570159032752049.
[I 2026-09-21 16:21:34,933] Trial 21 finished with value: 0.6586711369710789 and parameters: {'n_estimators': 150, 'max_depth': 4, 'learning_rate': 0.04687994146232383, 'min_child_weight': 1, 'subsample': 0.7168176996823928, 'colsample_bytree': 0.4583657236073577, 'gamma': 4.137389716154434, 'reg_alpha': 0.856557611071255, 'reg_lambda': 0.02808624383382428}. Best is trial 21 with value: 0.6586711369710789.
[I 2026-09-21 16:21:36,744] Trial 22 finished with value: 0.6562690002535222 and parameters: {'n_estimators': 100, 'max_depth': 3, 'learning_rate': 0.10199995966180417, 'min_child_weight': 3, 'subsample': 0.8800092053370638, 'colsample_bytree': 0.4837280962975091, 'gamma': 3.923532966645369, 'reg_alpha': 0.4812563800489144, 'reg_lambda': 0.03986586373727575}. Best is trial 21 with value: 0.6586711369710789.
[I 2026-09-21 16:21:40,969] Trial 23 finished with value: 0.6612565375164586 and parameters: {'n_estimators': 250, 'max_depth': 5, 'learning_rate': 0.021604493563766623, 'min_child_weight': 1, 'subsample': 0.792450101554529, 'colsample_bytree': 0.42350563481355175, 'gamma': 4.769535765108599, 'reg_alpha': 0.9573251029495646, 'reg_lambda': 0.09294759352138826}. Best is trial 23 with value: 0.6612565375164586.
[I 2026-09-21 16:21:46,713] Trial 24 finished with value: 0.6562218562980362 and parameters: {'n_estimators': 350, 'max_depth': 6, 'learning_rate': 0.026452469732932932, 'min_child_weight': 2, 'subsample': 0.7420647378902231, 'colsample_bytree': 0.4571037357098693, 'gamma': 4.481878196141494, 'reg_alpha': 0.26478521557488055, 'reg_lambda': 0.35029735234589476}. Best is trial 23 with value: 0.6612565375164586.
[I 2026-09-21 16:21:50,826] Trial 25 finished with value: 0.6603329323451861 and parameters: {'n_estimators': 250, 'max_depth': 5, 'learning_rate': 0.03347702586357802, 'min_child_weight': 2, 'subsample': 0.840107503219496, 'colsample_bytree': 0.5777369840522129, 'gamma': 4.771810613786977, 'reg_alpha': 0.13689882614509, 'reg_lambda': 0.05746165244044229}. Best is trial 23 with value: 0.6612565375164586.
[I 2026-09-21 16:21:53,776] Trial 26 finished with value: 0.6633970727792368 and parameters: {'n_estimators': 150, 'max_depth': 5, 'learning_rate': 0.031126416937259028, 'min_child_weight': 2, 'subsample': 0.9167251798729862, 'colsample_bytree': 0.4891339473204862, 'gamma': 4.606920579219219, 'reg_alpha': 0.12041478572319597, 'reg_lambda': 0.05934858331388643}. Best is trial 26 with value: 0.6633970727792368.
[I 2026-09-21 16:21:58,791] Trial 27 finished with value: 0.6547325196602374 and parameters: {'n_estimators': 300, 'max_depth': 5, 'learning_rate': 0.01828354904176157, 'min_child_weight': 1, 'subsample': 0.6766821993730365, 'colsample_bytree': 0.4513690415834608, 'gamma': 4.877269443688536, 'reg_alpha': 1.0269328781352987, 'reg_lambda': 0.06099966172047269}. Best is trial 26 with value: 0.6633970727792368.
[I 2026-09-21 16:22:02,016] Trial 28 finished with value: 0.6559401399169379 and parameters: {'n_estimators': 250, 'max_depth': 3, 'learning_rate': 0.01952103809884159, 'min_child_weight': 2, 'subsample': 0.8276724960484996, 'colsample_bytree': 0.5129120319071184, 'gamma': 4.242070411567644, 'reg_alpha': 0.36048917621511267, 'reg_lambda': 0.14083604502477118}. Best is trial 26 with value: 0.6633970727792368.
[I 2026-09-21 16:22:06,188] Trial 29 finished with value: 0.64617724211233 and parameters: {'n_estimators': 150, 'max_depth': 7, 'learning_rate': 0.01639156133212098, 'min_child_weight': 2, 'subsample': 0.9755995547980927, 'colsample_bytree': 0.5613650370615786, 'gamma': 4.75945728197761, 'reg_alpha': 0.2027071638917565, 'reg_lambda': 0.031432456069674576}. Best is trial 26 with value: 0.6633970727792368.
[I 2026-09-21 16:22:08,934] Trial 30 finished with value: 0.654293278280125 and parameters: {'n_estimators': 150, 'max_depth': 4, 'learning_rate': 0.02203719733691044, 'min_child_weight': 2, 'subsample': 0.9783424986459035, 'colsample_bytree': 0.5578670482560154, 'gamma': 4.723390414589085, 'reg_alpha': 0.5249962516800211, 'reg_lambda': 0.10663689364468641}. Best is trial 26 with value: 0.6633970727792368.
[I 2026-09-21 16:22:10,324] Trial 31 finished with value: 0.6461883578965868 and parameters: {'n_estimators': 50, 'max_depth': 3, 'learning_rate': 0.055027566155089365, 'min_child_weight': 1, 'subsample': 0.6750291070357745, 'colsample_bytree': 0.44583735014762504, 'gamma': 4.1181620170173066, 'reg_alpha': 0.5247045899018861, 'reg_lambda': 0.04506204905069112}. Best is trial 26 with value: 0.6633970727792368.
[I 2026-09-21 16:22:12,369] Trial 32 finished with value: 0.6505793862948493 and parameters: {'n_estimators': 100, 'max_depth': 4, 'learning_rate': 0.07291447895538204, 'min_child_weight': 1, 'subsample': 0.7779995099716155, 'colsample_bytree': 0.5097829981235088, 'gamma': 4.32435839631928, 'reg_alpha': 0.3261661297805735, 'reg_lambda': 0.02153361325407166}. Best is trial 26 with value: 0.6633970727792368.
[I 2026-09-21 16:22:17,028] Trial 33 finished with value: 0.6653406989347185 and parameters: {'n_estimators': 200, 'max_depth': 7, 'learning_rate': 0.018041455877536097, 'min_child_weight': 2, 'subsample': 0.8331663580354526, 'colsample_bytree': 0.4970565102038133, 'gamma': 4.976934981139605, 'reg_alpha': 0.43874101810124466, 'reg_lambda': 0.07770219339788582}. Best is trial 33 with value: 0.6653406989347185.
[I 2026-09-21 16:22:22,357] Trial 34 finished with value: 0.6615464903308992 and parameters: {'n_estimators': 200, 'max_depth': 8, 'learning_rate': 0.0118363005812367, 'min_child_weight': 3, 'subsample': 0.8444887296389922, 'colsample_bytree': 0.5186137903960012, 'gamma': 4.923916937632399, 'reg_alpha': 0.10756625191516483, 'reg_lambda': 0.06318086989447927}. Best is trial 33 with value: 0.6653406989347185.
[I 2026-09-21 16:22:25,869] Trial 35 finished with value: 0.6492891103565385 and parameters: {'n_estimators': 150, 'max_depth': 6, 'learning_rate': 0.0181825059231145, 'min_child_weight': 3, 'subsample': 0.805544693685309, 'colsample_bytree': 0.5027000465939925, 'gamma': 4.41121600468575, 'reg_alpha': 1.2430848506180128, 'reg_lambda': 0.08122801066777519}. Best is trial 33 with value: 0.6653406989347185.
[I 2026-09-21 16:22:28,215] Trial 36 finished with value: 0.6599945990140234 and parameters: {'n_estimators': 100, 'max_depth': 5, 'learning_rate': 0.02416519371386661, 'min_child_weight': 2, 'subsample': 0.7953631635150532, 'colsample_bytree': 0.431062709736787, 'gamma': 4.380415486072087, 'reg_alpha': 0.23798024756647237, 'reg_lambda': 0.079352342270349}. Best is trial 33 with value: 0.6653406989347185.
[I 2026-09-21 16:22:33,644] Trial 37 finished with value: 0.6635402314122694 and parameters: {'n_estimators': 250, 'max_depth': 7, 'learning_rate': 0.019309418233623355, 'min_child_weight': 2, 'subsample': 0.8066532188650364, 'colsample_bytree': 0.5599205285832582, 'gamma': 4.903792482168913, 'reg_alpha': 0.3051294122873123, 'reg_lambda': 0.141928544807223}. Best is trial 33 with value: 0.6653406989347185.
[I 2026-09-21 16:22:40,177] Trial 38 finished with value: 0.66142836030451 and parameters: {'n_estimators': 200, 'max_depth': 10, 'learning_rate': 0.01192084896808071, 'min_child_weight': 2, 'subsample': 0.8670340699720335, 'colsample_bytree': 0.47317123287823765, 'gamma': 4.332486663404268, 'reg_alpha': 0.34686719052469167, 'reg_lambda': 0.11377103560919001}. Best is trial 33 with value: 0.6653406989347185.
[I 2026-09-21 16:22:45,315] Trial 39 finished with value: 0.6642529330296927 and parameters: {'n_estimators': 250, 'max_depth': 7, 'learning_rate': 0.02047333571193025, 'min_child_weight': 3, 'subsample': 0.8533906865538476, 'colsample_bytree': 0.49911349971947316, 'gamma': 4.954628184683867, 'reg_alpha': 0.38848537545909156, 'reg_lambda': 0.22787816861343943}. Best is trial 33 with value: 0.6653406989347185.
[I 2026-09-21 16:22:48,488] Trial 40 finished with value: 0.6538016275402458 and parameters: {'n_estimators': 150, 'max_depth': 5, 'learning_rate': 0.01851238318620114, 'min_child_weight': 3, 'subsample': 0.8565711563858971, 'colsample_bytree': 0.5505122710395915, 'gamma': 3.9593155678652696, 'reg_alpha': 0.22683470449603635, 'reg_lambda': 0.062266953750290954}. Best is trial 33 with value: 0.6653406989347185.
[I 2026-09-21 16:22:54,825] Trial 41 finished with value: 0.6566660673774352 and parameters: {'n_estimators': 250, 'max_depth': 8, 'learning_rate': 0.010596515254011814, 'min_child_weight': 3, 'subsample': 0.8469960684391693, 'colsample_bytree': 0.5366243293599734, 'gamma': 4.593003152509272, 'reg_alpha': 0.1510579054862532, 'reg_lambda': 0.09144653853030978}. Best is trial 33 with value: 0.6653406989347185.
[I 2026-09-21 16:23:00,498] Trial 42 finished with value: 0.6534385628025428 and parameters: {'n_estimators': 200, 'max_depth': 8, 'learning_rate': 0.01086084878512165, 'min_child_weight': 2, 'subsample': 0.8497887398320725, 'colsample_bytree': 0.5383742127779231, 'gamma': 4.445167796554862, 'reg_alpha': 0.0509352055887731, 'reg_lambda': 0.041795320932041635}. Best is trial 33 with value: 0.6653406989347185.
[I 2026-09-21 16:23:05,839] Trial 43 finished with value: 0.6518102925456039 and parameters: {'n_estimators': 250, 'max_depth': 7, 'learning_rate': 0.01692252256671983, 'min_child_weight': 4, 'subsample': 0.882257945677307, 'colsample_bytree': 0.5474512344913366, 'gamma': 4.797380019922233, 'reg_alpha': 0.2873104647242766, 'reg_lambda': 0.41523183458633406}. Best is trial 33 with value: 0.6653406989347185.
[I 2026-09-21 16:23:10,348] Trial 44 finished with value: 0.6575745163162251 and parameters: {'n_estimators': 200, 'max_depth': 7, 'learning_rate': 0.019331984305459175, 'min_child_weight': 4, 'subsample': 0.8212878948076353, 'colsample_bytree': 0.4776777442927805, 'gamma': 4.74630016334147, 'reg_alpha': 1.0832207212534355, 'reg_lambda': 0.2031974344766466}. Best is trial 33 with value: 0.6653406989347185.
[I 2026-09-21 16:23:14,584] Trial 45 finished with value: 0.6529883476052177 and parameters: {'n_estimators': 200, 'max_depth': 7, 'learning_rate': 0.019629861624561977, 'min_child_weight': 4, 'subsample': 0.8772255320739394, 'colsample_bytree': 0.4104537844663281, 'gamma': 4.904180486628167, 'reg_alpha': 0.32601118089159403, 'reg_lambda': 0.052596365979060145}. Best is trial 33 with value: 0.6653406989347185.
[I 2026-09-21 16:23:19,009] Trial 46 finished with value: 0.6549093630763195 and parameters: {'n_estimators': 200, 'max_depth': 6, 'learning_rate': 0.01357904694254844, 'min_child_weight': 2, 'subsample': 0.8547698987747827, 'colsample_bytree': 0.492795357261277, 'gamma': 4.571803528878143, 'reg_alpha': 0.05686900296726638, 'reg_lambda': 0.20155414718027798}. Best is trial 33 with value: 0.6653406989347185.
[I 2026-09-21 16:23:23,656] Trial 47 finished with value: 0.6535408828978567 and parameters: {'n_estimators': 200, 'max_depth': 7, 'learning_rate': 0.01163855464059026, 'min_child_weight': 3, 'subsample': 0.79938446145663, 'colsample_bytree': 0.43216958870076605, 'gamma': 4.86483167863923, 'reg_alpha': 0.2492917045879387, 'reg_lambda': 0.18868833385492134}. Best is trial 33 with value: 0.6653406989347185.

CU | F1-Macro=0.665341
{'n_estimators': 200, 'max_depth': 7, 'learning_rate': 0.018041455877536097, 'min_child_weight': 2, 'subsample': 0.8331663580354526, 'colsample_bytree': 0.4970565102038133, 'gamma': 4.976934981139605, 'reg_alpha': 0.43874101810124466, 'reg_lambda': 0.07770219339788582}

In [33]:
comparacion_final = pd.DataFrame([
    {
        "variante": "mx",
        "optuna_v1": study_mx.best_value,
        "optuna_final": study_mx_final.best_value,
        "diferencia": (
            study_mx_final.best_value
            - study_mx.best_value
        )
    },
    {
        "variante": "es",
        "optuna_v1": study_es.best_value,
        "optuna_final": study_es_final.best_value,
        "diferencia": (
            study_es_final.best_value
            - study_es.best_value
        )
    },
    {
        "variante": "cu",
        "optuna_v1": study_cu.best_value,
        "optuna_final": study_cu_final.best_value,
        "diferencia": (
            study_cu_final.best_value
            - study_cu.best_value
        )
    }
])

comparacion_final

  variante  optuna_v1  optuna_final  diferencia
0       mx   0.623517      0.625833    0.002316
1       es   0.703954      0.699641   -0.004313
2       cu   0.666562      0.665341   -0.001222

In [34]:
STUDY_GANADOR = {
    "mx": study_mx_final,
    "es": study_es_final,
    "cu": study_cu
}

In [35]:
from sklearn.model_selection import GridSearchCV

def grid_local_variante(variante):

    df_train = cargar_train_ganador(variante)

    X = df_train[
        ["MESSAGE_CLEAN"] + FEATURE_COLS
    ]

    y = df_train["IS_IRONIC"].values

    scale_pos_weight = (
        (y == 0).sum() /
        (y == 1).sum()
    )

    # Mejor configuración encontrada con Optuna
    best = STUDY_GANADOR[variante].best_params.copy()

    # En CU puede venir guardado ngram_range
    best.pop("ngram_range", None)

    model = XGBClassifier(
        subsample=best["subsample"],
        colsample_bytree=best["colsample_bytree"],
        gamma=best["gamma"],
        reg_alpha=best["reg_alpha"],
        reg_lambda=best["reg_lambda"],

        scale_pos_weight=scale_pos_weight,
        objective="binary:logistic",
        eval_metric="logloss",
        booster="gbtree",
        tree_method="hist",
        random_state=RANDOM_STATE,
        n_jobs=-1
    )

    pipeline = Pipeline([
        (
            "prep",
            build_tfidf_prep((1, 2))
        ),
        ("clf", model)
    ])

    # Grid pequeño alrededor de Optuna
    n_est = best["n_estimators"]
    depth = best["max_depth"]
    lr = best["learning_rate"]
    child = best["min_child_weight"]

    param_grid = {
        "clf__n_estimators": sorted(set([
            max(50, n_est - 50),
            n_est,
            n_est + 50
        ])),

        "clf__max_depth": sorted(set([
            max(2, depth - 1),
            depth,
            depth + 1
        ])),

        "clf__learning_rate": sorted(set([
            max(0.01, lr * 0.75),
            lr,
            min(0.30, lr * 1.25)
        ])),

        "clf__min_child_weight": sorted(set([
            max(1, child - 1),
            child,
            child + 1
        ]))
    }

    grid = GridSearchCV(
        estimator=pipeline,
        param_grid=param_grid,
        scoring="f1_macro",
        cv=CV,
        n_jobs=1,
        verbose=1,
        refit=True
    )

    grid.fit(X, y)

    print(f"\n{variante.upper()}")
    print(
        "Optuna:",
        STUDY_GANADOR[variante].best_value
    )
    print(
        "GridSearch:",
        grid.best_score_
    )
    print(
        "Mejores parámetros:",
        grid.best_params_
    )

    return grid

In [36]:
grid_mx = grid_local_variante("mx")
grid_es = grid_local_variante("es")
grid_cu = grid_local_variante("cu")

Fitting 5 folds for each of 81 candidates, totalling 405 fits

MX
Optuna: 0.6258329468316003
GridSearch: 0.6258329468316003
Mejores parámetros: {'clf__learning_rate': 0.06299349502760707, 'clf__max_depth': 10, 'clf__min_child_weight': 3, 'clf__n_estimators': 300}
Fitting 5 folds for each of 81 candidates, totalling 405 fits

ES
Optuna: 0.6996407075532447
GridSearch: 0.7017270033413545
Mejores parámetros: {'clf__learning_rate': 0.06147854456275125, 'clf__max_depth': 4, 'clf__min_child_weight': 1, 'clf__n_estimators': 300}
Fitting 5 folds for each of 81 candidates, totalling 405 fits

CU
Optuna: 0.6665622610215698
GridSearch: 0.6616548378659992
Mejores parámetros: {'clf__learning_rate': 0.015890532329436432, 'clf__max_depth': 3, 'clf__min_child_weight': 2, 'clf__n_estimators': 650}

In [37]:
comparacion_grid = pd.DataFrame([
    {
        "variante": "mx",
        "optuna": STUDY_GANADOR["mx"].best_value,
        "grid": grid_mx.best_score_,
        "diferencia": (
            grid_mx.best_score_
            - STUDY_GANADOR["mx"].best_value
        )
    },
    {
        "variante": "es",
        "optuna": STUDY_GANADOR["es"].best_value,
        "grid": grid_es.best_score_,
        "diferencia": (
            grid_es.best_score_
            - STUDY_GANADOR["es"].best_value
        )
    },
    {
        "variante": "cu",
        "optuna": STUDY_GANADOR["cu"].best_value,
        "grid": grid_cu.best_score_,
        "diferencia": (
            grid_cu.best_score_
            - STUDY_GANADOR["cu"].best_value
        )
    }
])

comparacion_grid

  variante    optuna      grid  diferencia
0       mx  0.625833  0.625833    0.000000
1       es  0.699641  0.701727    0.002086
2       cu  0.666562  0.661655   -0.004907

In [38]:
CONFIG_FINAL_XGB = {
    "mx": {
        "source": "grid",
        "best_score_cv": grid_mx.best_score_,
        "best_params": grid_mx.best_params_
    },

    "es": {
        "source": "grid",
        "best_score_cv": grid_es.best_score_,
        "best_params": grid_es.best_params_
    },

    "cu": {
        "source": "grid",
        "best_score_cv": grid_cu.best_score_,
        "best_params": grid_cu.best_params_
    }
}

In [39]:
resumen_final_xgb = pd.DataFrame([
    {
        "variante": "mx",
        "metodo_seleccion": "GridSearch local",
        "f1_macro_cv": grid_mx.best_score_
    },
    {
        "variante": "es",
        "metodo_seleccion": "GridSearch local",
        "f1_macro_cv": grid_es.best_score_
    },
    {
        "variante": "cu",
        "metodo_seleccion": "GridSearch local",
        "f1_macro_cv": grid_cu.best_score_
    }
])

resumen_final_xgb

  variante  metodo_seleccion  f1_macro_cv
0       mx  GridSearch local     0.625833
1       es  GridSearch local     0.701727
2       cu  GridSearch local     0.661655