In [2]:
# ============================================================
# XGBOOST - COMPARACIÓN DE PREPROCESAMIENTO
# normal vs stemming vs lematización
# Variantes: MX / ES / CU
# Métrica principal: F1-Macro
# Validación: Stratified 5-Fold
# ============================================================

import pandas as pd
import numpy as np

from sklearn.compose import ColumnTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import StratifiedKFold, cross_validate

from xgboost import XGBClassifier


# ============================================================
# 1. CONFIGURACIÓN GENERAL
# ============================================================

RANDOM_STATE = 42

VARIANTES = ['mx', 'es', 'cu']

PREPROCESAMIENTOS = {
    'normal': '',
    'stem': '_stem',
    'lemma': '_lemma'
}

FEATURE_COLS = [
    'n_exc',  # exclamaciones
    'n_int',  # interrogaciones
    'n_may',  # palabras en mayúsculas
    'n_emo',  # emojis
    'n_ris',  # expresiones de risa
    'n_neg',  # negaciones
    'n_elo',  # elongaciones
    'n_com',  # comillas
    'n_pun'   # puntos suspensivos
]

CV = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=RANDOM_STATE
)


# ============================================================
# 2. CARGA DE DATOS
# ============================================================
#
# Modifica DATA_DIR si tus CSV están en otra carpeta.
#
# Se espera una estructura parecida a:
#
# train_clean_mx.csv
# train_clean_es.csv
# train_clean_cu.csv
#
# train_clean_stem_mx.csv
# train_clean_stem_es.csv
# train_clean_stem_cu.csv
#
# train_clean_lemma_mx.csv
# train_clean_lemma_es.csv
# train_clean_lemma_cu.csv
#
# ============================================================

DATA_DIR = '../data'


def cargar_train(variante, prep):

    sufijo = PREPROCESAMIENTOS[prep]

    ruta = f'{DATA_DIR}/train_clean{sufijo}_{variante}.csv'

    print(f'Cargando: {ruta}')

    df = pd.read_csv(ruta)

    return df


# ============================================================
# 3. PREPROCESADOR
# ============================================================
#
# TF-IDF:
# - unigramas + bigramas
# - hasta 20 000 términos
# - min_df=2 para eliminar términos extremadamente raros
# - sublinear_tf=True
#
# NO eliminamos stopwords aquí.
#
# TF-IDF acepta ngram_range, min_df, max_df,
# max_features y sublinear_tf de forma nativa.
#
# ============================================================

def crear_preprocesador():

    tfidf = TfidfVectorizer(
        analyzer='word',
        ngram_range=(1, 2),

        min_df=2,
        max_df=0.98,

        max_features=20000,

        lowercase=False,

        sublinear_tf=True,

        dtype=np.float32
    )

    preprocesador = ColumnTransformer(
        transformers=[
            (
                'tfidf',
                tfidf,
                'MESSAGE_CLEAN'
            ),
            (
                'linguisticas',
                'passthrough',
                FEATURE_COLS
            )
        ],
        remainder='drop'
    )

    return preprocesador


# ============================================================
# 4. XGBOOST BASE
# ============================================================
#
# Esta NO es la configuración final.
# Solo sirve para comparar normal / stem / lemma.
#
# Después optimizaremos hiperparámetros con Optuna.
#
# ============================================================

def crear_xgboost(y):

    negativos = (y == 0).sum()
    positivos = (y == 1).sum()

    scale_pos_weight = negativos / positivos

    modelo = XGBClassifier(

        # Problema binario
        objective='binary:logistic',

        # Boosting
        n_estimators=300,
        learning_rate=0.05,

        # Complejidad de árboles
        max_depth=5,
        min_child_weight=2,

        # Muestreo
        subsample=0.8,
        colsample_bytree=0.8,

        # Regularización
        gamma=0,
        reg_alpha=0,
        reg_lambda=1,

        # Desbalance
        scale_pos_weight=scale_pos_weight,

        # Algoritmo eficiente
        tree_method='hist',

        # Reproducibilidad
        random_state=RANDOM_STATE,

        # Paralelización interna
        n_jobs=-1,

        # Métrica interna de entrenamiento
        eval_metric='logloss'
    )

    return modelo


# ============================================================
# 5. FUNCIÓN DE EVALUACIÓN
# ============================================================

def evaluar_preprocesamiento(variante, prep):

    df = cargar_train(
        variante=variante,
        prep=prep
    )

    # --------------------------------------------------------
    # Comprobaciones
    # --------------------------------------------------------

    columnas_necesarias = (
        ['MESSAGE_CLEAN', 'IS_IRONIC']
        + FEATURE_COLS
    )

    faltantes = [
        col
        for col in columnas_necesarias
        if col not in df.columns
    ]

    if faltantes:
        raise ValueError(
            f'Faltan columnas en {variante}-{prep}: '
            f'{faltantes}'
        )

    # --------------------------------------------------------
    # Datos
    # --------------------------------------------------------

    X = df[
        ['MESSAGE_CLEAN'] + FEATURE_COLS
    ].copy()

    y = df['IS_IRONIC'].astype(int)

    # Por si hubiera NaN en texto
    X['MESSAGE_CLEAN'] = (
        X['MESSAGE_CLEAN']
        .fillna('')
        .astype(str)
    )

    # Por si hubiera NaN en features lingüísticas
    X[FEATURE_COLS] = (
        X[FEATURE_COLS]
        .fillna(0)
    )

    # --------------------------------------------------------
    # Información de clases
    # --------------------------------------------------------

    negativos = (y == 0).sum()
    positivos = (y == 1).sum()

    print(
        f'Clase 0: {negativos} | '
        f'Clase 1: {positivos} | '
        f'ratio: {negativos / positivos:.3f}'
    )

    # --------------------------------------------------------
    # Pipeline
    # --------------------------------------------------------

    pipeline = Pipeline(
        steps=[
            (
                'features',
                crear_preprocesador()
            ),
            (
                'xgb',
                crear_xgboost(y)
            )
        ]
    )

    # --------------------------------------------------------
    # Cross Validation
    # --------------------------------------------------------

    scores = cross_validate(
        estimator=pipeline,

        X=X,
        y=y,

        cv=CV,

        scoring={
            'f1_macro': 'f1_macro',
            'accuracy': 'accuracy',
            'precision_macro': 'precision_macro',
            'recall_macro': 'recall_macro'
        },

        # Evitamos paralelizar folds + XGBoost simultáneamente
        n_jobs=1,

        return_train_score=False
    )

    # --------------------------------------------------------
    # Resultado
    # --------------------------------------------------------

    resultado = {
        'variante': variante,
        'preprocesamiento': prep,

        'f1_macro_mean':
            scores['test_f1_macro'].mean(),

        'f1_macro_std':
            scores['test_f1_macro'].std(),

        'accuracy_mean':
            scores['test_accuracy'].mean(),

        'precision_macro_mean':
            scores['test_precision_macro'].mean(),

        'recall_macro_mean':
            scores['test_recall_macro'].mean()
    }

    return resultado


# ============================================================
# 6. EJECUTAR TODOS LOS EXPERIMENTOS
# ============================================================

resultados = []

for variante in VARIANTES:

    print('\n')
    print('=' * 65)
    print(f'VARIANTE: {variante.upper()}')
    print('=' * 65)

    for prep in PREPROCESAMIENTOS:

        print('\n')
        print('-' * 45)
        print(f'Preprocesamiento: {prep.upper()}')
        print('-' * 45)

        resultado = evaluar_preprocesamiento(
            variante=variante,
            prep=prep
        )

        resultados.append(resultado)

        print(
            '\nResultado: '
            f'F1-Macro = '
            f'{resultado["f1_macro_mean"]:.4f} '
            f'± '
            f'{resultado["f1_macro_std"]:.4f}'
        )


# ============================================================
# 7. TABLA COMPLETA DE RESULTADOS
# ============================================================

df_resultados = pd.DataFrame(resultados)

df_resultados = (
    df_resultados
    .sort_values(
        by=[
            'variante',
            'f1_macro_mean'
        ],
        ascending=[
            True,
            False
        ]
    )
    .reset_index(drop=True)
)

print('\n')
print('=' * 70)
print('RESULTADOS COMPLETOS')
print('=' * 70)

display(
    df_resultados.style.format({
        'f1_macro_mean': '{:.4f}',
        'f1_macro_std': '{:.4f}',
        'accuracy_mean': '{:.4f}',
        'precision_macro_mean': '{:.4f}',
        'recall_macro_mean': '{:.4f}'
    })
)


# ============================================================
# 8. MEJOR PREPROCESAMIENTO POR VARIANTE
# ============================================================

mejores_preprocesamientos = (
    df_resultados
    .sort_values(
        'f1_macro_mean',
        ascending=False
    )
    .groupby(
        'variante',
        as_index=False
    )
    .first()
)

print('\n')
print('=' * 70)
print('MEJOR PREPROCESAMIENTO POR VARIANTE')
print('=' * 70)

display(
    mejores_preprocesamientos.style.format({
        'f1_macro_mean': '{:.4f}',
        'f1_macro_std': '{:.4f}',
        'accuracy_mean': '{:.4f}',
        'precision_macro_mean': '{:.4f}',
        'recall_macro_mean': '{:.4f}'
    })
)


# ============================================================
# 9. MOSTRAR RANKING POR VARIANTE
# ============================================================

for variante in VARIANTES:

    print('\n')
    print('=' * 60)
    print(f'RANKING {variante.upper()}')
    print('=' * 60)

    ranking = (
        df_resultados[
            df_resultados['variante'] == variante
        ]
        .sort_values(
            'f1_macro_mean',
            ascending=False
        )
        [
            [
                'preprocesamiento',
                'f1_macro_mean',
                'f1_macro_std',
                'accuracy_mean',
                'precision_macro_mean',
                'recall_macro_mean'
            ]
        ]
    )

    display(
        ranking.style.format({
            'f1_macro_mean': '{:.4f}',
            'f1_macro_std': '{:.4f}',
            'accuracy_mean': '{:.4f}',
            'precision_macro_mean': '{:.4f}',
            'recall_macro_mean': '{:.4f}'
        })
    )

=================================================================
VARIANTE: MX
=================================================================


---------------------------------------------
Preprocesamiento: NORMAL
---------------------------------------------
Cargando: ../data/train_clean_mx.csv
Clase 0: 1599 | Clase 1: 800 | ratio: 1.999

Resultado: F1-Macro = 0.6127 ± 0.0112


---------------------------------------------
Preprocesamiento: STEM
---------------------------------------------
Cargando: ../data/train_clean_stem_mx.csv
Clase 0: 1599 | Clase 1: 800 | ratio: 1.999

Resultado: F1-Macro = 0.6084 ± 0.0210


---------------------------------------------
Preprocesamiento: LEMMA
---------------------------------------------
Cargando: ../data/train_clean_lemma_mx.csv
Clase 0: 1599 | Clase 1: 800 | ratio: 1.999

Resultado: F1-Macro = 0.6100 ± 0.0092


=================================================================
VARIANTE: ES
=================================================================


---------------------------------------------
Preprocesamiento: NORMAL
---------------------------------------------
Cargando: ../data/train_clean_es.csv
Clase 0: 1598 | Clase 1: 800 | ratio: 1.998

Resultado: F1-Macro = 0.6902 ± 0.0152


---------------------------------------------
Preprocesamiento: STEM
---------------------------------------------
Cargando: ../data/train_clean_stem_es.csv
Clase 0: 1598 | Clase 1: 800 | ratio: 1.998

Resultado: F1-Macro = 0.6985 ± 0.0150


---------------------------------------------
Preprocesamiento: LEMMA
---------------------------------------------
Cargando: ../data/train_clean_lemma_es.csv
Clase 0: 1598 | Clase 1: 800 | ratio: 1.998

Resultado: F1-Macro = 0.7028 ± 0.0188


=================================================================
VARIANTE: CU
=================================================================


---------------------------------------------
Preprocesamiento: NORMAL
---------------------------------------------
Cargando: ../data/train_clean_cu.csv
Clase 0: 1600 | Clase 1: 800 | ratio: 2.000

Resultado: F1-Macro = 0.6578 ± 0.0197


---------------------------------------------
Preprocesamiento: STEM
---------------------------------------------
Cargando: ../data/train_clean_stem_cu.csv
Clase 0: 1600 | Clase 1: 800 | ratio: 2.000

Resultado: F1-Macro = 0.6581 ± 0.0209


---------------------------------------------
Preprocesamiento: LEMMA
---------------------------------------------
Cargando: ../data/train_clean_lemma_cu.csv
Clase 0: 1600 | Clase 1: 800 | ratio: 2.000

Resultado: F1-Macro = 0.6389 ± 0.0136


======================================================================
RESULTADOS COMPLETOS
======================================================================

======================================================================
MEJOR PREPROCESAMIENTO POR VARIANTE
======================================================================

============================================================
RANKING MX
============================================================

============================================================
RANKING ES
============================================================

============================================================
RANKING CU
============================================================

In [3]:
# ============================================================
# 10. OPTIMIZACIÓN DE XGBOOST CON OPTUNA
# ============================================================

import optuna

from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score
from xgboost import XGBClassifier


# ============================================================
# 10.1 PREPROCESAMIENTO GANADOR POR VARIANTE
# ============================================================

MEJOR_PREP = {
    'mx': 'normal',
    'es': 'lemma',
    'cu': 'stem'
}


# ============================================================
# 10.2 FUNCIÓN OBJETIVO PARA OPTUNA
# ============================================================

def objective_xgboost(trial, variante):

    prep = MEJOR_PREP[variante]

    df = cargar_train(
        variante=variante,
        prep=prep
    )

    X = df[
        ['MESSAGE_CLEAN'] + FEATURE_COLS
    ].copy()

    y = df['IS_IRONIC'].astype(int)

    # Seguridad ante NaN
    X['MESSAGE_CLEAN'] = (
        X['MESSAGE_CLEAN']
        .fillna('')
        .astype(str)
    )

    X[FEATURE_COLS] = (
        X[FEATURE_COLS]
        .fillna(0)
    )

    # --------------------------------------------------------
    # Espacio de búsqueda
    # --------------------------------------------------------

    params = {

        'n_estimators': trial.suggest_int(
            'n_estimators',
            100,
            800,
            step=50
        ),

        'max_depth': trial.suggest_int(
            'max_depth',
            2,
            10
        ),

        'learning_rate': trial.suggest_float(
            'learning_rate',
            0.01,
            0.30,
            log=True
        ),

        'min_child_weight': trial.suggest_int(
            'min_child_weight',
            1,
            10
        ),

        'subsample': trial.suggest_float(
            'subsample',
            0.60,
            1.00
        ),

        'colsample_bytree': trial.suggest_float(
            'colsample_bytree',
            0.50,
            1.00
        ),

        'gamma': trial.suggest_float(
            'gamma',
            0.0,
            5.0
        ),

        'reg_alpha': trial.suggest_float(
            'reg_alpha',
            1e-4,
            10.0,
            log=True
        ),

        'reg_lambda': trial.suggest_float(
            'reg_lambda',
            1e-3,
            20.0,
            log=True
        ),

        'scale_pos_weight': trial.suggest_float(
            'scale_pos_weight',
            1.0,
            3.0
        )
    }

    # --------------------------------------------------------
    # Modelo
    # --------------------------------------------------------

    modelo = XGBClassifier(

        objective='binary:logistic',

        tree_method='hist',

        eval_metric='logloss',

        random_state=RANDOM_STATE,

        n_jobs=-1,

        **params
    )

    # --------------------------------------------------------
    # Pipeline
    # --------------------------------------------------------

    pipeline = Pipeline(
        steps=[
            (
                'features',
                crear_preprocesador()
            ),
            (
                'xgb',
                modelo
            )
        ]
    )

    # --------------------------------------------------------
    # Stratified 5-Fold
    # --------------------------------------------------------

    scores = cross_val_score(
        estimator=pipeline,
        X=X,
        y=y,
        cv=CV,
        scoring='f1_macro',

        # Evita paralelizar folds y XGBoost simultáneamente
        n_jobs=1
    )

    return scores.mean()


# ============================================================
# 10.3 EJECUTAR OPTUNA POR VARIANTE
# ============================================================

N_TRIALS = 50

studies = {}

for variante in ['mx', 'es', 'cu']:

    print('\n')
    print('=' * 70)
    print(f'OPTUNA - VARIANTE {variante.upper()}')
    print(
        f'Preprocesamiento seleccionado: '
        f'{MEJOR_PREP[variante]}'
    )
    print('=' * 70)

    sampler = optuna.samplers.TPESampler(
        seed=RANDOM_STATE
    )

    study = optuna.create_study(
        direction='maximize',
        sampler=sampler,
        study_name=f'xgboost_{variante}'
    )

    study.optimize(
        lambda trial: objective_xgboost(
            trial,
            variante
        ),
        n_trials=N_TRIALS,
        show_progress_bar=True
    )

    studies[variante] = study

    print('\n')
    print(
        f'Mejor F1-Macro CV: '
        f'{study.best_value:.4f}'
    )

    print('\nMejores hiperparámetros:')

    for parametro, valor in study.best_params.items():
        print(
            f'  {parametro}: {valor}'
        )


# ============================================================
# 10.4 RESUMEN DE RESULTADOS DE OPTUNA
# ============================================================

resumen_optuna = []

for variante, study in studies.items():

    fila = {
        'variante': variante,
        'preprocesamiento':
            MEJOR_PREP[variante],

        'best_f1_macro_cv':
            study.best_value,

        'best_trial':
            study.best_trial.number
    }

    fila.update(
        study.best_params
    )

    resumen_optuna.append(fila)


df_optuna = pd.DataFrame(
    resumen_optuna
)

print('\n')
print('=' * 70)
print('MEJORES RESULTADOS OPTUNA')
print('=' * 70)

display(
    df_optuna.style.format({
        'best_f1_macro_cv': '{:.4f}',
        'learning_rate': '{:.5f}',
        'subsample': '{:.4f}',
        'colsample_bytree': '{:.4f}',
        'gamma': '{:.4f}',
        'reg_alpha': '{:.5f}',
        'reg_lambda': '{:.5f}',
        'scale_pos_weight': '{:.4f}'
    })
)


# ============================================================
# 10.5 HISTORIAL DE TRIALS
# ============================================================

for variante, study in studies.items():

    print('\n')
    print('=' * 70)
    print(f'TOP 10 TRIALS - {variante.upper()}')
    print('=' * 70)

    df_trials = study.trials_dataframe()

    columnas = [
        'number',
        'value'
    ] + [
        col
        for col in df_trials.columns
        if col.startswith('params_')
    ]

    display(
        df_trials[
            columnas
        ]
        .sort_values(
            'value',
            ascending=False
        )
        .head(10)
    )

[I 2026-09-21 16:56:55,725] A new study created in memory with name: xgboost_mx

======================================================================
OPTUNA - VARIANTE MX
Preprocesamiento seleccionado: normal
======================================================================

  0%|          | 0/50 [00:00<?, ?it/s]

Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:57:01,311] Trial 0 finished with value: 0.5922952189215975 and parameters: {'n_estimators': 350, 'max_depth': 10, 'learning_rate': 0.1205712628744377, 'min_child_weight': 6, 'subsample': 0.6624074561769746, 'colsample_bytree': 0.5779972601681014, 'gamma': 0.2904180608409973, 'reg_alpha': 2.1423021757741068, 'reg_lambda': 0.3849583075868115, 'scale_pos_weight': 2.416145155592091}. Best is trial 0 with value: 0.5922952189215975.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:57:03,710] Trial 1 finished with value: 0.5879048875235989 and parameters: {'n_estimators': 100, 'max_depth': 10, 'learning_rate': 0.16967533607196555, 'min_child_weight': 3, 'subsample': 0.6727299868828402, 'colsample_bytree': 0.5917022549267169, 'gamma': 1.5212112147976886, 'reg_alpha': 0.042051564509138675, 'reg_lambda': 0.07207895500630218, 'scale_pos_weight': 1.5824582803960838}. Best is trial 0 with value: 0.5922952189215975.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:57:08,171] Trial 2 finished with value: 0.5984012144671708 and parameters: {'n_estimators': 550, 'max_depth': 3, 'learning_rate': 0.027010527749605478, 'min_child_weight': 4, 'subsample': 0.7824279936868144, 'colsample_bytree': 0.8925879806965068, 'gamma': 0.9983689107917987, 'reg_alpha': 0.03725393839578886, 'reg_lambda': 0.35317733939252866, 'scale_pos_weight': 1.0929008254399954}. Best is trial 2 with value: 0.5984012144671708.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:57:12,603] Trial 3 finished with value: 0.5977829567790046 and parameters: {'n_estimators': 550, 'max_depth': 3, 'learning_rate': 0.012476394272569451, 'min_child_weight': 10, 'subsample': 0.9862528132298237, 'colsample_bytree': 0.9041986740582306, 'gamma': 1.5230688458668533, 'reg_alpha': 0.0003078651783619622, 'reg_lambda': 0.8768125777016167, 'scale_pos_weight': 1.8803049874792026}. Best is trial 2 with value: 0.5984012144671708.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:57:14,999] Trial 4 finished with value: 0.5850814426775114 and parameters: {'n_estimators': 150, 'max_depth': 6, 'learning_rate': 0.011240768803005551, 'min_child_weight': 10, 'subsample': 0.7035119926400067, 'colsample_bytree': 0.831261142176991, 'gamma': 1.5585553804470549, 'reg_alpha': 0.039841905944346875, 'reg_lambda': 0.22460390897586935, 'scale_pos_weight': 1.369708911051054}. Best is trial 2 with value: 0.5984012144671708.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:57:23,084] Trial 5 finished with value: 0.5717200525296495 and parameters: {'n_estimators': 800, 'max_depth': 8, 'learning_rate': 0.24420460844911424, 'min_child_weight': 9, 'subsample': 0.8391599915244341, 'colsample_bytree': 0.9609371175115584, 'gamma': 0.4424625102595975, 'reg_alpha': 0.0009548041810464163, 'reg_lambda': 0.001565034538003576, 'scale_pos_weight': 1.6506606615265287}. Best is trial 2 with value: 0.5984012144671708.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:57:26,486] Trial 6 finished with value: 0.6049342786487865 and parameters: {'n_estimators': 350, 'max_depth': 4, 'learning_rate': 0.16755052359850303, 'min_child_weight': 4, 'subsample': 0.7123738038749523, 'colsample_bytree': 0.7713480415791243, 'gamma': 0.7046211248738132, 'reg_alpha': 1.025616274847307, 'reg_lambda': 0.002092399245066083, 'scale_pos_weight': 2.9737738732010346}. Best is trial 6 with value: 0.6049342786487865.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:57:31,603] Trial 7 finished with value: 0.5811303705883363 and parameters: {'n_estimators': 650, 'max_depth': 3, 'learning_rate': 0.010189592979395137, 'min_child_weight': 9, 'subsample': 0.8827429375390468, 'colsample_bytree': 0.8645035840204937, 'gamma': 3.8563517334297286, 'reg_alpha': 0.00023454342277260534, 'reg_lambda': 0.034815437009482725, 'scale_pos_weight': 1.2317381190502594}. Best is trial 6 with value: 0.6049342786487865.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:57:37,918] Trial 8 finished with value: 0.6018175716352695 and parameters: {'n_estimators': 700, 'max_depth': 7, 'learning_rate': 0.030816017044468066, 'min_child_weight': 1, 'subsample': 0.7243929286862649, 'colsample_bytree': 0.6625916610133735, 'gamma': 3.64803089169032, 'reg_alpha': 0.1540945776288154, 'reg_lambda': 6.545285853960302, 'scale_pos_weight': 1.9444298503238986}. Best is trial 6 with value: 0.6049342786487865.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:57:39,947] Trial 9 finished with value: 0.5834156493069262 and parameters: {'n_estimators': 150, 'max_depth': 8, 'learning_rate': 0.13297554090738672, 'min_child_weight': 6, 'subsample': 0.9083868719818244, 'colsample_bytree': 0.7468977981821954, 'gamma': 2.6136641469099704, 'reg_alpha': 0.013731092468240296, 'reg_lambda': 0.0012862590001032788, 'scale_pos_weight': 1.215782853986609}. Best is trial 6 with value: 0.6049342786487865.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:57:42,208] Trial 10 finished with value: 0.5582575235081954 and parameters: {'n_estimators': 250, 'max_depth': 4, 'learning_rate': 0.13307260979777857, 'min_child_weight': 10, 'subsample': 0.6628357665489781, 'colsample_bytree': 0.838466367272767, 'gamma': 3.902734147156754, 'reg_alpha': 4.578510427150422, 'reg_lambda': 0.0023901919011402217, 'scale_pos_weight': 2.6466014560195474}. Best is trial 6 with value: 0.6049342786487865.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:57:46,384] Trial 11 finished with value: 0.5796317255934159 and parameters: {'n_estimators': 450, 'max_depth': 4, 'learning_rate': 0.07797255942100832, 'min_child_weight': 7, 'subsample': 0.7830265590945842, 'colsample_bytree': 0.7257507510810043, 'gamma': 0.6745462507676732, 'reg_alpha': 3.008638981468325, 'reg_lambda': 0.2837041172521452, 'scale_pos_weight': 2.8767821375241667}. Best is trial 6 with value: 0.6049342786487865.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:57:49,266] Trial 12 finished with value: 0.5903704448526534 and parameters: {'n_estimators': 300, 'max_depth': 5, 'learning_rate': 0.22516884922347646, 'min_child_weight': 3, 'subsample': 0.7405382175276275, 'colsample_bytree': 0.7199746022641412, 'gamma': 3.178167009719738, 'reg_alpha': 0.09112572655944229, 'reg_lambda': 5.5386700416629795, 'scale_pos_weight': 2.5613025854996425}. Best is trial 6 with value: 0.6049342786487865.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:57:55,474] Trial 13 finished with value: 0.6036769437276369 and parameters: {'n_estimators': 800, 'max_depth': 5, 'learning_rate': 0.05193032776366906, 'min_child_weight': 2, 'subsample': 0.645167071965635, 'colsample_bytree': 0.6486881257876254, 'gamma': 3.5404139260489487, 'reg_alpha': 0.23955956801000108, 'reg_lambda': 0.260970577544141, 'scale_pos_weight': 1.9608686500341335}. Best is trial 6 with value: 0.6049342786487865.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:57:58,187] Trial 14 finished with value: 0.6026278968320096 and parameters: {'n_estimators': 300, 'max_depth': 3, 'learning_rate': 0.12999556085300887, 'min_child_weight': 2, 'subsample': 0.6588862877739998, 'colsample_bytree': 0.6975882834948043, 'gamma': 0.7199776369712292, 'reg_alpha': 2.2249120764571226, 'reg_lambda': 0.02397034888298291, 'scale_pos_weight': 1.6835728976495816}. Best is trial 6 with value: 0.6049342786487865.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:57:59,466] Trial 15 finished with value: 0.5488715354541576 and parameters: {'n_estimators': 100, 'max_depth': 2, 'learning_rate': 0.11105970635398382, 'min_child_weight': 2, 'subsample': 0.6700414823936431, 'colsample_bytree': 0.7460357809472592, 'gamma': 0.9076649933759591, 'reg_alpha': 0.34590784110866396, 'reg_lambda': 0.0011258227154083977, 'scale_pos_weight': 2.5992386058668795}. Best is trial 6 with value: 0.6049342786487865.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:58:03,281] Trial 16 finished with value: 0.5792908596901978 and parameters: {'n_estimators': 450, 'max_depth': 3, 'learning_rate': 0.04391096428697683, 'min_child_weight': 4, 'subsample': 0.6404364895174242, 'colsample_bytree': 0.8495986525781896, 'gamma': 0.3383407934154466, 'reg_alpha': 2.4397302153922005, 'reg_lambda': 0.0015861692562286877, 'scale_pos_weight': 2.5106101057389036}. Best is trial 6 with value: 0.6049342786487865.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:58:06,761] Trial 17 finished with value: 0.5987623026525061 and parameters: {'n_estimators': 350, 'max_depth': 4, 'learning_rate': 0.16318546958292127, 'min_child_weight': 2, 'subsample': 0.6615934879258403, 'colsample_bytree': 0.8413903479989355, 'gamma': 1.5849923736883897, 'reg_alpha': 0.08880877044614466, 'reg_lambda': 0.020972543565051367, 'scale_pos_weight': 2.566976529729315}. Best is trial 6 with value: 0.6049342786487865.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:58:12,580] Trial 18 finished with value: 0.615536783594656 and parameters: {'n_estimators': 650, 'max_depth': 4, 'learning_rate': 0.06158802642656143, 'min_child_weight': 1, 'subsample': 0.673158036914205, 'colsample_bytree': 0.773249791303957, 'gamma': 2.0366958717256205, 'reg_alpha': 0.01714096528869879, 'reg_lambda': 1.0032532318247116, 'scale_pos_weight': 1.7587808404938527}. Best is trial 18 with value: 0.615536783594656.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:58:18,201] Trial 19 finished with value: 0.598691573995295 and parameters: {'n_estimators': 700, 'max_depth': 4, 'learning_rate': 0.07957496093935025, 'min_child_weight': 1, 'subsample': 0.7307480286086183, 'colsample_bytree': 0.7716740318383992, 'gamma': 2.248928660190043, 'reg_alpha': 0.00033771593145264916, 'reg_lambda': 0.2481364916396099, 'scale_pos_weight': 1.098232096928034}. Best is trial 18 with value: 0.615536783594656.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:58:24,132] Trial 20 finished with value: 0.6034537462543114 and parameters: {'n_estimators': 800, 'max_depth': 3, 'learning_rate': 0.0564219142759185, 'min_child_weight': 1, 'subsample': 0.6091433834073912, 'colsample_bytree': 0.7333647568531841, 'gamma': 1.370456920854768, 'reg_alpha': 0.0004314158655575851, 'reg_lambda': 0.02070372389615208, 'scale_pos_weight': 1.8887504134800313}. Best is trial 18 with value: 0.615536783594656.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:58:29,949] Trial 21 finished with value: 0.6052254142164465 and parameters: {'n_estimators': 750, 'max_depth': 6, 'learning_rate': 0.0568980645828591, 'min_child_weight': 1, 'subsample': 0.6660680410855552, 'colsample_bytree': 0.7453152634532416, 'gamma': 4.755634186233372, 'reg_alpha': 0.3076792576077348, 'reg_lambda': 1.1119302925463088, 'scale_pos_weight': 2.416788734937858}. Best is trial 18 with value: 0.615536783594656.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:58:36,638] Trial 22 finished with value: 0.5986810389690631 and parameters: {'n_estimators': 600, 'max_depth': 6, 'learning_rate': 0.142906965985697, 'min_child_weight': 4, 'subsample': 0.7749889675971657, 'colsample_bytree': 0.8154758430972684, 'gamma': 0.270523259684317, 'reg_alpha': 0.23852324219378898, 'reg_lambda': 0.0071735737304411545, 'scale_pos_weight': 2.873041616484581}. Best is trial 18 with value: 0.615536783594656.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:58:40,703] Trial 23 finished with value: 0.6001338236097222 and parameters: {'n_estimators': 350, 'max_depth': 5, 'learning_rate': 0.22389312388021854, 'min_child_weight': 1, 'subsample': 0.7771203940600636, 'colsample_bytree': 0.7592688417555339, 'gamma': 0.21889770231492922, 'reg_alpha': 0.909087111266729, 'reg_lambda': 0.0020066921274651973, 'scale_pos_weight': 2.7120121349844997}. Best is trial 18 with value: 0.615536783594656.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:58:46,393] Trial 24 finished with value: 0.5983805875396427 and parameters: {'n_estimators': 550, 'max_depth': 6, 'learning_rate': 0.04337230219298867, 'min_child_weight': 2, 'subsample': 0.7353885704870811, 'colsample_bytree': 0.7134321504482217, 'gamma': 2.831730088997952, 'reg_alpha': 0.5679867200674394, 'reg_lambda': 2.129037952527833, 'scale_pos_weight': 2.5765072414766705}. Best is trial 18 with value: 0.615536783594656.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:58:53,852] Trial 25 finished with value: 0.6044568681335991 and parameters: {'n_estimators': 800, 'max_depth': 5, 'learning_rate': 0.04882190672520078, 'min_child_weight': 2, 'subsample': 0.6989568155247856, 'colsample_bytree': 0.7299717882627698, 'gamma': 1.9560577602198157, 'reg_alpha': 0.006213070341993567, 'reg_lambda': 0.6129280808552563, 'scale_pos_weight': 2.1248845820482227}. Best is trial 18 with value: 0.615536783594656.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:59:03,069] Trial 26 finished with value: 0.5996576574934547 and parameters: {'n_estimators': 800, 'max_depth': 6, 'learning_rate': 0.026280744069249136, 'min_child_weight': 1, 'subsample': 0.6315124445220045, 'colsample_bytree': 0.7861564645217153, 'gamma': 2.5760435041713823, 'reg_alpha': 0.09369350894227382, 'reg_lambda': 0.8280565178911673, 'scale_pos_weight': 2.527753623668832}. Best is trial 18 with value: 0.615536783594656.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:59:08,458] Trial 27 finished with value: 0.5916601488322623 and parameters: {'n_estimators': 750, 'max_depth': 5, 'learning_rate': 0.09076546087317398, 'min_child_weight': 4, 'subsample': 0.6223650264575857, 'colsample_bytree': 0.7280281275303588, 'gamma': 4.317611001797975, 'reg_alpha': 0.7343488541425889, 'reg_lambda': 1.0219349612608681, 'scale_pos_weight': 2.99174473030736}. Best is trial 18 with value: 0.615536783594656.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:59:11,702] Trial 28 finished with value: 0.5785673670496929 and parameters: {'n_estimators': 300, 'max_depth': 5, 'learning_rate': 0.05449911925071044, 'min_child_weight': 5, 'subsample': 0.7269852166860765, 'colsample_bytree': 0.6740346633054048, 'gamma': 0.6966576658886333, 'reg_alpha': 0.2805368703859911, 'reg_lambda': 0.039855850066160096, 'scale_pos_weight': 2.8027615299705637}. Best is trial 18 with value: 0.615536783594656.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:59:16,252] Trial 29 finished with value: 0.5981595470928165 and parameters: {'n_estimators': 550, 'max_depth': 5, 'learning_rate': 0.051141197520297284, 'min_child_weight': 4, 'subsample': 0.611576261080137, 'colsample_bytree': 0.7526212303403812, 'gamma': 4.1177888412532155, 'reg_alpha': 0.7532037746977274, 'reg_lambda': 1.5323816796401935, 'scale_pos_weight': 2.0886697883626053}. Best is trial 18 with value: 0.615536783594656.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:59:18,560] Trial 30 finished with value: 0.6004771653900232 and parameters: {'n_estimators': 200, 'max_depth': 4, 'learning_rate': 0.1964663570953108, 'min_child_weight': 3, 'subsample': 0.7492329311995334, 'colsample_bytree': 0.7898813592397594, 'gamma': 1.7518415377205607, 'reg_alpha': 0.31001252531417806, 'reg_lambda': 0.007739262142137478, 'scale_pos_weight': 2.830275872903943}. Best is trial 18 with value: 0.615536783594656.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:59:25,984] Trial 31 finished with value: 0.6084019463970044 and parameters: {'n_estimators': 750, 'max_depth': 5, 'learning_rate': 0.026923370937456666, 'min_child_weight': 1, 'subsample': 0.6553813794877319, 'colsample_bytree': 0.7644877280772198, 'gamma': 2.1194392795702917, 'reg_alpha': 0.0014433678878964184, 'reg_lambda': 0.12476243230691265, 'scale_pos_weight': 1.8838337361768096}. Best is trial 18 with value: 0.615536783594656.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:59:33,061] Trial 32 finished with value: 0.5808753162817897 and parameters: {'n_estimators': 800, 'max_depth': 7, 'learning_rate': 0.0301425129116782, 'min_child_weight': 1, 'subsample': 0.6560930549612601, 'colsample_bytree': 0.6857705320250914, 'gamma': 3.6003326657765813, 'reg_alpha': 1.7955718620610412, 'reg_lambda': 1.0312478415800679, 'scale_pos_weight': 2.7845796038184427}. Best is trial 18 with value: 0.615536783594656.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:59:38,794] Trial 33 finished with value: 0.5949830719488425 and parameters: {'n_estimators': 700, 'max_depth': 7, 'learning_rate': 0.03461315306431339, 'min_child_weight': 2, 'subsample': 0.6081196760573244, 'colsample_bytree': 0.6944046914345551, 'gamma': 3.7764381110240692, 'reg_alpha': 1.9968724474786217, 'reg_lambda': 3.083621864499324, 'scale_pos_weight': 2.16267568923292}. Best is trial 18 with value: 0.615536783594656.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:59:43,685] Trial 34 finished with value: 0.6023931669877951 and parameters: {'n_estimators': 700, 'max_depth': 5, 'learning_rate': 0.0458676401733156, 'min_child_weight': 3, 'subsample': 0.7053937776512812, 'colsample_bytree': 0.7461423455714905, 'gamma': 4.1671730979736985, 'reg_alpha': 2.148758798544195, 'reg_lambda': 2.0319759403902404, 'scale_pos_weight': 1.9654746531947636}. Best is trial 18 with value: 0.615536783594656.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:59:46,301] Trial 35 finished with value: 0.5901817601967485 and parameters: {'n_estimators': 250, 'max_depth': 4, 'learning_rate': 0.1302748138363223, 'min_child_weight': 3, 'subsample': 0.7028320121126477, 'colsample_bytree': 0.7526214000581284, 'gamma': 0.5916342220890859, 'reg_alpha': 0.5685939842013966, 'reg_lambda': 0.001760758534077512, 'scale_pos_weight': 2.9820672085077553}. Best is trial 18 with value: 0.615536783594656.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:59:51,473] Trial 36 finished with value: 0.5926103415521375 and parameters: {'n_estimators': 650, 'max_depth': 6, 'learning_rate': 0.09645469562986614, 'min_child_weight': 2, 'subsample': 0.6163565415728476, 'colsample_bytree': 0.7553624499882461, 'gamma': 4.091811404677715, 'reg_alpha': 0.017491229364894424, 'reg_lambda': 1.084177471383125, 'scale_pos_weight': 2.3400270714983207}. Best is trial 18 with value: 0.615536783594656.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 16:59:56,496] Trial 37 finished with value: 0.6058864222163182 and parameters: {'n_estimators': 550, 'max_depth': 5, 'learning_rate': 0.052394863143752655, 'min_child_weight': 1, 'subsample': 0.6594043295436535, 'colsample_bytree': 0.7456130938699508, 'gamma': 4.453468392769143, 'reg_alpha': 0.051464981247464577, 'reg_lambda': 0.23797353498869794, 'scale_pos_weight': 1.9599001756142693}. Best is trial 18 with value: 0.615536783594656.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:00:02,367] Trial 38 finished with value: 0.6065972648381097 and parameters: {'n_estimators': 700, 'max_depth': 4, 'learning_rate': 0.04893715768457321, 'min_child_weight': 2, 'subsample': 0.6583805213294627, 'colsample_bytree': 0.7010809205887247, 'gamma': 2.270540865259585, 'reg_alpha': 0.02930027724210045, 'reg_lambda': 1.8509378652761628, 'scale_pos_weight': 1.7746095803231834}. Best is trial 18 with value: 0.615536783594656.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:00:07,178] Trial 39 finished with value: 0.6140585018762941 and parameters: {'n_estimators': 550, 'max_depth': 6, 'learning_rate': 0.0756260866598326, 'min_child_weight': 1, 'subsample': 0.6400181185016932, 'colsample_bytree': 0.6965723691602669, 'gamma': 4.197265734764679, 'reg_alpha': 0.043187465607042355, 'reg_lambda': 0.12313074258442767, 'scale_pos_weight': 1.9633286422615472}. Best is trial 18 with value: 0.615536783594656.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:00:13,777] Trial 40 finished with value: 0.5970610056380352 and parameters: {'n_estimators': 750, 'max_depth': 4, 'learning_rate': 0.03413457534168738, 'min_child_weight': 2, 'subsample': 0.6012665471961314, 'colsample_bytree': 0.7849963334498358, 'gamma': 2.800501387528487, 'reg_alpha': 0.009620872426253622, 'reg_lambda': 5.305283971038861, 'scale_pos_weight': 2.0710991909881}. Best is trial 18 with value: 0.615536783594656.

[I 2026-09-21 17:01:01,995] A new study created in memory with name: xgboost_es

[I 2026-09-21 17:01:01,991] Trial 49 finished with value: 0.6133543900529096 and parameters: {'n_estimators': 750, 'max_depth': 7, 'learning_rate': 0.05299373096470815, 'min_child_weight': 2, 'subsample': 0.6610836129287274, 'colsample_bytree': 0.6763999918041049, 'gamma': 4.498097535405653, 'reg_alpha': 0.0011648200500346537, 'reg_lambda': 0.15343400986747352, 'scale_pos_weight': 1.7525267746437658}. Best is trial 42 with value: 0.6217677262633654.


Mejor F1-Macro CV: 0.6218

Mejores hiperparámetros:
  n_estimators: 550
  max_depth: 6
  learning_rate: 0.046809166947982796
  min_child_weight: 1
  subsample: 0.6263161245535187
  colsample_bytree: 0.7573050632130222
  gamma: 4.5665967287751945
  reg_alpha: 0.0020328469876987523
  reg_lambda: 0.44152130308969434
  scale_pos_weight: 1.7072385720641816


======================================================================
OPTUNA - VARIANTE ES
Preprocesamiento seleccionado: lemma
======================================================================

  0%|          | 0/50 [00:00<?, ?it/s]

Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:01:11,228] Trial 0 finished with value: 0.6721873052526904 and parameters: {'n_estimators': 350, 'max_depth': 10, 'learning_rate': 0.1205712628744377, 'min_child_weight': 6, 'subsample': 0.6624074561769746, 'colsample_bytree': 0.5779972601681014, 'gamma': 0.2904180608409973, 'reg_alpha': 2.1423021757741068, 'reg_lambda': 0.3849583075868115, 'scale_pos_weight': 2.416145155592091}. Best is trial 0 with value: 0.6721873052526904.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:01:14,743] Trial 1 finished with value: 0.6754239092744864 and parameters: {'n_estimators': 100, 'max_depth': 10, 'learning_rate': 0.16967533607196555, 'min_child_weight': 3, 'subsample': 0.6727299868828402, 'colsample_bytree': 0.5917022549267169, 'gamma': 1.5212112147976886, 'reg_alpha': 0.042051564509138675, 'reg_lambda': 0.07207895500630218, 'scale_pos_weight': 1.5824582803960838}. Best is trial 1 with value: 0.6754239092744864.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:01:20,747] Trial 2 finished with value: 0.6936434952610194 and parameters: {'n_estimators': 550, 'max_depth': 3, 'learning_rate': 0.027010527749605478, 'min_child_weight': 4, 'subsample': 0.7824279936868144, 'colsample_bytree': 0.8925879806965068, 'gamma': 0.9983689107917987, 'reg_alpha': 0.03725393839578886, 'reg_lambda': 0.35317733939252866, 'scale_pos_weight': 1.0929008254399954}. Best is trial 2 with value: 0.6936434952610194.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:01:26,832] Trial 3 finished with value: 0.69639076306712 and parameters: {'n_estimators': 550, 'max_depth': 3, 'learning_rate': 0.012476394272569451, 'min_child_weight': 10, 'subsample': 0.9862528132298237, 'colsample_bytree': 0.9041986740582306, 'gamma': 1.5230688458668533, 'reg_alpha': 0.0003078651783619622, 'reg_lambda': 0.8768125777016167, 'scale_pos_weight': 1.8803049874792026}. Best is trial 3 with value: 0.69639076306712.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:01:30,436] Trial 4 finished with value: 0.6904929173272124 and parameters: {'n_estimators': 150, 'max_depth': 6, 'learning_rate': 0.011240768803005551, 'min_child_weight': 10, 'subsample': 0.7035119926400067, 'colsample_bytree': 0.831261142176991, 'gamma': 1.5585553804470549, 'reg_alpha': 0.039841905944346875, 'reg_lambda': 0.22460390897586935, 'scale_pos_weight': 1.369708911051054}. Best is trial 3 with value: 0.69639076306712.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:01:41,810] Trial 5 finished with value: 0.6587104199299965 and parameters: {'n_estimators': 800, 'max_depth': 8, 'learning_rate': 0.24420460844911424, 'min_child_weight': 9, 'subsample': 0.8391599915244341, 'colsample_bytree': 0.9609371175115584, 'gamma': 0.4424625102595975, 'reg_alpha': 0.0009548041810464163, 'reg_lambda': 0.001565034538003576, 'scale_pos_weight': 1.6506606615265287}. Best is trial 3 with value: 0.69639076306712.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:01:46,558] Trial 6 finished with value: 0.6840198377545319 and parameters: {'n_estimators': 350, 'max_depth': 4, 'learning_rate': 0.16755052359850303, 'min_child_weight': 4, 'subsample': 0.7123738038749523, 'colsample_bytree': 0.7713480415791243, 'gamma': 0.7046211248738132, 'reg_alpha': 1.025616274847307, 'reg_lambda': 0.002092399245066083, 'scale_pos_weight': 2.9737738732010346}. Best is trial 3 with value: 0.69639076306712.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:01:53,778] Trial 7 finished with value: 0.6915718785887929 and parameters: {'n_estimators': 650, 'max_depth': 3, 'learning_rate': 0.010189592979395137, 'min_child_weight': 9, 'subsample': 0.8827429375390468, 'colsample_bytree': 0.8645035840204937, 'gamma': 3.8563517334297286, 'reg_alpha': 0.00023454342277260534, 'reg_lambda': 0.034815437009482725, 'scale_pos_weight': 1.2317381190502594}. Best is trial 3 with value: 0.69639076306712.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:02:02,945] Trial 8 finished with value: 0.6971891795735881 and parameters: {'n_estimators': 700, 'max_depth': 7, 'learning_rate': 0.030816017044468066, 'min_child_weight': 1, 'subsample': 0.7243929286862649, 'colsample_bytree': 0.6625916610133735, 'gamma': 3.64803089169032, 'reg_alpha': 0.1540945776288154, 'reg_lambda': 6.545285853960302, 'scale_pos_weight': 1.9444298503238986}. Best is trial 8 with value: 0.6971891795735881.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:02:05,810] Trial 9 finished with value: 0.6911155267230711 and parameters: {'n_estimators': 150, 'max_depth': 8, 'learning_rate': 0.13297554090738672, 'min_child_weight': 6, 'subsample': 0.9083868719818244, 'colsample_bytree': 0.7468977981821954, 'gamma': 2.6136641469099704, 'reg_alpha': 0.013731092468240296, 'reg_lambda': 0.0012862590001032788, 'scale_pos_weight': 1.215782853986609}. Best is trial 8 with value: 0.6971891795735881.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:02:14,239] Trial 10 finished with value: 0.6888588262275164 and parameters: {'n_estimators': 750, 'max_depth': 5, 'learning_rate': 0.030950865935951418, 'min_child_weight': 8, 'subsample': 0.7566522490201855, 'colsample_bytree': 0.7788210154930302, 'gamma': 3.1818864890574194, 'reg_alpha': 0.2133922915437601, 'reg_lambda': 7.523825655513485, 'scale_pos_weight': 1.2221595433343617}. Best is trial 8 with value: 0.6971891795735881.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:02:20,840] Trial 11 finished with value: 0.6814148028709056 and parameters: {'n_estimators': 600, 'max_depth': 3, 'learning_rate': 0.011136125856257277, 'min_child_weight': 3, 'subsample': 0.9152935166285485, 'colsample_bytree': 0.8506779674239556, 'gamma': 0.21338385580562536, 'reg_alpha': 0.02550855686965221, 'reg_lambda': 0.11129561240961297, 'scale_pos_weight': 2.1993499878741742}. Best is trial 8 with value: 0.6971891795735881.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:02:29,180] Trial 12 finished with value: 0.6933591055437176 and parameters: {'n_estimators': 650, 'max_depth': 4, 'learning_rate': 0.013430569676232226, 'min_child_weight': 10, 'subsample': 0.7964863549995089, 'colsample_bytree': 0.7522333298040985, 'gamma': 1.4322570172753086, 'reg_alpha': 0.3275776618849284, 'reg_lambda': 2.5665385817671815, 'scale_pos_weight': 1.9920418184028188}. Best is trial 8 with value: 0.6971891795735881.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:02:34,911] Trial 13 finished with value: 0.6987376866414547 and parameters: {'n_estimators': 550, 'max_depth': 3, 'learning_rate': 0.036171394128506416, 'min_child_weight': 10, 'subsample': 0.9819624073075668, 'colsample_bytree': 0.9669438829380244, 'gamma': 3.230818571927179, 'reg_alpha': 0.0015733704877101936, 'reg_lambda': 3.819218697250491, 'scale_pos_weight': 1.6764585926620752}. Best is trial 13 with value: 0.6987376866414547.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:02:43,594] Trial 14 finished with value: 0.6948620753714942 and parameters: {'n_estimators': 750, 'max_depth': 9, 'learning_rate': 0.02523160093968462, 'min_child_weight': 7, 'subsample': 0.9039388172081382, 'colsample_bytree': 0.7307694019061102, 'gamma': 4.511223176021807, 'reg_alpha': 0.058400878387865916, 'reg_lambda': 8.270510122674182, 'scale_pos_weight': 1.9731712607447012}. Best is trial 13 with value: 0.6987376866414547.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:02:50,442] Trial 15 finished with value: 0.7070521725343173 and parameters: {'n_estimators': 650, 'max_depth': 3, 'learning_rate': 0.018716052108351085, 'min_child_weight': 2, 'subsample': 0.8196859496155866, 'colsample_bytree': 0.7810490497882538, 'gamma': 4.183466977940077, 'reg_alpha': 0.1504379218330471, 'reg_lambda': 0.8886224155612514, 'scale_pos_weight': 1.6022164841931859}. Best is trial 15 with value: 0.7070521725343173.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:02:55,769] Trial 16 finished with value: 0.6917990265752729 and parameters: {'n_estimators': 550, 'max_depth': 2, 'learning_rate': 0.07713063678641012, 'min_child_weight': 2, 'subsample': 0.8675736564669551, 'colsample_bytree': 0.9177067066396144, 'gamma': 3.727824933092804, 'reg_alpha': 0.0027543636811288336, 'reg_lambda': 4.040167035984566, 'scale_pos_weight': 2.073486176181786}. Best is trial 15 with value: 0.7070521725343173.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:03:02,614] Trial 17 finished with value: 0.707433711833063 and parameters: {'n_estimators': 650, 'max_depth': 3, 'learning_rate': 0.04910968540298613, 'min_child_weight': 1, 'subsample': 0.9509473154911338, 'colsample_bytree': 0.9292787526730006, 'gamma': 2.6831160826718943, 'reg_alpha': 0.00012296754951486962, 'reg_lambda': 1.9348417382291172, 'scale_pos_weight': 1.371350217807353}. Best is trial 17 with value: 0.707433711833063.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:03:09,851] Trial 18 finished with value: 0.7084807424089418 and parameters: {'n_estimators': 650, 'max_depth': 3, 'learning_rate': 0.05753681772670507, 'min_child_weight': 1, 'subsample': 0.8723547786304661, 'colsample_bytree': 0.9523365934696945, 'gamma': 2.0233564956026777, 'reg_alpha': 0.0004960302795618614, 'reg_lambda': 3.2156074693113483, 'scale_pos_weight': 1.387929632047938}. Best is trial 18 with value: 0.7084807424089418.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:03:16,886] Trial 19 finished with value: 0.7005231016428237 and parameters: {'n_estimators': 700, 'max_depth': 4, 'learning_rate': 0.07371258441626462, 'min_child_weight': 1, 'subsample': 0.8900071323537395, 'colsample_bytree': 0.8966102951720447, 'gamma': 2.2150219102391313, 'reg_alpha': 0.00015565825052350052, 'reg_lambda': 1.5851051205814557, 'scale_pos_weight': 1.0592604995040868}. Best is trial 18 with value: 0.7084807424089418.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:03:22,557] Trial 20 finished with value: 0.7026866155000703 and parameters: {'n_estimators': 600, 'max_depth': 4, 'learning_rate': 0.09311662632681636, 'min_child_weight': 1, 'subsample': 0.8766460555508906, 'colsample_bytree': 0.972701015668312, 'gamma': 3.537649855191735, 'reg_alpha': 0.00010351475851791009, 'reg_lambda': 11.108217828754558, 'scale_pos_weight': 1.5333125297951506}. Best is trial 18 with value: 0.7084807424089418.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:03:28,691] Trial 21 finished with value: 0.7008365935869098 and parameters: {'n_estimators': 650, 'max_depth': 3, 'learning_rate': 0.105370779545784, 'min_child_weight': 2, 'subsample': 0.8873941722488619, 'colsample_bytree': 0.9250967252553299, 'gamma': 2.8480940621427155, 'reg_alpha': 0.0001048916108199983, 'reg_lambda': 0.40046946020840196, 'scale_pos_weight': 1.5634192709219692}. Best is trial 18 with value: 0.7084807424089418.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:03:36,269] Trial 22 finished with value: 0.7127914767504929 and parameters: {'n_estimators': 750, 'max_depth': 3, 'learning_rate': 0.0347336432034124, 'min_child_weight': 2, 'subsample': 0.9623294715330104, 'colsample_bytree': 0.9619062970943634, 'gamma': 2.702431033178114, 'reg_alpha': 0.0001950183828267918, 'reg_lambda': 6.0607346931568, 'scale_pos_weight': 1.250872097870687}. Best is trial 22 with value: 0.7127914767504929.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:03:44,504] Trial 23 finished with value: 0.6940717168442578 and parameters: {'n_estimators': 750, 'max_depth': 3, 'learning_rate': 0.01620026535528613, 'min_child_weight': 3, 'subsample': 0.933100051019451, 'colsample_bytree': 0.9670529038478997, 'gamma': 3.3163653373559665, 'reg_alpha': 0.00018775678266922622, 'reg_lambda': 2.6608219391538412, 'scale_pos_weight': 1.1321688428069794}. Best is trial 22 with value: 0.7127914767504929.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:03:50,787] Trial 24 finished with value: 0.6997345458016195 and parameters: {'n_estimators': 750, 'max_depth': 2, 'learning_rate': 0.0539630221395501, 'min_child_weight': 2, 'subsample': 0.9850166443793893, 'colsample_bytree': 0.9877852003588561, 'gamma': 3.8549040021668874, 'reg_alpha': 0.00012911799605279037, 'reg_lambda': 2.2870748744962115, 'scale_pos_weight': 1.2702733357782763}. Best is trial 22 with value: 0.7127914767504929.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:03:56,757] Trial 25 finished with value: 0.7047590495024536 and parameters: {'n_estimators': 700, 'max_depth': 5, 'learning_rate': 0.08277528354792738, 'min_child_weight': 2, 'subsample': 0.9829851600797926, 'colsample_bytree': 0.8693601836148439, 'gamma': 3.1108725800047052, 'reg_alpha': 0.00014419200480184142, 'reg_lambda': 8.334589705206728, 'scale_pos_weight': 1.412921840966411}. Best is trial 22 with value: 0.7127914767504929.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:04:04,783] Trial 26 finished with value: 0.6954903523535871 and parameters: {'n_estimators': 650, 'max_depth': 5, 'learning_rate': 0.05072199575610648, 'min_child_weight': 2, 'subsample': 0.8992504712887788, 'colsample_bytree': 0.9892768178628505, 'gamma': 2.1467513800705147, 'reg_alpha': 0.0004923192299893113, 'reg_lambda': 0.3972301177718791, 'scale_pos_weight': 1.1475854498952658}. Best is trial 22 with value: 0.7127914767504929.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:04:13,661] Trial 27 finished with value: 0.7061732913940025 and parameters: {'n_estimators': 750, 'max_depth': 4, 'learning_rate': 0.022631980739409283, 'min_child_weight': 4, 'subsample': 0.9602330065041793, 'colsample_bytree': 0.9682494533372537, 'gamma': 3.122539443184448, 'reg_alpha': 0.0013317946029990217, 'reg_lambda': 1.593839624612793, 'scale_pos_weight': 1.464325532218886}. Best is trial 22 with value: 0.7127914767504929.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:04:20,357] Trial 28 finished with value: 0.7001685650288416 and parameters: {'n_estimators': 650, 'max_depth': 3, 'learning_rate': 0.033030687579446355, 'min_child_weight': 3, 'subsample': 0.9751353390323753, 'colsample_bytree': 0.9890116742163031, 'gamma': 4.1258122684814404, 'reg_alpha': 0.0003035460567878395, 'reg_lambda': 4.382039375250464, 'scale_pos_weight': 1.8172034101974284}. Best is trial 22 with value: 0.7127914767504929.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:04:28,641] Trial 29 finished with value: 0.704984798072042 and parameters: {'n_estimators': 750, 'max_depth': 3, 'learning_rate': 0.026951123979069926, 'min_child_weight': 1, 'subsample': 0.8540343604963173, 'colsample_bytree': 0.9434614318917962, 'gamma': 2.51709393083044, 'reg_alpha': 0.00027533145019422546, 'reg_lambda': 1.672365871723824, 'scale_pos_weight': 1.764269995606154}. Best is trial 22 with value: 0.7127914767504929.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:04:36,222] Trial 30 finished with value: 0.7080328994150629 and parameters: {'n_estimators': 700, 'max_depth': 4, 'learning_rate': 0.05883394373156622, 'min_child_weight': 1, 'subsample': 0.912996719328293, 'colsample_bytree': 0.9830790491571536, 'gamma': 2.253863724287077, 'reg_alpha': 0.0003192415596623254, 'reg_lambda': 5.95819949372232, 'scale_pos_weight': 1.3028820724934431}. Best is trial 22 with value: 0.7127914767504929.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:04:43,029] Trial 31 finished with value: 0.6978430081202014 and parameters: {'n_estimators': 600, 'max_depth': 5, 'learning_rate': 0.04673227958139884, 'min_child_weight': 1, 'subsample': 0.9516211883579069, 'colsample_bytree': 0.9281485325672577, 'gamma': 2.5893339575566108, 'reg_alpha': 0.00017360985548379114, 'reg_lambda': 18.426699136985285, 'scale_pos_weight': 1.5510983658882986}. Best is trial 22 with value: 0.7127914767504929.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:04:49,878] Trial 32 finished with value: 0.7005507255788869 and parameters: {'n_estimators': 750, 'max_depth': 2, 'learning_rate': 0.03684709553283484, 'min_child_weight': 2, 'subsample': 0.9551637679832257, 'colsample_bytree': 0.977577653701148, 'gamma': 1.3784048059259932, 'reg_alpha': 0.00012253330227217176, 'reg_lambda': 5.912395349263188, 'scale_pos_weight': 1.08430560469091}. Best is trial 22 with value: 0.7127914767504929.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:04:57,052] Trial 33 finished with value: 0.7075169796513953 and parameters: {'n_estimators': 750, 'max_depth': 3, 'learning_rate': 0.048899360811512894, 'min_child_weight': 1, 'subsample': 0.9383928492190933, 'colsample_bytree': 0.963625559063489, 'gamma': 2.961513556562009, 'reg_alpha': 0.00022684451518433725, 'reg_lambda': 7.28130072209074, 'scale_pos_weight': 1.288119879283747}. Best is trial 22 with value: 0.7127914767504929.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:05:03,331] Trial 34 finished with value: 0.7028014698490604 and parameters: {'n_estimators': 600, 'max_depth': 3, 'learning_rate': 0.04661195850584219, 'min_child_weight': 3, 'subsample': 0.9640858003497426, 'colsample_bytree': 0.9869126694084956, 'gamma': 2.588647258758484, 'reg_alpha': 0.0012994307060252431, 'reg_lambda': 10.486432275205507, 'scale_pos_weight': 1.272151584019803}. Best is trial 22 with value: 0.7127914767504929.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:05:09,206] Trial 35 finished with value: 0.6958672354283602 and parameters: {'n_estimators': 650, 'max_depth': 2, 'learning_rate': 0.039492634136450176, 'min_child_weight': 2, 'subsample': 0.8973151825967843, 'colsample_bytree': 0.9201198173058039, 'gamma': 3.500494034379323, 'reg_alpha': 0.00028167700335044783, 'reg_lambda': 3.2287878068207716, 'scale_pos_weight': 1.0792566805713286}. Best is trial 22 with value: 0.7127914767504929.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:05:15,671] Trial 36 finished with value: 0.705293431032229 and parameters: {'n_estimators': 650, 'max_depth': 5, 'learning_rate': 0.09165638541189502, 'min_child_weight': 1, 'subsample': 0.9058848664614397, 'colsample_bytree': 0.9965589935287079, 'gamma': 2.648282676039384, 'reg_alpha': 0.00014601308833568568, 'reg_lambda': 7.939966088710214, 'scale_pos_weight': 1.4263544898010452}. Best is trial 22 with value: 0.7127914767504929.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:05:22,711] Trial 37 finished with value: 0.7131703592316931 and parameters: {'n_estimators': 650, 'max_depth': 3, 'learning_rate': 0.04112035080491694, 'min_child_weight': 1, 'subsample': 0.9455520835632656, 'colsample_bytree': 0.920555932808492, 'gamma': 2.6716980528236336, 'reg_alpha': 0.0005300868857454632, 'reg_lambda': 1.3302541205524063, 'scale_pos_weight': 1.684812358171659}. Best is trial 37 with value: 0.7131703592316931.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:05:30,182] Trial 38 finished with value: 0.7032993398335077 and parameters: {'n_estimators': 650, 'max_depth': 3, 'learning_rate': 0.058480736211453756, 'min_child_weight': 1, 'subsample': 0.8389373681112486, 'colsample_bytree': 0.9873670336120483, 'gamma': 1.7164822785963563, 'reg_alpha': 0.0014588412902307656, 'reg_lambda': 13.80704693385951, 'scale_pos_weight': 1.3381624787502362}. Best is trial 37 with value: 0.7131703592316931.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:05:37,212] Trial 39 finished with value: 0.69859597295694 and parameters: {'n_estimators': 750, 'max_depth': 3, 'learning_rate': 0.0713200825763049, 'min_child_weight': 1, 'subsample': 0.9530638515221455, 'colsample_bytree': 0.9070931811179135, 'gamma': 1.9745298728837768, 'reg_alpha': 0.00045523083526745496, 'reg_lambda': 2.7992649114361314, 'scale_pos_weight': 1.0436785911917343}. Best is trial 37 with value: 0.7131703592316931.
Cargando: ../data/train_clean_lemma_es.csv

[I 2026-09-21 17:06:53,305] A new study created in memory with name: xgboost_cu

[I 2026-09-21 17:06:53,301] Trial 49 finished with value: 0.6973840396836872 and parameters: {'n_estimators': 700, 'max_depth': 3, 'learning_rate': 0.05907259191180324, 'min_child_weight': 1, 'subsample': 0.9322758822319247, 'colsample_bytree': 0.9714035202269057, 'gamma': 2.945903949338609, 'reg_alpha': 0.00026739323602407793, 'reg_lambda': 2.3821212189835905, 'scale_pos_weight': 1.0558854174620789}. Best is trial 37 with value: 0.7131703592316931.


Mejor F1-Macro CV: 0.7132

Mejores hiperparámetros:
  n_estimators: 650
  max_depth: 3
  learning_rate: 0.04112035080491694
  min_child_weight: 1
  subsample: 0.9455520835632656
  colsample_bytree: 0.920555932808492
  gamma: 2.6716980528236336
  reg_alpha: 0.0005300868857454632
  reg_lambda: 1.3302541205524063
  scale_pos_weight: 1.684812358171659


======================================================================
OPTUNA - VARIANTE CU
Preprocesamiento seleccionado: stem
======================================================================

  0%|          | 0/50 [00:00<?, ?it/s]

Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:07:04,219] Trial 0 finished with value: 0.6079451059418257 and parameters: {'n_estimators': 350, 'max_depth': 10, 'learning_rate': 0.1205712628744377, 'min_child_weight': 6, 'subsample': 0.6624074561769746, 'colsample_bytree': 0.5779972601681014, 'gamma': 0.2904180608409973, 'reg_alpha': 2.1423021757741068, 'reg_lambda': 0.3849583075868115, 'scale_pos_weight': 2.416145155592091}. Best is trial 0 with value: 0.6079451059418257.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:07:08,347] Trial 1 finished with value: 0.6234615970433481 and parameters: {'n_estimators': 100, 'max_depth': 10, 'learning_rate': 0.16967533607196555, 'min_child_weight': 3, 'subsample': 0.6727299868828402, 'colsample_bytree': 0.5917022549267169, 'gamma': 1.5212112147976886, 'reg_alpha': 0.042051564509138675, 'reg_lambda': 0.07207895500630218, 'scale_pos_weight': 1.5824582803960838}. Best is trial 1 with value: 0.6234615970433481.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:07:15,034] Trial 2 finished with value: 0.6432473628604695 and parameters: {'n_estimators': 550, 'max_depth': 3, 'learning_rate': 0.027010527749605478, 'min_child_weight': 4, 'subsample': 0.7824279936868144, 'colsample_bytree': 0.8925879806965068, 'gamma': 0.9983689107917987, 'reg_alpha': 0.03725393839578886, 'reg_lambda': 0.35317733939252866, 'scale_pos_weight': 1.0929008254399954}. Best is trial 2 with value: 0.6432473628604695.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:07:21,848] Trial 3 finished with value: 0.6350851824727746 and parameters: {'n_estimators': 550, 'max_depth': 3, 'learning_rate': 0.012476394272569451, 'min_child_weight': 10, 'subsample': 0.9862528132298237, 'colsample_bytree': 0.9041986740582306, 'gamma': 1.5230688458668533, 'reg_alpha': 0.0003078651783619622, 'reg_lambda': 0.8768125777016167, 'scale_pos_weight': 1.8803049874792026}. Best is trial 2 with value: 0.6432473628604695.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:07:26,061] Trial 4 finished with value: 0.6140912908935807 and parameters: {'n_estimators': 150, 'max_depth': 6, 'learning_rate': 0.011240768803005551, 'min_child_weight': 10, 'subsample': 0.7035119926400067, 'colsample_bytree': 0.831261142176991, 'gamma': 1.5585553804470549, 'reg_alpha': 0.039841905944346875, 'reg_lambda': 0.22460390897586935, 'scale_pos_weight': 1.369708911051054}. Best is trial 2 with value: 0.6432473628604695.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:07:39,337] Trial 5 finished with value: 0.5961376444998068 and parameters: {'n_estimators': 800, 'max_depth': 8, 'learning_rate': 0.24420460844911424, 'min_child_weight': 9, 'subsample': 0.8391599915244341, 'colsample_bytree': 0.9609371175115584, 'gamma': 0.4424625102595975, 'reg_alpha': 0.0009548041810464163, 'reg_lambda': 0.001565034538003576, 'scale_pos_weight': 1.6506606615265287}. Best is trial 2 with value: 0.6432473628604695.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:07:44,611] Trial 6 finished with value: 0.6237549439566188 and parameters: {'n_estimators': 350, 'max_depth': 4, 'learning_rate': 0.16755052359850303, 'min_child_weight': 4, 'subsample': 0.7123738038749523, 'colsample_bytree': 0.7713480415791243, 'gamma': 0.7046211248738132, 'reg_alpha': 1.025616274847307, 'reg_lambda': 0.002092399245066083, 'scale_pos_weight': 2.9737738732010346}. Best is trial 2 with value: 0.6432473628604695.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:07:52,692] Trial 7 finished with value: 0.6170641334733522 and parameters: {'n_estimators': 650, 'max_depth': 3, 'learning_rate': 0.010189592979395137, 'min_child_weight': 9, 'subsample': 0.8827429375390468, 'colsample_bytree': 0.8645035840204937, 'gamma': 3.8563517334297286, 'reg_alpha': 0.00023454342277260534, 'reg_lambda': 0.034815437009482725, 'scale_pos_weight': 1.2317381190502594}. Best is trial 2 with value: 0.6432473628604695.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:08:04,292] Trial 8 finished with value: 0.641912361274228 and parameters: {'n_estimators': 700, 'max_depth': 7, 'learning_rate': 0.030816017044468066, 'min_child_weight': 1, 'subsample': 0.7243929286862649, 'colsample_bytree': 0.6625916610133735, 'gamma': 3.64803089169032, 'reg_alpha': 0.1540945776288154, 'reg_lambda': 6.545285853960302, 'scale_pos_weight': 1.9444298503238986}. Best is trial 2 with value: 0.6432473628604695.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:08:07,707] Trial 9 finished with value: 0.6280878524011968 and parameters: {'n_estimators': 150, 'max_depth': 8, 'learning_rate': 0.13297554090738672, 'min_child_weight': 6, 'subsample': 0.9083868719818244, 'colsample_bytree': 0.7468977981821954, 'gamma': 2.6136641469099704, 'reg_alpha': 0.013731092468240296, 'reg_lambda': 0.0012862590001032788, 'scale_pos_weight': 1.215782853986609}. Best is trial 2 with value: 0.6432473628604695.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:08:17,521] Trial 10 finished with value: 0.6237213734182147 and parameters: {'n_estimators': 750, 'max_depth': 4, 'learning_rate': 0.030413593449347513, 'min_child_weight': 8, 'subsample': 0.7688495088698033, 'colsample_bytree': 0.8248775313455099, 'gamma': 2.6979397444927864, 'reg_alpha': 0.1437889084306099, 'reg_lambda': 6.165295307613112, 'scale_pos_weight': 1.1616054026388245}. Best is trial 2 with value: 0.6432473628604695.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:08:24,752] Trial 11 finished with value: 0.625697906587764 and parameters: {'n_estimators': 750, 'max_depth': 8, 'learning_rate': 0.04358506703109434, 'min_child_weight': 2, 'subsample': 0.8191823341511698, 'colsample_bytree': 0.7243876447557895, 'gamma': 3.88061802158116, 'reg_alpha': 4.397240305425342, 'reg_lambda': 16.61524139820008, 'scale_pos_weight': 1.439065161704261}. Best is trial 2 with value: 0.6432473628604695.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:08:33,710] Trial 12 finished with value: 0.6444037359674901 and parameters: {'n_estimators': 500, 'max_depth': 5, 'learning_rate': 0.02184979749493093, 'min_child_weight': 1, 'subsample': 0.8619788590356126, 'colsample_bytree': 0.6509156082426414, 'gamma': 2.223459361284214, 'reg_alpha': 0.0662787251194429, 'reg_lambda': 8.16610837589296, 'scale_pos_weight': 1.6623255992884014}. Best is trial 12 with value: 0.6444037359674901.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:08:42,830] Trial 13 finished with value: 0.6388727840603893 and parameters: {'n_estimators': 600, 'max_depth': 4, 'learning_rate': 0.01663774476308199, 'min_child_weight': 2, 'subsample': 0.8163781049906638, 'colsample_bytree': 0.7660858008072352, 'gamma': 2.0853395019395564, 'reg_alpha': 0.0012342024184595886, 'reg_lambda': 9.576966729325711, 'scale_pos_weight': 1.8665485309452532}. Best is trial 12 with value: 0.6444037359674901.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:08:51,493] Trial 14 finished with value: 0.6480089713411441 and parameters: {'n_estimators': 500, 'max_depth': 5, 'learning_rate': 0.036674949022846966, 'min_child_weight': 1, 'subsample': 0.8653903499988301, 'colsample_bytree': 0.8650240730975516, 'gamma': 1.5441532361979629, 'reg_alpha': 0.014495618975650881, 'reg_lambda': 0.47300939516617085, 'scale_pos_weight': 1.0079678136853019}. Best is trial 14 with value: 0.6480089713411441.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:08:57,801] Trial 15 finished with value: 0.6518258401571718 and parameters: {'n_estimators': 500, 'max_depth': 3, 'learning_rate': 0.015665240513689317, 'min_child_weight': 1, 'subsample': 0.8765617676767536, 'colsample_bytree': 0.7519749119781811, 'gamma': 3.154504366261185, 'reg_alpha': 0.1035608700759894, 'reg_lambda': 0.7027453364418086, 'scale_pos_weight': 1.3988806958117315}. Best is trial 15 with value: 0.6518258401571718.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:09:04,194] Trial 16 finished with value: 0.6499927084202038 and parameters: {'n_estimators': 400, 'max_depth': 4, 'learning_rate': 0.016085278738661158, 'min_child_weight': 1, 'subsample': 0.8885007273631045, 'colsample_bytree': 0.762434551474467, 'gamma': 2.227534908432815, 'reg_alpha': 0.675390119207931, 'reg_lambda': 0.02204969273510592, 'scale_pos_weight': 1.4152015232896735}. Best is trial 15 with value: 0.6518258401571718.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:09:09,990] Trial 17 finished with value: 0.6683638541937067 and parameters: {'n_estimators': 450, 'max_depth': 3, 'learning_rate': 0.03154838798956611, 'min_child_weight': 1, 'subsample': 0.7859201240583127, 'colsample_bytree': 0.825427700298568, 'gamma': 2.796169463111169, 'reg_alpha': 0.013918300303802592, 'reg_lambda': 0.28830895088514297, 'scale_pos_weight': 1.7041811146914616}. Best is trial 17 with value: 0.6683638541937067.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:09:16,539] Trial 18 finished with value: 0.662400525688862 and parameters: {'n_estimators': 500, 'max_depth': 3, 'learning_rate': 0.03887448235646187, 'min_child_weight': 1, 'subsample': 0.7691542762612572, 'colsample_bytree': 0.9119890577455709, 'gamma': 2.2149593239946066, 'reg_alpha': 0.0016381957936233208, 'reg_lambda': 0.8870815280359704, 'scale_pos_weight': 1.599980981412292}. Best is trial 17 with value: 0.6683638541937067.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:09:24,977] Trial 19 finished with value: 0.6503409524028184 and parameters: {'n_estimators': 600, 'max_depth': 4, 'learning_rate': 0.05262107972110246, 'min_child_weight': 1, 'subsample': 0.8057333353582744, 'colsample_bytree': 0.8751281972486025, 'gamma': 2.3781029304896957, 'reg_alpha': 0.0001947679474429181, 'reg_lambda': 0.6589696323460442, 'scale_pos_weight': 1.0953357719269468}. Best is trial 17 with value: 0.6683638541937067.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:09:31,332] Trial 20 finished with value: 0.6376248132911029 and parameters: {'n_estimators': 500, 'max_depth': 4, 'learning_rate': 0.11385992409046569, 'min_child_weight': 2, 'subsample': 0.8572963037231478, 'colsample_bytree': 0.9250744612741566, 'gamma': 2.8034071396251194, 'reg_alpha': 0.0029570818688656546, 'reg_lambda': 0.34965387878162046, 'scale_pos_weight': 1.6003964499273489}. Best is trial 17 with value: 0.6683638541937067.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:09:38,686] Trial 21 finished with value: 0.660292454325081 and parameters: {'n_estimators': 500, 'max_depth': 4, 'learning_rate': 0.018395139111543425, 'min_child_weight': 1, 'subsample': 0.8691571485343861, 'colsample_bytree': 0.7686137046075233, 'gamma': 3.372346607443202, 'reg_alpha': 0.008578542051626638, 'reg_lambda': 0.550947104138183, 'scale_pos_weight': 1.4105931137000567}. Best is trial 17 with value: 0.6683638541937067.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:09:46,410] Trial 22 finished with value: 0.660128627813743 and parameters: {'n_estimators': 600, 'max_depth': 3, 'learning_rate': 0.030019895074382782, 'min_child_weight': 2, 'subsample': 0.8269294853074134, 'colsample_bytree': 0.9633155486422451, 'gamma': 2.2758291542418854, 'reg_alpha': 0.0004997574995298852, 'reg_lambda': 3.7793865472137496, 'scale_pos_weight': 1.3892158577342748}. Best is trial 17 with value: 0.6683638541937067.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:09:54,484] Trial 23 finished with value: 0.648114921248267 and parameters: {'n_estimators': 550, 'max_depth': 4, 'learning_rate': 0.01205980433978525, 'min_child_weight': 2, 'subsample': 0.8680304766963218, 'colsample_bytree': 0.8510820919780853, 'gamma': 3.8948091875296837, 'reg_alpha': 0.0012038049722183537, 'reg_lambda': 0.4304501586701217, 'scale_pos_weight': 1.187518566338973}. Best is trial 17 with value: 0.6683638541937067.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:09:59,969] Trial 24 finished with value: 0.6505825166978696 and parameters: {'n_estimators': 350, 'max_depth': 4, 'learning_rate': 0.017339984040669963, 'min_child_weight': 2, 'subsample': 0.9160780347139856, 'colsample_bytree': 0.735673506708534, 'gamma': 3.071549564912421, 'reg_alpha': 0.023109269942402977, 'reg_lambda': 1.207717255008363, 'scale_pos_weight': 1.7057669276983793}. Best is trial 17 with value: 0.6683638541937067.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:10:09,716] Trial 25 finished with value: 0.6560682650732905 and parameters: {'n_estimators': 700, 'max_depth': 4, 'learning_rate': 0.03413230682196225, 'min_child_weight': 2, 'subsample': 0.7794369744637609, 'colsample_bytree': 0.8510335246440655, 'gamma': 2.0081538630801727, 'reg_alpha': 0.0010082262302169305, 'reg_lambda': 1.271553312025051, 'scale_pos_weight': 1.8257237139563436}. Best is trial 17 with value: 0.6683638541937067.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:10:14,043] Trial 26 finished with value: 0.6606352561576572 and parameters: {'n_estimators': 300, 'max_depth': 3, 'learning_rate': 0.05867657700262362, 'min_child_weight': 1, 'subsample': 0.7082703773849802, 'colsample_bytree': 0.9531283172362375, 'gamma': 2.391704836940327, 'reg_alpha': 0.005756450367261148, 'reg_lambda': 0.37091951423484554, 'scale_pos_weight': 1.5421789205057763}. Best is trial 17 with value: 0.6683638541937067.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:10:20,224] Trial 27 finished with value: 0.6576320294963702 and parameters: {'n_estimators': 400, 'max_depth': 4, 'learning_rate': 0.03768408927837873, 'min_child_weight': 1, 'subsample': 0.7043730904280328, 'colsample_bytree': 0.8421535686090353, 'gamma': 1.6182000344763505, 'reg_alpha': 0.005180768816755745, 'reg_lambda': 0.042644038526689944, 'scale_pos_weight': 1.5119037829564164}. Best is trial 17 with value: 0.6683638541937067.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:10:26,134] Trial 28 finished with value: 0.6613051274473951 and parameters: {'n_estimators': 400, 'max_depth': 4, 'learning_rate': 0.018505271491742373, 'min_child_weight': 2, 'subsample': 0.7935576894179922, 'colsample_bytree': 0.7252061767344138, 'gamma': 2.2196215047799353, 'reg_alpha': 0.005791184664920188, 'reg_lambda': 0.2557755711331805, 'scale_pos_weight': 1.963172181374992}. Best is trial 17 with value: 0.6683638541937067.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:10:33,469] Trial 29 finished with value: 0.6430706401278572 and parameters: {'n_estimators': 500, 'max_depth': 4, 'learning_rate': 0.04459745317824759, 'min_child_weight': 1, 'subsample': 0.7035850537289294, 'colsample_bytree': 0.8744356640162795, 'gamma': 2.1876731776466047, 'reg_alpha': 0.0012702136184795452, 'reg_lambda': 0.12228933793598144, 'scale_pos_weight': 1.9528059448876811}. Best is trial 17 with value: 0.6683638541937067.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:10:41,371] Trial 30 finished with value: 0.6577782319198324 and parameters: {'n_estimators': 500, 'max_depth': 4, 'learning_rate': 0.03890868147753847, 'min_child_weight': 1, 'subsample': 0.773655808412581, 'colsample_bytree': 0.9479077252044481, 'gamma': 2.361737483198673, 'reg_alpha': 0.006725240326317589, 'reg_lambda': 1.5152330502198597, 'scale_pos_weight': 1.5359860058813357}. Best is trial 17 with value: 0.6683638541937067.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:10:47,218] Trial 31 finished with value: 0.6602603114595217 and parameters: {'n_estimators': 300, 'max_depth': 5, 'learning_rate': 0.010379746603723879, 'min_child_weight': 2, 'subsample': 0.7666240689339034, 'colsample_bytree': 0.6781026326452355, 'gamma': 2.058532696705072, 'reg_alpha': 0.014410768211005119, 'reg_lambda': 0.19619268202455847, 'scale_pos_weight': 2.0444036512356996}. Best is trial 17 with value: 0.6683638541937067.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:10:53,003] Trial 32 finished with value: 0.6561374188753775 and parameters: {'n_estimators': 400, 'max_depth': 4, 'learning_rate': 0.05136173335122571, 'min_child_weight': 2, 'subsample': 0.7814026548709578, 'colsample_bytree': 0.8002203634290965, 'gamma': 3.2701432683950267, 'reg_alpha': 0.0018636013316281445, 'reg_lambda': 0.4851729801566544, 'scale_pos_weight': 1.9759248388057953}. Best is trial 17 with value: 0.6683638541937067.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:10:57,201] Trial 33 finished with value: 0.6560034460887922 and parameters: {'n_estimators': 350, 'max_depth': 2, 'learning_rate': 0.057720009711863966, 'min_child_weight': 1, 'subsample': 0.7140159221581615, 'colsample_bytree': 0.9981144304310097, 'gamma': 2.098906355335179, 'reg_alpha': 0.043503240645900984, 'reg_lambda': 0.4847760133550785, 'scale_pos_weight': 1.8456797355374712}. Best is trial 17 with value: 0.6683638541937067.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:11:01,615] Trial 34 finished with value: 0.6561106588462999 and parameters: {'n_estimators': 400, 'max_depth': 2, 'learning_rate': 0.029298964662839537, 'min_child_weight': 2, 'subsample': 0.7664972824006283, 'colsample_bytree': 0.881251961386844, 'gamma': 3.1895018254025804, 'reg_alpha': 0.0033614552453400132, 'reg_lambda': 0.2794418684824112, 'scale_pos_weight': 1.6172011409971871}. Best is trial 17 with value: 0.6683638541937067.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:11:08,077] Trial 35 finished with value: 0.6621677735973576 and parameters: {'n_estimators': 400, 'max_depth': 4, 'learning_rate': 0.022256746099657342, 'min_child_weight': 1, 'subsample': 0.7287642060958115, 'colsample_bytree': 0.8698449259538155, 'gamma': 2.0267604099757364, 'reg_alpha': 0.002212168150477042, 'reg_lambda': 0.12804506714363545, 'scale_pos_weight': 1.728102529567104}. Best is trial 17 with value: 0.6683638541937067.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:11:15,442] Trial 36 finished with value: 0.6509666529347167 and parameters: {'n_estimators': 600, 'max_depth': 3, 'learning_rate': 0.03768121078476325, 'min_child_weight': 2, 'subsample': 0.7816151619154686, 'colsample_bytree': 0.9224164324157897, 'gamma': 2.536651873149054, 'reg_alpha': 0.00012710641776789104, 'reg_lambda': 0.634801809580207, 'scale_pos_weight': 1.6905870877841038}. Best is trial 17 with value: 0.6683638541937067.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:11:21,296] Trial 37 finished with value: 0.657055763323747 and parameters: {'n_estimators': 450, 'max_depth': 3, 'learning_rate': 0.04586754066619767, 'min_child_weight': 1, 'subsample': 0.7798026321013174, 'colsample_bytree': 0.88905949897585, 'gamma': 2.1903524700142736, 'reg_alpha': 0.0021985330472708156, 'reg_lambda': 0.2579864664234384, 'scale_pos_weight': 1.991360710844977}. Best is trial 17 with value: 0.6683638541937067.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:11:27,555] Trial 38 finished with value: 0.6550750220647222 and parameters: {'n_estimators': 400, 'max_depth': 4, 'learning_rate': 0.03409722674994124, 'min_child_weight': 1, 'subsample': 0.6747608780064638, 'colsample_bytree': 0.8357273106850256, 'gamma': 2.175887162722687, 'reg_alpha': 0.0043733221239180145, 'reg_lambda': 0.3926559415000159, 'scale_pos_weight': 2.0362827079630392}. Best is trial 17 with value: 0.6683638541937067.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:11:35,050] Trial 39 finished with value: 0.6632631534116564 and parameters: {'n_estimators': 500, 'max_depth': 4, 'learning_rate': 0.02267710625248703, 'min_child_weight': 2, 'subsample': 0.768305459438252, 'colsample_bytree': 0.9133955168186407, 'gamma': 3.398484510039582, 'reg_alpha': 0.004850687397536632, 'reg_lambda': 0.21119746295282996, 'scale_pos_weight': 1.9167345059882408}. Best is trial 17 with value: 0.6683638541937067.
Cargando: ../data/train_clean_stem_cu.csv

======================================================================
TOP 10 TRIALS - MX
======================================================================

,number,value,params_colsample_bytree,params_gamma,params_learning_rate,params_max_depth,params_min_child_weight,params_n_estimators,params_reg_alpha,params_reg_lambda,params_scale_pos_weight,params_subsample
42,42,0.621768,0.757305,4.566597,0.046809,6,1,550,0.002033,0.441521,1.707239,0.626316
43,43,0.617502,0.772791,3.801343,0.030271,6,2,600,0.030038,0.645385,1.739864,0.670964
18,18,0.615537,0.773250,2.036696,0.061588,4,1,650,0.017141,1.003253,1.758781,0.673158
47,47,0.615258,0.726191,4.984074,0.055319,7,1,700,0.000877,0.723884,1.718858,0.623571
39,39,0.614059,0.696572,4.197266,0.075626,6,1,550,0.043187,0.123131,1.963329,0.640018
44,44,0.613553,0.720087,4.092680,0.051367,7,1,550,0.002593,0.187889,1.841414,0.653529
49,49,0.613354,0.676400,4.498098,0.052994,7,2,750,0.001165,0.153434,1.752527,0.661084
48,48,0.610857,0.723241,4.314048,0.047512,5,1,600,0.001030,1.365863,1.521557,0.648010
45,45,0.609553,0.820137,4.180037,0.061119,6,2,550,0.000589,0.922204,1.623194,0.611632
41,41,0.609113,0.754832,4.672825,0.058445,5,2,600,0.007031,0.538749,2.010855,0.633512

======================================================================
TOP 10 TRIALS - ES
======================================================================

,number,value,params_colsample_bytree,params_gamma,params_learning_rate,params_max_depth,params_min_child_weight,params_n_estimators,params_reg_alpha,params_reg_lambda,params_scale_pos_weight,params_subsample
37,37,0.713170,0.920556,2.671698,0.041120,3,1,650,0.000530,1.330254,1.684812,0.945552
22,22,0.712791,0.961906,2.702431,0.034734,3,2,750,0.000195,6.060735,1.250872,0.962329
44,44,0.709161,0.905830,2.681437,0.053654,4,1,700,0.000500,2.313400,1.462256,0.932274
18,18,0.708481,0.952337,2.023356,0.057537,3,1,650,0.000496,3.215607,1.387930,0.872355
46,46,0.708111,0.991349,1.726325,0.050774,4,2,700,0.000841,5.502342,1.547377,0.911112
30,30,0.708033,0.983079,2.253864,0.058834,4,1,700,0.000319,5.958199,1.302882,0.912997
33,33,0.707517,0.963626,2.961514,0.048899,3,1,750,0.000227,7.281301,1.288120,0.938393
17,17,0.707434,0.929279,2.683116,0.049110,3,1,650,0.000123,1.934842,1.371350,0.950947
15,15,0.707052,0.781049,4.183467,0.018716,3,2,650,0.150438,0.888622,1.602216,0.819686
41,41,0.706341,0.947265,1.317132,0.049496,4,1,700,0.000321,6.087418,1.389691,0.880241

======================================================================
TOP 10 TRIALS - CU
======================================================================

,number,value,params_colsample_bytree,params_gamma,params_learning_rate,params_max_depth,params_min_child_weight,params_n_estimators,params_reg_alpha,params_reg_lambda,params_scale_pos_weight,params_subsample
17,17,0.668364,0.825428,2.796169,0.031548,3,1,450,0.013918,0.288309,1.704181,0.785920
42,42,0.666743,0.862842,2.453716,0.029014,3,1,450,0.002753,0.118419,1.446029,0.809243
40,40,0.666620,0.872937,3.082857,0.023003,5,3,400,0.010726,0.109761,1.529572,0.782911
43,43,0.665199,0.849694,3.034163,0.021119,4,2,450,0.017518,0.294885,1.745953,0.758301
39,39,0.663263,0.913396,3.398485,0.022677,4,2,500,0.004851,0.211197,1.916735,0.768305
48,48,0.662639,0.852774,2.260878,0.031422,4,2,450,0.024005,0.262085,1.707629,0.767720
18,18,0.662401,0.911989,2.214959,0.038874,3,1,500,0.001638,0.887082,1.599981,0.769154
35,35,0.662168,0.869845,2.026760,0.022257,4,1,400,0.002212,0.128045,1.728103,0.728764
28,28,0.661305,0.725206,2.219622,0.018505,4,2,400,0.005791,0.255776,1.963172,0.793558
46,46,0.661087,0.846021,2.822249,0.017776,4,1,450,0.002967,0.265219,1.720500,0.786469

In [4]:
# ============================================================
# 11. SEGUNDA BÚSQUEDA OPTUNA REFINADA
# ============================================================

import optuna
import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score
from xgboost import XGBClassifier


# ============================================================
# 11.1 RANGOS REFINADOS POR VARIANTE
# ============================================================

RANGOS_REFINADOS = {

    'mx': {
        'n_estimators': (450, 750),
        'max_depth': (4, 8),
        'learning_rate': (0.02, 0.09),
        'min_child_weight': (1, 3),
        'subsample': (0.60, 0.80),
        'colsample_bytree': (0.65, 0.85),
        'gamma': (2.0, 5.0),
        'reg_alpha': (1e-4, 0.10),
        'reg_lambda': (0.10, 2.0),
        'scale_pos_weight': (1.4, 2.1)
    },

    'es': {
        'n_estimators': (550, 800),
        'max_depth': (2, 5),
        'learning_rate': (0.02, 0.08),
        'min_child_weight': (1, 3),
        'subsample': (0.85, 1.00),
        'colsample_bytree': (0.85, 1.00),
        'gamma': (1.0, 4.0),
        'reg_alpha': (1e-4, 0.05),
        'reg_lambda': (0.50, 8.0),
        'scale_pos_weight': (1.2, 1.8)
    },

    'cu': {
        'n_estimators': (350, 550),
        'max_depth': (2, 5),
        'learning_rate': (0.015, 0.05),
        'min_child_weight': (1, 3),
        'subsample': (0.70, 0.90),
        'colsample_bytree': (0.75, 0.95),
        'gamma': (1.5, 4.0),
        'reg_alpha': (1e-4, 0.10),
        'reg_lambda': (0.05, 1.5),
        'scale_pos_weight': (1.3, 2.0)
    }
}


# ============================================================
# 11.2 FUNCIÓN OBJETIVO REFINADA
# ============================================================

def objective_xgboost_refinado(trial, variante):

    prep = MEJOR_PREP[variante]
    rango = RANGOS_REFINADOS[variante]

    df = cargar_train(
        variante=variante,
        prep=prep
    )

    X = df[
        ['MESSAGE_CLEAN'] + FEATURE_COLS
    ].copy()

    y = df['IS_IRONIC'].astype(int)

    X['MESSAGE_CLEAN'] = (
        X['MESSAGE_CLEAN']
        .fillna('')
        .astype(str)
    )

    X[FEATURE_COLS] = (
        X[FEATURE_COLS]
        .fillna(0)
    )

    params = {

        'n_estimators': trial.suggest_int(
            'n_estimators',
            rango['n_estimators'][0],
            rango['n_estimators'][1],
            step=25
        ),

        'max_depth': trial.suggest_int(
            'max_depth',
            rango['max_depth'][0],
            rango['max_depth'][1]
        ),

        'learning_rate': trial.suggest_float(
            'learning_rate',
            rango['learning_rate'][0],
            rango['learning_rate'][1],
            log=True
        ),

        'min_child_weight': trial.suggest_int(
            'min_child_weight',
            rango['min_child_weight'][0],
            rango['min_child_weight'][1]
        ),

        'subsample': trial.suggest_float(
            'subsample',
            rango['subsample'][0],
            rango['subsample'][1]
        ),

        'colsample_bytree': trial.suggest_float(
            'colsample_bytree',
            rango['colsample_bytree'][0],
            rango['colsample_bytree'][1]
        ),

        'gamma': trial.suggest_float(
            'gamma',
            rango['gamma'][0],
            rango['gamma'][1]
        ),

        'reg_alpha': trial.suggest_float(
            'reg_alpha',
            rango['reg_alpha'][0],
            rango['reg_alpha'][1],
            log=True
        ),

        'reg_lambda': trial.suggest_float(
            'reg_lambda',
            rango['reg_lambda'][0],
            rango['reg_lambda'][1],
            log=True
        ),

        'scale_pos_weight': trial.suggest_float(
            'scale_pos_weight',
            rango['scale_pos_weight'][0],
            rango['scale_pos_weight'][1]
        )
    }

    modelo = XGBClassifier(
        objective='binary:logistic',
        tree_method='hist',
        eval_metric='logloss',
        random_state=RANDOM_STATE,
        n_jobs=-1,
        **params
    )

    pipeline = Pipeline(
        steps=[
            ('features', crear_preprocesador()),
            ('xgb', modelo)
        ]
    )

    scores = cross_val_score(
        estimator=pipeline,
        X=X,
        y=y,
        cv=CV,
        scoring='f1_macro',
        n_jobs=1
    )

    return scores.mean()


# ============================================================
# 11.3 EJECUTAR SEGUNDA BÚSQUEDA
# ============================================================

N_TRIALS_REFINADOS = 40

studies_refinados = {}

for variante in ['mx', 'es', 'cu']:

    print('\n')
    print('=' * 70)
    print(f'OPTUNA REFINADO - {variante.upper()}')
    print(f'Preprocesamiento: {MEJOR_PREP[variante]}')
    print('=' * 70)

    sampler = optuna.samplers.TPESampler(
        seed=RANDOM_STATE
    )

    study = optuna.create_study(
        direction='maximize',
        sampler=sampler,
        study_name=f'xgboost_refinado_{variante}'
    )

    study.optimize(
        lambda trial: objective_xgboost_refinado(
            trial,
            variante
        ),
        n_trials=N_TRIALS_REFINADOS,
        show_progress_bar=True
    )

    studies_refinados[variante] = study

    print(
        f'\nMejor F1-Macro CV refinado: '
        f'{study.best_value:.4f}'
    )

    print('\nMejores hiperparámetros:')

    for parametro, valor in study.best_params.items():
        print(f'  {parametro}: {valor}')


# ============================================================
# 11.4 COMPARAR PRIMERA VS SEGUNDA BÚSQUEDA
# ============================================================

comparacion_optuna = []

for variante in ['mx', 'es', 'cu']:

    primera = studies[variante]
    segunda = studies_refinados[variante]

    comparacion_optuna.append({
        'variante': variante,

        'f1_primera_busqueda':
            primera.best_value,

        'f1_segunda_busqueda':
            segunda.best_value,

        'mejora':
            segunda.best_value - primera.best_value,

        'mejor_busqueda':
            (
                'segunda'
                if segunda.best_value > primera.best_value
                else 'primera'
            )
    })


df_comparacion_optuna = pd.DataFrame(
    comparacion_optuna
)

print('\n')
print('=' * 70)
print('COMPARACIÓN OPTUNA 1 VS OPTUNA 2')
print('=' * 70)

display(
    df_comparacion_optuna.style.format({
        'f1_primera_busqueda': '{:.4f}',
        'f1_segunda_busqueda': '{:.4f}',
        'mejora': '{:+.4f}'
    })
)


# ============================================================
# 11.5 GUARDAR MEJOR CONFIGURACIÓN DEFINITIVA
# ============================================================

mejores_studies_finales = {}

for variante in ['mx', 'es', 'cu']:

    if (
        studies_refinados[variante].best_value
        >
        studies[variante].best_value
    ):
        mejores_studies_finales[variante] = (
            studies_refinados[variante]
        )
    else:
        mejores_studies_finales[variante] = (
            studies[variante]
        )


# ============================================================
# 11.6 RESUMEN FINAL DE HIPERPARÁMETROS
# ============================================================

resumen_final = []

for variante, study in mejores_studies_finales.items():

    fila = {
        'variante': variante,
        'preprocesamiento':
            MEJOR_PREP[variante],

        'best_f1_macro_cv':
            study.best_value
    }

    fila.update(study.best_params)

    resumen_final.append(fila)


df_mejores_finales = pd.DataFrame(
    resumen_final
)

print('\n')
print('=' * 70)
print('CONFIGURACIÓN DEFINITIVA POR VARIANTE')
print('=' * 70)

display(
    df_mejores_finales.style.format({
        'best_f1_macro_cv': '{:.4f}',
        'learning_rate': '{:.5f}',
        'subsample': '{:.4f}',
        'colsample_bytree': '{:.4f}',
        'gamma': '{:.4f}',
        'reg_alpha': '{:.5f}',
        'reg_lambda': '{:.5f}',
        'scale_pos_weight': '{:.4f}'
    })
)

[I 2026-09-21 17:12:51,823] A new study created in memory with name: xgboost_refinado_mx

======================================================================
OPTUNA REFINADO - MX
Preprocesamiento: normal
======================================================================

  0%|          | 0/40 [00:00<?, ?it/s]

Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:12:58,566] Trial 0 finished with value: 0.6060274735770232 and parameters: {'n_estimators': 550, 'max_depth': 8, 'learning_rate': 0.06014196290837443, 'min_child_weight': 2, 'subsample': 0.6312037280884872, 'colsample_bytree': 0.6811989040672406, 'gamma': 2.1742508365045983, 'reg_alpha': 0.0396760507705299, 'reg_lambda': 0.6054365855469247, 'scale_pos_weight': 1.8956508044572318}. Best is trial 0 with value: 0.6060274735770232.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:13:03,807] Trial 1 finished with value: 0.6131117329853221 and parameters: {'n_estimators': 450, 'max_depth': 8, 'learning_rate': 0.06995068079750541, 'min_child_weight': 1, 'subsample': 0.6363649934414202, 'colsample_bytree': 0.6866809019706868, 'gamma': 2.912726728878613, 'reg_alpha': 0.0037520558551242854, 'reg_lambda': 0.364731628491121, 'scale_pos_weight': 1.6038603981386292}. Best is trial 1 with value: 0.6131117329853221.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:13:09,638] Trial 2 finished with value: 0.6107232707827805 and parameters: {'n_estimators': 625, 'max_depth': 4, 'learning_rate': 0.03103577079915638, 'min_child_weight': 2, 'subsample': 0.6912139968434072, 'colsample_bytree': 0.8070351922786028, 'gamma': 2.5990213464750793, 'reg_alpha': 0.003489018845491387, 'reg_lambda': 0.5898602410432694, 'scale_pos_weight': 1.4325152889039983}. Best is trial 1 with value: 0.6131117329853221.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:13:15,368] Trial 3 finished with value: 0.6229606407020472 and parameters: {'n_estimators': 625, 'max_depth': 4, 'learning_rate': 0.02205578452420942, 'min_child_weight': 3, 'subsample': 0.793126406614912, 'colsample_bytree': 0.8116794696232922, 'gamma': 2.913841307520112, 'reg_alpha': 0.00019634341572933326, 'reg_lambda': 0.7766184280392886, 'scale_pos_weight': 1.7081067456177208}. Best is trial 3 with value: 0.6229606407020472.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:13:21,134] Trial 4 finished with value: 0.6259045680927553 and parameters: {'n_estimators': 475, 'max_depth': 6, 'learning_rate': 0.021061679900335632, 'min_child_weight': 3, 'subsample': 0.6517559963200034, 'colsample_bytree': 0.7825044568707964, 'gamma': 2.9351332282682328, 'reg_alpha': 0.0036324869566766076, 'reg_lambda': 0.5143828405076928, 'scale_pos_weight': 1.529398118867869}. Best is trial 4 with value: 0.6259045680927553.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:13:28,005] Trial 5 finished with value: 0.6008637614919122 and parameters: {'n_estimators': 750, 'max_depth': 7, 'learning_rate': 0.08217173577024987, 'min_child_weight': 3, 'subsample': 0.7195799957622171, 'colsample_bytree': 0.8343748470046234, 'gamma': 2.2654775061557584, 'reg_alpha': 0.0003872118032174585, 'reg_lambda': 0.1145096426832664, 'scale_pos_weight': 1.627731231534285}. Best is trial 4 with value: 0.6259045680927553.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:13:33,741] Trial 6 finished with value: 0.6118255635197083 and parameters: {'n_estimators': 575, 'max_depth': 5, 'learning_rate': 0.06956194349487431, 'min_child_weight': 2, 'subsample': 0.6561869019374762, 'colsample_bytree': 0.7585392166316497, 'gamma': 2.422772674924288, 'reg_alpha': 0.025502980701628937, 'reg_lambda': 0.12502377950801113, 'scale_pos_weight': 2.090820855620362}. Best is trial 4 with value: 0.6259045680927553.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:13:39,616] Trial 7 finished with value: 0.6206564109934225 and parameters: {'n_estimators': 700, 'max_depth': 4, 'learning_rate': 0.02016680558993271, 'min_child_weight': 3, 'subsample': 0.7413714687695234, 'colsample_bytree': 0.7958014336081974, 'gamma': 4.313811040057837, 'reg_alpha': 0.0001667761543019791, 'reg_lambda': 0.29266761285490717, 'scale_pos_weight': 1.4811083416675908}. Best is trial 4 with value: 0.6259045680927553.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:13:46,055] Trial 8 finished with value: 0.6097006041234811 and parameters: {'n_estimators': 725, 'max_depth': 7, 'learning_rate': 0.03289854768134375, 'min_child_weight': 1, 'subsample': 0.6621964643431324, 'colsample_bytree': 0.7150366644053494, 'gamma': 4.188818535014192, 'reg_alpha': 0.008178476574339543, 'reg_lambda': 1.426561143637793, 'scale_pos_weight': 1.7305504476133646}. Best is trial 4 with value: 0.6259045680927553.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:13:50,546] Trial 9 finished with value: 0.6130533202680244 and parameters: {'n_estimators': 475, 'max_depth': 7, 'learning_rate': 0.06280356685930856, 'min_child_weight': 2, 'subsample': 0.7541934359909123, 'colsample_bytree': 0.7487591192728782, 'gamma': 3.568198488145982, 'reg_alpha': 0.0019170041589170674, 'reg_lambda': 0.10791232418686399, 'scale_pos_weight': 1.475523998895313}. Best is trial 4 with value: 0.6259045680927553.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:13:56,073] Trial 10 finished with value: 0.6165473818180176 and parameters: {'n_estimators': 500, 'max_depth': 6, 'learning_rate': 0.038548184223793046, 'min_child_weight': 2, 'subsample': 0.6936193454101188, 'colsample_bytree': 0.76164840030051, 'gamma': 2.5596927373835823, 'reg_alpha': 0.042771347699765525, 'reg_lambda': 0.22832466171526164, 'scale_pos_weight': 1.5102890103005042}. Best is trial 4 with value: 0.6259045680927553.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:14:01,066] Trial 11 finished with value: 0.6231248620509853 and parameters: {'n_estimators': 550, 'max_depth': 4, 'learning_rate': 0.021782749235913425, 'min_child_weight': 3, 'subsample': 0.6680730704232154, 'colsample_bytree': 0.8437152455924967, 'gamma': 2.5987898224111907, 'reg_alpha': 0.00023182864448940597, 'reg_lambda': 1.161506383713377, 'scale_pos_weight': 1.4325647478579024}. Best is trial 4 with value: 0.6259045680927553.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:14:06,304] Trial 12 finished with value: 0.610574386328942 and parameters: {'n_estimators': 450, 'max_depth': 6, 'learning_rate': 0.021851490866152578, 'min_child_weight': 3, 'subsample': 0.6442649810814105, 'colsample_bytree': 0.7800743403392537, 'gamma': 2.3987351274244135, 'reg_alpha': 0.0010332159079673529, 'reg_lambda': 1.4274047397922083, 'scale_pos_weight': 1.488920944897936}. Best is trial 4 with value: 0.6259045680927553.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:14:10,707] Trial 13 finished with value: 0.6202422108208898 and parameters: {'n_estimators': 475, 'max_depth': 4, 'learning_rate': 0.02029049336896416, 'min_child_weight': 3, 'subsample': 0.6523359604164403, 'colsample_bytree': 0.7894900640081783, 'gamma': 2.1280414950599558, 'reg_alpha': 0.001983722779458645, 'reg_lambda': 0.7063527708351744, 'scale_pos_weight': 1.7228924730412631}. Best is trial 4 with value: 0.6259045680927553.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:14:16,415] Trial 14 finished with value: 0.6154216481227123 and parameters: {'n_estimators': 525, 'max_depth': 6, 'learning_rate': 0.02660608696677713, 'min_child_weight': 3, 'subsample': 0.6985593748951134, 'colsample_bytree': 0.8399690523904326, 'gamma': 3.2545957871312456, 'reg_alpha': 0.0003191094273284849, 'reg_lambda': 0.8687231352075084, 'scale_pos_weight': 1.426594400143799}. Best is trial 4 with value: 0.6259045680927553.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:14:22,199] Trial 15 finished with value: 0.6231083728981257 and parameters: {'n_estimators': 525, 'max_depth': 6, 'learning_rate': 0.020656216749368014, 'min_child_weight': 3, 'subsample': 0.6607878350329641, 'colsample_bytree': 0.7542103097204496, 'gamma': 2.730025317704195, 'reg_alpha': 0.0037322295773733302, 'reg_lambda': 0.5933481288405428, 'scale_pos_weight': 1.5057086701784552}. Best is trial 4 with value: 0.6259045680927553.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:14:27,608] Trial 16 finished with value: 0.6137548208833268 and parameters: {'n_estimators': 550, 'max_depth': 5, 'learning_rate': 0.041889780390403364, 'min_child_weight': 3, 'subsample': 0.6919517792909026, 'colsample_bytree': 0.827479328002749, 'gamma': 2.998751868773787, 'reg_alpha': 0.0008141575416917843, 'reg_lambda': 1.0692315065539004, 'scale_pos_weight': 1.6253930774664918}. Best is trial 4 with value: 0.6259045680927553.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:14:32,510] Trial 17 finished with value: 0.6208006048074008 and parameters: {'n_estimators': 475, 'max_depth': 5, 'learning_rate': 0.025992624584761308, 'min_child_weight': 3, 'subsample': 0.698058371175688, 'colsample_bytree': 0.7817848302273489, 'gamma': 2.117043324373192, 'reg_alpha': 0.00017934340694949124, 'reg_lambda': 0.7537809037379852, 'scale_pos_weight': 1.5872662719914992}. Best is trial 4 with value: 0.6259045680927553.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:14:37,802] Trial 18 finished with value: 0.6153066733821468 and parameters: {'n_estimators': 575, 'max_depth': 4, 'learning_rate': 0.02776660942466255, 'min_child_weight': 2, 'subsample': 0.6643570352532635, 'colsample_bytree': 0.8351802722398074, 'gamma': 2.5389016174448824, 'reg_alpha': 0.00023001327912607416, 'reg_lambda': 1.223494422504963, 'scale_pos_weight': 1.4943280188840418}. Best is trial 4 with value: 0.6259045680927553.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:14:43,227] Trial 19 finished with value: 0.6201351821992935 and parameters: {'n_estimators': 625, 'max_depth': 4, 'learning_rate': 0.02045240254737575, 'min_child_weight': 3, 'subsample': 0.693224817080558, 'colsample_bytree': 0.7944242229062344, 'gamma': 3.437935613852001, 'reg_alpha': 0.00013696871980583083, 'reg_lambda': 1.1873784578975008, 'scale_pos_weight': 1.4009776763958195}. Best is trial 4 with value: 0.6259045680927553.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:14:47,947] Trial 20 finished with value: 0.6080989190241646 and parameters: {'n_estimators': 500, 'max_depth': 4, 'learning_rate': 0.023659527756775482, 'min_child_weight': 3, 'subsample': 0.6165459477015808, 'colsample_bytree': 0.8205808546322155, 'gamma': 2.9510073426045054, 'reg_alpha': 0.0017446931793914885, 'reg_lambda': 1.729950284103583, 'scale_pos_weight': 1.4442951671176298}. Best is trial 4 with value: 0.6259045680927553.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:14:53,075] Trial 21 finished with value: 0.6151068915524844 and parameters: {'n_estimators': 575, 'max_depth': 4, 'learning_rate': 0.03090964961309817, 'min_child_weight': 3, 'subsample': 0.6497729459535918, 'colsample_bytree': 0.8260821477265782, 'gamma': 2.800682606010972, 'reg_alpha': 0.00010695224718247692, 'reg_lambda': 0.646420576018071, 'scale_pos_weight': 1.5374604891652914}. Best is trial 4 with value: 0.6259045680927553.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:14:58,512] Trial 22 finished with value: 0.6124846549255423 and parameters: {'n_estimators': 550, 'max_depth': 5, 'learning_rate': 0.021768520078026304, 'min_child_weight': 3, 'subsample': 0.6755367799572436, 'colsample_bytree': 0.765097398695421, 'gamma': 2.1410140515186007, 'reg_alpha': 0.0037952954648339666, 'reg_lambda': 0.3244209196829699, 'scale_pos_weight': 1.43175096994263}. Best is trial 4 with value: 0.6259045680927553.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:15:04,499] Trial 23 finished with value: 0.6212145485685305 and parameters: {'n_estimators': 550, 'max_depth': 6, 'learning_rate': 0.02084511481449692, 'min_child_weight': 3, 'subsample': 0.666336275630896, 'colsample_bytree': 0.7874540911664459, 'gamma': 3.166916822876214, 'reg_alpha': 0.001038472643926335, 'reg_lambda': 0.547191128880325, 'scale_pos_weight': 1.4516178091656913}. Best is trial 4 with value: 0.6259045680927553.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:15:09,844] Trial 24 finished with value: 0.6225301614376152 and parameters: {'n_estimators': 475, 'max_depth': 6, 'learning_rate': 0.023081317402672486, 'min_child_weight': 3, 'subsample': 0.6906983653946421, 'colsample_bytree': 0.7411786950440638, 'gamma': 2.6836875814576366, 'reg_alpha': 0.006450588294008687, 'reg_lambda': 0.7754593571453662, 'scale_pos_weight': 1.6183689150787206}. Best is trial 4 with value: 0.6259045680927553.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:15:16,200] Trial 25 finished with value: 0.6220219691040775 and parameters: {'n_estimators': 525, 'max_depth': 7, 'learning_rate': 0.02396418022090978, 'min_child_weight': 3, 'subsample': 0.6378235798989026, 'colsample_bytree': 0.7434612530919158, 'gamma': 2.458543314298967, 'reg_alpha': 0.0008245614839079405, 'reg_lambda': 0.4811390881505152, 'scale_pos_weight': 1.6082264023684691}. Best is trial 4 with value: 0.6259045680927553.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:15:21,863] Trial 26 finished with value: 0.6118033613238364 and parameters: {'n_estimators': 500, 'max_depth': 6, 'learning_rate': 0.02451960392256047, 'min_child_weight': 3, 'subsample': 0.6301325499939062, 'colsample_bytree': 0.7932521785267099, 'gamma': 2.8547385733225408, 'reg_alpha': 0.023586948247471783, 'reg_lambda': 0.7622148170117039, 'scale_pos_weight': 1.4469864306699134}. Best is trial 4 with value: 0.6259045680927553.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:15:27,362] Trial 27 finished with value: 0.6132625713865039 and parameters: {'n_estimators': 625, 'max_depth': 4, 'learning_rate': 0.02425299779253577, 'min_child_weight': 3, 'subsample': 0.6431573368168144, 'colsample_bytree': 0.8133269260321728, 'gamma': 2.264036837366511, 'reg_alpha': 0.002870553532871696, 'reg_lambda': 0.979427343375037, 'scale_pos_weight': 1.4724990845599553}. Best is trial 4 with value: 0.6259045680927553.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:15:32,269] Trial 28 finished with value: 0.6143314474454127 and parameters: {'n_estimators': 475, 'max_depth': 5, 'learning_rate': 0.03081048859519149, 'min_child_weight': 3, 'subsample': 0.7052288693079571, 'colsample_bytree': 0.8117633052538222, 'gamma': 2.14475515892618, 'reg_alpha': 0.0007317072847564229, 'reg_lambda': 0.8364012169264494, 'scale_pos_weight': 1.4527466344665176}. Best is trial 4 with value: 0.6259045680927553.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:15:37,751] Trial 29 finished with value: 0.6167199224946739 and parameters: {'n_estimators': 500, 'max_depth': 6, 'learning_rate': 0.023463074282290792, 'min_child_weight': 3, 'subsample': 0.654091303205371, 'colsample_bytree': 0.7808914963706148, 'gamma': 3.5490926371282225, 'reg_alpha': 0.007486395705009747, 'reg_lambda': 0.5785542239347983, 'scale_pos_weight': 1.5276868867422173}. Best is trial 4 with value: 0.6259045680927553.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:15:42,918] Trial 30 finished with value: 0.6202093667015115 and parameters: {'n_estimators': 450, 'max_depth': 6, 'learning_rate': 0.021959890426810555, 'min_child_weight': 3, 'subsample': 0.6440772536111584, 'colsample_bytree': 0.8217043899322044, 'gamma': 2.9114441361733014, 'reg_alpha': 0.0025392695936611895, 'reg_lambda': 0.406258240609184, 'scale_pos_weight': 1.457745325616271}. Best is trial 4 with value: 0.6259045680927553.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:15:48,796] Trial 31 finished with value: 0.6202106239312949 and parameters: {'n_estimators': 475, 'max_depth': 7, 'learning_rate': 0.020122422134678637, 'min_child_weight': 3, 'subsample': 0.6492528692358616, 'colsample_bytree': 0.7378357942203401, 'gamma': 2.683643838022849, 'reg_alpha': 0.0063118652520136485, 'reg_lambda': 0.5465115623427395, 'scale_pos_weight': 1.5569496190555845}. Best is trial 4 with value: 0.6259045680927553.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:15:54,483] Trial 32 finished with value: 0.615649850729789 and parameters: {'n_estimators': 575, 'max_depth': 5, 'learning_rate': 0.021471445851142898, 'min_child_weight': 3, 'subsample': 0.691418968046287, 'colsample_bytree': 0.784038369232028, 'gamma': 2.319194729049293, 'reg_alpha': 0.0005651618487370865, 'reg_lambda': 0.7129441917163332, 'scale_pos_weight': 1.4294308902774957}. Best is trial 4 with value: 0.6259045680927553.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:15:59,333] Trial 33 finished with value: 0.6194177534242484 and parameters: {'n_estimators': 525, 'max_depth': 4, 'learning_rate': 0.021418259444883073, 'min_child_weight': 3, 'subsample': 0.6505572246795936, 'colsample_bytree': 0.8428812572908508, 'gamma': 2.2059977847360854, 'reg_alpha': 0.00015034667667289522, 'reg_lambda': 1.0658313315114754, 'scale_pos_weight': 1.4825677180095462}. Best is trial 4 with value: 0.6259045680927553.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:16:04,618] Trial 34 finished with value: 0.618426477076191 and parameters: {'n_estimators': 600, 'max_depth': 4, 'learning_rate': 0.024007397426352925, 'min_child_weight': 3, 'subsample': 0.7040575032769248, 'colsample_bytree': 0.8243915929701179, 'gamma': 3.1686954143358226, 'reg_alpha': 0.00016581336314049747, 'reg_lambda': 0.7578399812334107, 'scale_pos_weight': 1.6660498178764866}. Best is trial 4 with value: 0.6259045680927553.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:16:09,617] Trial 35 finished with value: 0.6164497090897931 and parameters: {'n_estimators': 500, 'max_depth': 5, 'learning_rate': 0.02263834120717632, 'min_child_weight': 3, 'subsample': 0.647939629210494, 'colsample_bytree': 0.749969253646175, 'gamma': 3.0908427242339056, 'reg_alpha': 0.002149167370373849, 'reg_lambda': 0.5386729744360614, 'scale_pos_weight': 1.42892357112311}. Best is trial 4 with value: 0.6259045680927553.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:16:15,659] Trial 36 finished with value: 0.619115324809212 and parameters: {'n_estimators': 600, 'max_depth': 5, 'learning_rate': 0.021940935245049253, 'min_child_weight': 3, 'subsample': 0.7745306058856165, 'colsample_bytree': 0.8204311379286304, 'gamma': 2.7463454382615407, 'reg_alpha': 0.0001901368580614326, 'reg_lambda': 1.061973404261511, 'scale_pos_weight': 1.6281472387903475}. Best is trial 4 with value: 0.6259045680927553.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:16:20,954] Trial 37 finished with value: 0.6176505033639497 and parameters: {'n_estimators': 475, 'max_depth': 6, 'learning_rate': 0.023563303632028097, 'min_child_weight': 3, 'subsample': 0.6694766720394096, 'colsample_bytree': 0.765119557645728, 'gamma': 2.885338769999125, 'reg_alpha': 0.011264682844467898, 'reg_lambda': 0.39927655032997555, 'scale_pos_weight': 1.4511950557486175}. Best is trial 4 with value: 0.6259045680927553.
Cargando: ../data/train_clean_mx.csv
[I 2026-09-21 17:16:26,567] Trial 38 finished with value: 0.6240557305082595 and parameters: {'n_estimators': 650, 'max_depth': 4, 'learning_rate': 0.02307808373269079, 'min_child_weight': 3, 'subsample': 0.691617742374879, 'colsample_bytree': 0.7797733898402681, 'gamma': 3.067909438603068, 'reg_alpha': 0.00035640918537784667, 'reg_lambda': 0.9396019920285547, 'scale_pos_weight': 1.7201078675521753}. Best is trial 4 with value: 0.6259045680927553.
Cargando: ../data/train_clean_mx.csv

[I 2026-09-21 17:16:32,105] A new study created in memory with name: xgboost_refinado_es

[I 2026-09-21 17:16:32,102] Trial 39 finished with value: 0.6169764444926987 and parameters: {'n_estimators': 550, 'max_depth': 5, 'learning_rate': 0.021382518511067233, 'min_child_weight': 3, 'subsample': 0.6682937197399184, 'colsample_bytree': 0.8152674736984731, 'gamma': 3.341499595839002, 'reg_alpha': 0.0005296947566495865, 'reg_lambda': 0.722373776494801, 'scale_pos_weight': 1.5768009249879626}. Best is trial 4 with value: 0.6259045680927553.

Mejor F1-Macro CV refinado: 0.6259

Mejores hiperparámetros:
  n_estimators: 475
  max_depth: 6
  learning_rate: 0.021061679900335632
  min_child_weight: 3
  subsample: 0.6517559963200034
  colsample_bytree: 0.7825044568707964
  gamma: 2.9351332282682328
  reg_alpha: 0.0036324869566766076
  reg_lambda: 0.5143828405076928
  scale_pos_weight: 1.529398118867869


======================================================================
OPTUNA REFINADO - ES
Preprocesamiento: lemma
======================================================================

  0%|          | 0/40 [00:00<?, ?it/s]

Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:16:41,418] Trial 0 finished with value: 0.6969567942521826 and parameters: {'n_estimators': 650, 'max_depth': 5, 'learning_rate': 0.05517397349623406, 'min_child_weight': 2, 'subsample': 0.8734027960663655, 'colsample_bytree': 0.8733991780504303, 'gamma': 1.1742508365045983, 'reg_alpha': 0.021766241123453687, 'reg_lambda': 2.6471868808879733, 'scale_pos_weight': 1.6248435466776274}. Best is trial 0 with value: 0.6969567942521826.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:16:48,660] Trial 1 finished with value: 0.7054863625296823 and parameters: {'n_estimators': 550, 'max_depth': 5, 'learning_rate': 0.06341768796084152, 'min_child_weight': 1, 'subsample': 0.877273745081065, 'colsample_bytree': 0.8775106764780151, 'gamma': 1.9127267288786132, 'reg_alpha': 0.002607965659809585, 'reg_lambda': 1.6560888480945333, 'scale_pos_weight': 1.3747374841188251}. Best is trial 1 with value: 0.7054863625296823.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:16:55,128] Trial 2 finished with value: 0.7003209123401366 and parameters: {'n_estimators': 700, 'max_depth': 2, 'learning_rate': 0.029986004389261193, 'min_child_weight': 2, 'subsample': 0.9184104976325553, 'colsample_bytree': 0.967776394208952, 'gamma': 1.5990213464750793, 'reg_alpha': 0.0024428866967349987, 'reg_lambda': 2.584093506411774, 'scale_pos_weight': 1.2278702476319987}. Best is trial 1 with value: 0.7054863625296823.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:17:01,514] Trial 3 finished with value: 0.6967411152595538 and parameters: {'n_estimators': 700, 'max_depth': 2, 'learning_rate': 0.021887439425976252, 'min_child_weight': 3, 'subsample': 0.9948448049611839, 'colsample_bytree': 0.9712596022174692, 'gamma': 1.9138413075201122, 'reg_alpha': 0.00018349072049055458, 'reg_lambda': 3.333255960250397, 'scale_pos_weight': 1.4640914962437608}. Best is trial 1 with value: 0.7054863625296823.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:17:08,005] Trial 4 finished with value: 0.7056100470625646 and parameters: {'n_estimators': 575, 'max_depth': 3, 'learning_rate': 0.020976544532321704, 'min_child_weight': 3, 'subsample': 0.8888169972400025, 'colsample_bytree': 0.9493783426530973, 'gamma': 1.9351332282682328, 'reg_alpha': 0.0025330746540014474, 'reg_lambda': 2.276537331461955, 'scale_pos_weight': 1.3109126733153162}. Best is trial 4 with value: 0.7056100470625646.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:17:17,166] Trial 5 finished with value: 0.6999184033640375 and parameters: {'n_estimators': 800, 'max_depth': 5, 'learning_rate': 0.07356389575148468, 'min_child_weight': 3, 'subsample': 0.9396849968216627, 'colsample_bytree': 0.9882811352534675, 'gamma': 1.2654775061557584, 'reg_alpha': 0.00033802737047124425, 'reg_lambda': 0.5667990147757791, 'scale_pos_weight': 1.3951981984579587}. Best is trial 4 with value: 0.7056100470625646.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:17:24,184] Trial 6 finished with value: 0.7018390286131366 and parameters: {'n_estimators': 650, 'max_depth': 3, 'learning_rate': 0.06309278428352182, 'min_child_weight': 2, 'subsample': 0.8921401764531071, 'colsample_bytree': 0.9314044124737373, 'gamma': 1.422772674924288, 'reg_alpha': 0.014625327121207692, 'reg_lambda': 0.6148057549607031, 'scale_pos_weight': 1.7921321619603106}. Best is trial 4 with value: 0.7056100470625646.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:17:30,933] Trial 7 finished with value: 0.692235017737753 and parameters: {'n_estimators': 750, 'max_depth': 2, 'learning_rate': 0.02015369312797273, 'min_child_weight': 3, 'subsample': 0.9560286015771425, 'colsample_bytree': 0.959351075206148, 'gamma': 3.3138110400578373, 'reg_alpha': 0.0001584325068438869, 'reg_lambda': 1.350845720196498, 'scale_pos_weight': 1.2695214357150777}. Best is trial 4 with value: 0.7056100470625646.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:17:39,533] Trial 8 finished with value: 0.7096893442317876 and parameters: {'n_estimators': 775, 'max_depth': 4, 'learning_rate': 0.03164101871724988, 'min_child_weight': 1, 'subsample': 0.8966473482573493, 'colsample_bytree': 0.898777498304012, 'gamma': 3.1888185350141924, 'reg_alpha': 0.005257127272786869, 'reg_lambda': 5.85168037586392, 'scale_pos_weight': 1.4833289550971696}. Best is trial 8 with value: 0.7096893442317876.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:17:45,779] Trial 9 finished with value: 0.7008086651202652 and parameters: {'n_estimators': 575, 'max_depth': 4, 'learning_rate': 0.057420667326657605, 'min_child_weight': 2, 'subsample': 0.9656450769931841, 'colsample_bytree': 0.9240693394546586, 'gamma': 2.568198488145982, 'reg_alpha': 0.00142534627201215, 'reg_lambda': 0.5365098290336188, 'scale_pos_weight': 1.2647348561959826}. Best is trial 8 with value: 0.7096893442317876.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:17:55,145] Trial 10 finished with value: 0.7115666857469943 and parameters: {'n_estimators': 725, 'max_depth': 4, 'learning_rate': 0.023484260096657644, 'min_child_weight': 1, 'subsample': 0.9281443803453815, 'colsample_bytree': 0.8550982918896112, 'gamma': 1.5508356782359656, 'reg_alpha': 0.016474136923970154, 'reg_lambda': 2.6500802715642964, 'scale_pos_weight': 1.329464416173443}. Best is trial 10 with value: 0.7115666857469943.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:18:03,345] Trial 11 finished with value: 0.7135297707581827 and parameters: {'n_estimators': 775, 'max_depth': 4, 'learning_rate': 0.029541163614874227, 'min_child_weight': 1, 'subsample': 0.9585995985547178, 'colsample_bytree': 0.8836941661004954, 'gamma': 2.8417377011176943, 'reg_alpha': 0.04119379042044028, 'reg_lambda': 6.867346536918053, 'scale_pos_weight': 1.270315808816275}. Best is trial 11 with value: 0.7135297707581827.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:18:11,385] Trial 12 finished with value: 0.7087778214649143 and parameters: {'n_estimators': 750, 'max_depth': 3, 'learning_rate': 0.024393627524221157, 'min_child_weight': 1, 'subsample': 0.9491715514845912, 'colsample_bytree': 0.8843966261585069, 'gamma': 3.068565914337818, 'reg_alpha': 0.03476706154188282, 'reg_lambda': 3.7480101885126724, 'scale_pos_weight': 1.2094374372958183}. Best is trial 11 with value: 0.7135297707581827.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:18:19,803] Trial 13 finished with value: 0.713103187300495 and parameters: {'n_estimators': 800, 'max_depth': 3, 'learning_rate': 0.03738193928475562, 'min_child_weight': 1, 'subsample': 0.9859088275928134, 'colsample_bytree': 0.9133159198081454, 'gamma': 1.8956849421508428, 'reg_alpha': 0.028087334644003273, 'reg_lambda': 7.15736496360743, 'scale_pos_weight': 1.3933650158790754}. Best is trial 11 with value: 0.7135297707581827.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:18:27,743] Trial 14 finished with value: 0.7090015052351882 and parameters: {'n_estimators': 775, 'max_depth': 5, 'learning_rate': 0.027839042463650477, 'min_child_weight': 2, 'subsample': 0.9788430563624655, 'colsample_bytree': 0.8933969793913347, 'gamma': 3.5842594894672604, 'reg_alpha': 0.015169593997035428, 'reg_lambda': 6.499087281647025, 'scale_pos_weight': 1.3370291394127973}. Best is trial 11 with value: 0.7135297707581827.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:18:36,685] Trial 15 finished with value: 0.7084907248377619 and parameters: {'n_estimators': 775, 'max_depth': 4, 'learning_rate': 0.035650796041177955, 'min_child_weight': 2, 'subsample': 0.9718459912673176, 'colsample_bytree': 0.9359219458769953, 'gamma': 1.9278949650413744, 'reg_alpha': 0.017068048658259248, 'reg_lambda': 4.635287264751866, 'scale_pos_weight': 1.2121711290363388}. Best is trial 11 with value: 0.7135297707581827.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:18:45,742] Trial 16 finished with value: 0.7078648679925743 and parameters: {'n_estimators': 775, 'max_depth': 4, 'learning_rate': 0.03612108172432161, 'min_child_weight': 1, 'subsample': 0.9979654547784297, 'colsample_bytree': 0.9287884591518729, 'gamma': 1.5644594476749947, 'reg_alpha': 0.029989552810921964, 'reg_lambda': 6.841968516306379, 'scale_pos_weight': 1.3415801099405338}. Best is trial 11 with value: 0.7135297707581827.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:18:53,372] Trial 17 finished with value: 0.6997556213990507 and parameters: {'n_estimators': 800, 'max_depth': 4, 'learning_rate': 0.050079496394453256, 'min_child_weight': 1, 'subsample': 0.9811880821799948, 'colsample_bytree': 0.8912935626543624, 'gamma': 3.0381397323485615, 'reg_alpha': 0.01640023634902577, 'reg_lambda': 5.762114753178052, 'scale_pos_weight': 1.5153304801345908}. Best is trial 11 with value: 0.7135297707581827.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:19:01,917] Trial 18 finished with value: 0.7092112710017483 and parameters: {'n_estimators': 775, 'max_depth': 3, 'learning_rate': 0.03967475010674521, 'min_child_weight': 1, 'subsample': 0.9632574384556005, 'colsample_bytree': 0.9478191830380955, 'gamma': 1.7453201286697348, 'reg_alpha': 0.004757474874758808, 'reg_lambda': 5.961027330997788, 'scale_pos_weight': 1.3669385699654912}. Best is trial 11 with value: 0.7135297707581827.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:19:09,051] Trial 19 finished with value: 0.7053687151883727 and parameters: {'n_estimators': 800, 'max_depth': 2, 'learning_rate': 0.03477537919839345, 'min_child_weight': 1, 'subsample': 0.9806438046966004, 'colsample_bytree': 0.8787514723098602, 'gamma': 1.8703789820537997, 'reg_alpha': 0.044384956991405454, 'reg_lambda': 5.637170341647292, 'scale_pos_weight': 1.349062386963888}. Best is trial 11 with value: 0.7135297707581827.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:19:16,281] Trial 20 finished with value: 0.712978222191908 and parameters: {'n_estimators': 775, 'max_depth': 3, 'learning_rate': 0.05713378238656742, 'min_child_weight': 1, 'subsample': 0.9881871691721988, 'colsample_bytree': 0.9350484418209277, 'gamma': 2.4586909191364223, 'reg_alpha': 0.013683768228052213, 'reg_lambda': 4.203572978496643, 'scale_pos_weight': 1.3898849399962812}. Best is trial 11 with value: 0.7135297707581827.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:19:24,636] Trial 21 finished with value: 0.7117668632463264 and parameters: {'n_estimators': 750, 'max_depth': 3, 'learning_rate': 0.026578726016859407, 'min_child_weight': 1, 'subsample': 0.9327652774317668, 'colsample_bytree': 0.9041157791694134, 'gamma': 2.401753351499978, 'reg_alpha': 0.0131537372633199, 'reg_lambda': 6.473278963241503, 'scale_pos_weight': 1.3644082599001077}. Best is trial 11 with value: 0.7135297707581827.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:19:31,455] Trial 22 finished with value: 0.7078160038496448 and parameters: {'n_estimators': 725, 'max_depth': 3, 'learning_rate': 0.052921327852294295, 'min_child_weight': 1, 'subsample': 0.9696718716490174, 'colsample_bytree': 0.9235309342679092, 'gamma': 2.8033981521139277, 'reg_alpha': 0.014048679818716762, 'reg_lambda': 4.888464853594099, 'scale_pos_weight': 1.3221711634744477}. Best is trial 11 with value: 0.7135297707581827.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:19:39,497] Trial 23 finished with value: 0.7096765945743714 and parameters: {'n_estimators': 775, 'max_depth': 4, 'learning_rate': 0.03681426648524698, 'min_child_weight': 1, 'subsample': 0.959717289209846, 'colsample_bytree': 0.9251598050066444, 'gamma': 2.765508886996925, 'reg_alpha': 0.00939406476161832, 'reg_lambda': 7.203143425750255, 'scale_pos_weight': 1.3721908435516712}. Best is trial 11 with value: 0.7135297707581827.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:19:48,045] Trial 24 finished with value: 0.7073156758314673 and parameters: {'n_estimators': 800, 'max_depth': 3, 'learning_rate': 0.03677831451709431, 'min_child_weight': 1, 'subsample': 0.9928233230089397, 'colsample_bytree': 0.9196895315823501, 'gamma': 1.641835148708221, 'reg_alpha': 0.0077295313434540625, 'reg_lambda': 4.297144400437978, 'scale_pos_weight': 1.3027017897756104}. Best is trial 11 with value: 0.7135297707581827.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:19:56,762] Trial 25 finished with value: 0.7057183341337558 and parameters: {'n_estimators': 800, 'max_depth': 3, 'learning_rate': 0.03496996517088021, 'min_child_weight': 1, 'subsample': 0.9759966283400164, 'colsample_bytree': 0.90137807748411, 'gamma': 1.821942125781025, 'reg_alpha': 0.011331831450389278, 'reg_lambda': 5.7965047211833785, 'scale_pos_weight': 1.4596294318693892}. Best is trial 11 with value: 0.7135297707581827.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:20:05,537] Trial 26 finished with value: 0.711261795139246 and parameters: {'n_estimators': 800, 'max_depth': 3, 'learning_rate': 0.03346068925448269, 'min_child_weight': 1, 'subsample': 0.9506548707020711, 'colsample_bytree': 0.9466443679299312, 'gamma': 2.2253002386268217, 'reg_alpha': 0.007795531056362796, 'reg_lambda': 3.7408982990386437, 'scale_pos_weight': 1.4560521418033068}. Best is trial 11 with value: 0.7135297707581827.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:20:13,632] Trial 27 finished with value: 0.7051224209527975 and parameters: {'n_estimators': 725, 'max_depth': 3, 'learning_rate': 0.02689217187101949, 'min_child_weight': 1, 'subsample': 0.9990105417847608, 'colsample_bytree': 0.926744430630102, 'gamma': 1.6174212012740246, 'reg_alpha': 0.04044296149918973, 'reg_lambda': 7.214107055816139, 'scale_pos_weight': 1.4597726381842826}. Best is trial 11 with value: 0.7135297707581827.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:20:20,941] Trial 28 finished with value: 0.6980253130450202 and parameters: {'n_estimators': 800, 'max_depth': 2, 'learning_rate': 0.02215177123476626, 'min_child_weight': 1, 'subsample': 0.9844794010991971, 'colsample_bytree': 0.9002519647057338, 'gamma': 1.4974297454551466, 'reg_alpha': 0.032933653199613916, 'reg_lambda': 6.525824803672166, 'scale_pos_weight': 1.4304789299610186}. Best is trial 11 with value: 0.7135297707581827.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:20:28,868] Trial 29 finished with value: 0.7086406726963528 and parameters: {'n_estimators': 750, 'max_depth': 4, 'learning_rate': 0.02787811789397363, 'min_child_weight': 1, 'subsample': 0.9534752564394678, 'colsample_bytree': 0.892534809994057, 'gamma': 3.3801215254916444, 'reg_alpha': 0.026488976185096217, 'reg_lambda': 5.587085425044076, 'scale_pos_weight': 1.2876140424600164}. Best is trial 11 with value: 0.7135297707581827.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:20:36,537] Trial 30 finished with value: 0.7100781563483071 and parameters: {'n_estimators': 775, 'max_depth': 3, 'learning_rate': 0.03968289864025965, 'min_child_weight': 1, 'subsample': 0.9760551606448723, 'colsample_bytree': 0.9145588796644305, 'gamma': 2.7209927483132947, 'reg_alpha': 0.0473294431450161, 'reg_lambda': 4.998352822241258, 'scale_pos_weight': 1.402550935920974}. Best is trial 11 with value: 0.7135297707581827.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:20:44,828] Trial 31 finished with value: 0.7091797854611099 and parameters: {'n_estimators': 800, 'max_depth': 3, 'learning_rate': 0.03763286467575796, 'min_child_weight': 1, 'subsample': 0.9207186925447354, 'colsample_bytree': 0.8948981257567362, 'gamma': 2.492165038062831, 'reg_alpha': 0.02453949982215974, 'reg_lambda': 5.179167066990297, 'scale_pos_weight': 1.2825111112118717}. Best is trial 11 with value: 0.7135297707581827.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:20:54,802] Trial 32 finished with value: 0.7113393546546152 and parameters: {'n_estimators': 800, 'max_depth': 4, 'learning_rate': 0.031110461202668194, 'min_child_weight': 1, 'subsample': 0.9809343524663516, 'colsample_bytree': 0.8926200678078918, 'gamma': 1.6255653570477593, 'reg_alpha': 0.047095990377053566, 'reg_lambda': 5.577481050079899, 'scale_pos_weight': 1.3268129913786182}. Best is trial 11 with value: 0.7135297707581827.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:21:03,285] Trial 33 finished with value: 0.7100512906313984 and parameters: {'n_estimators': 775, 'max_depth': 3, 'learning_rate': 0.02568036342663776, 'min_child_weight': 1, 'subsample': 0.9473686491572606, 'colsample_bytree': 0.9177231428556166, 'gamma': 2.830833946637153, 'reg_alpha': 0.0053835797764102255, 'reg_lambda': 6.34582695725692, 'scale_pos_weight': 1.3388201686809333}. Best is trial 11 with value: 0.7135297707581827.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:21:10,771] Trial 34 finished with value: 0.712917156483839 and parameters: {'n_estimators': 750, 'max_depth': 3, 'learning_rate': 0.056550732760937035, 'min_child_weight': 1, 'subsample': 0.9938655718216274, 'colsample_bytree': 0.9107060586858745, 'gamma': 1.6410140109253804, 'reg_alpha': 0.03727887329377949, 'reg_lambda': 7.596269401057706, 'scale_pos_weight': 1.3636354846061696}. Best is trial 11 with value: 0.7135297707581827.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:21:18,033] Trial 35 finished with value: 0.7131234601120234 and parameters: {'n_estimators': 800, 'max_depth': 3, 'learning_rate': 0.06013909518299416, 'min_child_weight': 1, 'subsample': 0.9958232505773542, 'colsample_bytree': 0.9384057134574979, 'gamma': 2.199898744193414, 'reg_alpha': 0.016384291880428253, 'reg_lambda': 7.312493653935688, 'scale_pos_weight': 1.3891638173498144}. Best is trial 11 with value: 0.7135297707581827.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:21:25,319] Trial 36 finished with value: 0.7062635387574959 and parameters: {'n_estimators': 800, 'max_depth': 3, 'learning_rate': 0.06662134149361687, 'min_child_weight': 1, 'subsample': 0.9889856835414117, 'colsample_bytree': 0.8939612272194681, 'gamma': 2.083386248904826, 'reg_alpha': 0.022908073630580342, 'reg_lambda': 5.04301648029136, 'scale_pos_weight': 1.3567338788691998}. Best is trial 11 with value: 0.7135297707581827.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:21:32,266] Trial 37 finished with value: 0.7106090017146719 and parameters: {'n_estimators': 775, 'max_depth': 2, 'learning_rate': 0.050240903537061905, 'min_child_weight': 1, 'subsample': 0.9781673423701641, 'colsample_bytree': 0.954847298889655, 'gamma': 2.5659603080437807, 'reg_alpha': 0.019296923060482647, 'reg_lambda': 5.187045676719147, 'scale_pos_weight': 1.361520362436195}. Best is trial 11 with value: 0.7135297707581827.
Cargando: ../data/train_clean_lemma_es.csv
[I 2026-09-21 17:21:40,784] Trial 38 finished with value: 0.7121757692210323 and parameters: {'n_estimators': 775, 'max_depth': 4, 'learning_rate': 0.02740642311172121, 'min_child_weight': 1, 'subsample': 0.9441934224650763, 'colsample_bytree': 0.867853855776753, 'gamma': 2.9704432925509257, 'reg_alpha': 0.026379560526850337, 'reg_lambda': 6.184981867326591, 'scale_pos_weight': 1.3155437769568314}. Best is trial 11 with value: 0.7135297707581827.
Cargando: ../data/train_clean_lemma_es.csv

[I 2026-09-21 17:21:48,117] A new study created in memory with name: xgboost_refinado_cu

[I 2026-09-21 17:21:48,114] Trial 39 finished with value: 0.707333432664882 and parameters: {'n_estimators': 750, 'max_depth': 4, 'learning_rate': 0.04614559013384516, 'min_child_weight': 1, 'subsample': 0.9958966717890433, 'colsample_bytree': 0.9371024518404708, 'gamma': 2.559291398193623, 'reg_alpha': 0.00919942530043381, 'reg_lambda': 6.526450150893064, 'scale_pos_weight': 1.4097877816073126}. Best is trial 11 with value: 0.7135297707581827.

Mejor F1-Macro CV refinado: 0.7135

Mejores hiperparámetros:
  n_estimators: 775
  max_depth: 4
  learning_rate: 0.029541163614874227
  min_child_weight: 1
  subsample: 0.9585995985547178
  colsample_bytree: 0.8836941661004954
  gamma: 2.8417377011176943
  reg_alpha: 0.04119379042044028
  reg_lambda: 6.867346536918053
  scale_pos_weight: 1.270315808816275


======================================================================
OPTUNA REFINADO - CU
Preprocesamiento: stem
======================================================================

  0%|          | 0/40 [00:00<?, ?it/s]

Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:21:55,316] Trial 0 finished with value: 0.660488321764827 and parameters: {'n_estimators': 425, 'max_depth': 5, 'learning_rate': 0.03621056763954017, 'min_child_weight': 2, 'subsample': 0.7312037280884873, 'colsample_bytree': 0.7811989040672406, 'gamma': 1.6452090304204987, 'reg_alpha': 0.0396760507705299, 'reg_lambda': 0.3862689194653677, 'scale_pos_weight': 1.795650804457232}. Best is trial 0 with value: 0.660488321764827.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:22:01,749] Trial 1 finished with value: 0.6608323155450291 and parameters: {'n_estimators': 350, 'max_depth': 5, 'learning_rate': 0.040865594623548177, 'min_child_weight': 1, 'subsample': 0.73636499344142, 'colsample_bytree': 0.7866809019706867, 'gamma': 2.260605607398844, 'reg_alpha': 0.0037520558551242854, 'reg_lambda': 0.21727270548647376, 'scale_pos_weight': 1.5038603981386294}. Best is trial 1 with value: 0.6608323155450291.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:22:07,060] Trial 2 finished with value: 0.6509196801550343 and parameters: {'n_estimators': 475, 'max_depth': 2, 'learning_rate': 0.021322959710738644, 'min_child_weight': 2, 'subsample': 0.7912139968434072, 'colsample_bytree': 0.9070351922786026, 'gamma': 1.9991844553958993, 'reg_alpha': 0.003489018845491387, 'reg_lambda': 0.37500594752084926, 'scale_pos_weight': 1.3325152889039984}. Best is trial 1 with value: 0.6608323155450291.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:22:12,350] Trial 3 finished with value: 0.652851071673144 and parameters: {'n_estimators': 475, 'max_depth': 2, 'learning_rate': 0.016222035757973607, 'min_child_weight': 3, 'subsample': 0.8931264066149118, 'colsample_bytree': 0.9116794696232922, 'gamma': 2.2615344229334267, 'reg_alpha': 0.00019634341572933326, 'reg_lambda': 0.5124661108462079, 'scale_pos_weight': 1.608106745617721}. Best is trial 1 with value: 0.6608323155450291.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:22:17,523] Trial 4 finished with value: 0.654035785178653 and parameters: {'n_estimators': 375, 'max_depth': 3, 'learning_rate': 0.015634078412645306, 'min_child_weight': 3, 'subsample': 0.7517559963200033, 'colsample_bytree': 0.8825044568707964, 'gamma': 2.2792776902235277, 'reg_alpha': 0.0036324869566766076, 'reg_lambda': 0.32101651681489296, 'scale_pos_weight': 1.429398118867869}. Best is trial 1 with value: 0.6608323155450291.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:22:26,906] Trial 5 finished with value: 0.644076553314367 and parameters: {'n_estimators': 550, 'max_depth': 5, 'learning_rate': 0.046487403175345776, 'min_child_weight': 3, 'subsample': 0.819579995762217, 'colsample_bytree': 0.9343748470046234, 'gamma': 1.7212312551297988, 'reg_alpha': 0.0003872118032174585, 'reg_lambda': 0.0583144513696569, 'scale_pos_weight': 1.527731231534285}. Best is trial 1 with value: 0.6608323155450291.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:22:32,448] Trial 6 finished with value: 0.6539026314757194 and parameters: {'n_estimators': 425, 'max_depth': 3, 'learning_rate': 0.04068370419920864, 'min_child_weight': 2, 'subsample': 0.7561869019374762, 'colsample_bytree': 0.8585392166316497, 'gamma': 1.8523105624369065, 'reg_alpha': 0.025502980701628937, 'reg_lambda': 0.06443032835947, 'scale_pos_weight': 1.9908208556203622}. Best is trial 1 with value: 0.6608323155450291.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:22:37,960] Trial 7 finished with value: 0.6441231044801367 and parameters: {'n_estimators': 500, 'max_depth': 2, 'learning_rate': 0.015100059435535782, 'min_child_weight': 3, 'subsample': 0.8413714687695234, 'colsample_bytree': 0.8958014336081974, 'gamma': 3.4281758667148643, 'reg_alpha': 0.0001667761543019791, 'reg_lambda': 0.16922610206005692, 'scale_pos_weight': 1.3811083416675909}. Best is trial 1 with value: 0.6608323155450291.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:22:46,069] Trial 8 finished with value: 0.6630168928548159 and parameters: {'n_estimators': 525, 'max_depth': 4, 'learning_rate': 0.022341421548114658, 'min_child_weight': 1, 'subsample': 0.7621964643431324, 'colsample_bytree': 0.8150366644053494, 'gamma': 3.32401544584516, 'reg_alpha': 0.008178476574339543, 'reg_lambda': 1.0220939176246893, 'scale_pos_weight': 1.6305504476133645}. Best is trial 8 with value: 0.6630168928548159.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:22:51,704] Trial 9 finished with value: 0.6615748971905273 and parameters: {'n_estimators': 375, 'max_depth': 4, 'learning_rate': 0.03748776861762909, 'min_child_weight': 2, 'subsample': 0.8541934359909122, 'colsample_bytree': 0.8487591192728782, 'gamma': 2.806832073454985, 'reg_alpha': 0.0019170041589170674, 'reg_lambda': 0.05451514062685493, 'scale_pos_weight': 1.3755239988953132}. Best is trial 8 with value: 0.6630168928548159.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:22:59,241] Trial 10 finished with value: 0.659342442985765 and parameters: {'n_estimators': 500, 'max_depth': 4, 'learning_rate': 0.017245080648292846, 'min_child_weight': 1, 'subsample': 0.8041925071271754, 'colsample_bytree': 0.7567977225194816, 'gamma': 1.9590297318633045, 'reg_alpha': 0.029110795019504577, 'reg_lambda': 0.38678689878018696, 'scale_pos_weight': 1.4510418188690168}. Best is trial 8 with value: 0.6630168928548159.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:23:06,460] Trial 11 finished with value: 0.6574784299919715 and parameters: {'n_estimators': 500, 'max_depth': 4, 'learning_rate': 0.03556013345980787, 'min_child_weight': 2, 'subsample': 0.8701265054403874, 'colsample_bytree': 0.852681781781128, 'gamma': 3.1746978638329972, 'reg_alpha': 0.027743678172107208, 'reg_lambda': 1.2415767609247381, 'scale_pos_weight': 1.3743589160398264}. Best is trial 8 with value: 0.6630168928548159.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:23:11,883] Trial 12 finished with value: 0.6703311369209178 and parameters: {'n_estimators': 425, 'max_depth': 3, 'learning_rate': 0.03458651003666842, 'min_child_weight': 1, 'subsample': 0.7971986211947284, 'colsample_bytree': 0.8224822788942824, 'gamma': 3.7892393337168344, 'reg_alpha': 0.0037662570124544674, 'reg_lambda': 0.27579564728377115, 'scale_pos_weight': 1.4993140566482739}. Best is trial 12 with value: 0.6703311369209178.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:23:17,303] Trial 13 finished with value: 0.6659361587724522 and parameters: {'n_estimators': 525, 'max_depth': 2, 'learning_rate': 0.033112067054637276, 'min_child_weight': 1, 'subsample': 0.7434044214385354, 'colsample_bytree': 0.8150702423754055, 'gamma': 3.6621173625430403, 'reg_alpha': 0.005650350873662589, 'reg_lambda': 0.27170046149611965, 'scale_pos_weight': 1.5228181504845644}. Best is trial 12 with value: 0.6703311369209178.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:23:23,110] Trial 14 finished with value: 0.6609449570941969 and parameters: {'n_estimators': 450, 'max_depth': 3, 'learning_rate': 0.03202003845152873, 'min_child_weight': 1, 'subsample': 0.7825864410563783, 'colsample_bytree': 0.8757974143801499, 'gamma': 3.717158835895488, 'reg_alpha': 0.0019416100236548865, 'reg_lambda': 0.26195439321509806, 'scale_pos_weight': 1.3726471596156409}. Best is trial 12 with value: 0.6703311369209178.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:23:28,414] Trial 15 finished with value: 0.6631598651901054 and parameters: {'n_estimators': 400, 'max_depth': 3, 'learning_rate': 0.02801638041843335, 'min_child_weight': 1, 'subsample': 0.7613598356231058, 'colsample_bytree': 0.856019069097751, 'gamma': 3.9686298159017053, 'reg_alpha': 0.005765605697677418, 'reg_lambda': 0.437016409692555, 'scale_pos_weight': 1.5711315115138338}. Best is trial 12 with value: 0.6703311369209178.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:23:32,919] Trial 16 finished with value: 0.6639241888428099 and parameters: {'n_estimators': 425, 'max_depth': 2, 'learning_rate': 0.04331226859463392, 'min_child_weight': 1, 'subsample': 0.7813249829212092, 'colsample_bytree': 0.7863648055280452, 'gamma': 3.7802891321973497, 'reg_alpha': 0.0021840553509423974, 'reg_lambda': 0.28247072065348766, 'scale_pos_weight': 1.447945358461111}. Best is trial 12 with value: 0.6703311369209178.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:23:39,367] Trial 17 finished with value: 0.6609128995957849 and parameters: {'n_estimators': 525, 'max_depth': 3, 'learning_rate': 0.04007625021057906, 'min_child_weight': 1, 'subsample': 0.7811348093711238, 'colsample_bytree': 0.791483870358809, 'gamma': 3.850761118148553, 'reg_alpha': 0.006790810292964185, 'reg_lambda': 0.38748452735676264, 'scale_pos_weight': 1.665573136736147}. Best is trial 12 with value: 0.6703311369209178.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:23:44,796] Trial 18 finished with value: 0.6620815406754208 and parameters: {'n_estimators': 500, 'max_depth': 2, 'learning_rate': 0.03347421937404715, 'min_child_weight': 1, 'subsample': 0.7491560843933305, 'colsample_bytree': 0.8639775516901275, 'gamma': 3.1994735029949313, 'reg_alpha': 0.0012764779682959756, 'reg_lambda': 0.41776382338713697, 'scale_pos_weight': 1.492795265427742}. Best is trial 12 with value: 0.6703311369209178.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:23:51,228] Trial 19 finished with value: 0.6586235391383977 and parameters: {'n_estimators': 525, 'max_depth': 3, 'learning_rate': 0.03489683402941082, 'min_child_weight': 1, 'subsample': 0.7006392013593232, 'colsample_bytree': 0.8078170228667628, 'gamma': 3.4888890418494536, 'reg_alpha': 0.01895730562016014, 'reg_lambda': 0.32431814725602165, 'scale_pos_weight': 1.6324240414281352}. Best is trial 12 with value: 0.6703311369209178.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:23:56,820] Trial 20 finished with value: 0.6652180464139864 and parameters: {'n_estimators': 450, 'max_depth': 3, 'learning_rate': 0.028797340108387234, 'min_child_weight': 1, 'subsample': 0.8177150506687362, 'colsample_bytree': 0.7654680158517755, 'gamma': 3.9750277182994327, 'reg_alpha': 0.0010866109891510202, 'reg_lambda': 0.20480763654240328, 'scale_pos_weight': 1.4705420196403414}. Best is trial 12 with value: 0.6703311369209178.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:24:03,123] Trial 21 finished with value: 0.669073836849935 and parameters: {'n_estimators': 500, 'max_depth': 3, 'learning_rate': 0.026361793249827684, 'min_child_weight': 1, 'subsample': 0.8015288495710597, 'colsample_bytree': 0.7975904618917345, 'gamma': 3.719379922296184, 'reg_alpha': 0.0040034735989898165, 'reg_lambda': 0.3443324923040132, 'scale_pos_weight': 1.4260833642013366}. Best is trial 12 with value: 0.6703311369209178.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:24:08,545] Trial 22 finished with value: 0.6586754954335816 and parameters: {'n_estimators': 425, 'max_depth': 3, 'learning_rate': 0.02705939219677354, 'min_child_weight': 1, 'subsample': 0.7925946213336634, 'colsample_bytree': 0.7905332404317745, 'gamma': 3.73471642454543, 'reg_alpha': 0.00553629188173977, 'reg_lambda': 0.4755696615476101, 'scale_pos_weight': 1.3842462166073461}. Best is trial 12 with value: 0.6703311369209178.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:24:15,085] Trial 23 finished with value: 0.6655536335688674 and parameters: {'n_estimators': 525, 'max_depth': 3, 'learning_rate': 0.03202856458258713, 'min_child_weight': 1, 'subsample': 0.7341125758543021, 'colsample_bytree': 0.8322954895883015, 'gamma': 3.9119640642982496, 'reg_alpha': 0.0024707871952352697, 'reg_lambda': 0.5776862709965347, 'scale_pos_weight': 1.4985889556124108}. Best is trial 12 with value: 0.6703311369209178.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:24:20,715] Trial 24 finished with value: 0.6580923919140359 and parameters: {'n_estimators': 550, 'max_depth': 2, 'learning_rate': 0.03200938933831765, 'min_child_weight': 1, 'subsample': 0.8106802799807709, 'colsample_bytree': 0.8251608105382369, 'gamma': 3.269368871688732, 'reg_alpha': 0.0019232172392539292, 'reg_lambda': 0.19430530397096538, 'scale_pos_weight': 1.4178828641898509}. Best is trial 12 with value: 0.6703311369209178.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:24:25,746] Trial 25 finished with value: 0.6614770497113563 and parameters: {'n_estimators': 475, 'max_depth': 2, 'learning_rate': 0.029510672221535066, 'min_child_weight': 1, 'subsample': 0.7735901737154818, 'colsample_bytree': 0.8205150861726157, 'gamma': 3.6678361228560856, 'reg_alpha': 0.0009183116976082922, 'reg_lambda': 0.16941870978113277, 'scale_pos_weight': 1.6248638509761364}. Best is trial 12 with value: 0.6703311369209178.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:24:31,585] Trial 26 finished with value: 0.6622618194354334 and parameters: {'n_estimators': 475, 'max_depth': 3, 'learning_rate': 0.027971614620500386, 'min_child_weight': 1, 'subsample': 0.7621311351849596, 'colsample_bytree': 0.7597136775960733, 'gamma': 3.611510628133182, 'reg_alpha': 0.015327532596273603, 'reg_lambda': 0.1829424759985717, 'scale_pos_weight': 1.429518621376213}. Best is trial 12 with value: 0.6703311369209178.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:24:37,056] Trial 27 finished with value: 0.6636077923440471 and parameters: {'n_estimators': 525, 'max_depth': 2, 'learning_rate': 0.03829553059874481, 'min_child_weight': 1, 'subsample': 0.705050408015962, 'colsample_bytree': 0.8436530009881918, 'gamma': 3.9242358414757352, 'reg_alpha': 0.0034090986367986322, 'reg_lambda': 0.24586298898502973, 'scale_pos_weight': 1.5110833252865135}. Best is trial 12 with value: 0.6703311369209178.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:24:42,649] Trial 28 finished with value: 0.6654483769047388 and parameters: {'n_estimators': 550, 'max_depth': 2, 'learning_rate': 0.03558637864420926, 'min_child_weight': 1, 'subsample': 0.746127537736121, 'colsample_bytree': 0.8097883794777065, 'gamma': 3.214492298039532, 'reg_alpha': 0.013196943640317333, 'reg_lambda': 0.23002017394230725, 'scale_pos_weight': 1.3904856564815102}. Best is trial 12 with value: 0.6703311369209178.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:24:48,433] Trial 29 finished with value: 0.6673102287148455 and parameters: {'n_estimators': 450, 'max_depth': 3, 'learning_rate': 0.03139625501565025, 'min_child_weight': 1, 'subsample': 0.7941117852630485, 'colsample_bytree': 0.8298664515709696, 'gamma': 3.859032534104389, 'reg_alpha': 0.006149353079632054, 'reg_lambda': 0.31755042213651097, 'scale_pos_weight': 1.4758411562628824}. Best is trial 12 with value: 0.6703311369209178.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:24:53,672] Trial 30 finished with value: 0.6714625395893774 and parameters: {'n_estimators': 400, 'max_depth': 3, 'learning_rate': 0.040163152902984646, 'min_child_weight': 1, 'subsample': 0.81249264006384, 'colsample_bytree': 0.8318800076799352, 'gamma': 3.7385388146681655, 'reg_alpha': 0.0022890802590751352, 'reg_lambda': 0.1845069333257935, 'scale_pos_weight': 1.6100770173733678}. Best is trial 30 with value: 0.6714625395893774.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:24:59,107] Trial 31 finished with value: 0.6691972163458498 and parameters: {'n_estimators': 425, 'max_depth': 3, 'learning_rate': 0.043824139238215376, 'min_child_weight': 1, 'subsample': 0.7706190942618975, 'colsample_bytree': 0.8354627196096417, 'gamma': 3.761362629113185, 'reg_alpha': 0.0020841009806155976, 'reg_lambda': 0.30446768075165914, 'scale_pos_weight': 1.5776085791944126}. Best is trial 30 with value: 0.6714625395893774.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:25:04,519] Trial 32 finished with value: 0.6655760983270355 and parameters: {'n_estimators': 425, 'max_depth': 3, 'learning_rate': 0.04088468350846252, 'min_child_weight': 1, 'subsample': 0.7948870779025919, 'colsample_bytree': 0.8162632731396312, 'gamma': 3.7871377093271072, 'reg_alpha': 0.001105147648096976, 'reg_lambda': 0.3311041105544645, 'scale_pos_weight': 1.596733736851308}. Best is trial 30 with value: 0.6714625395893774.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:25:09,429] Trial 33 finished with value: 0.6694680163271883 and parameters: {'n_estimators': 375, 'max_depth': 3, 'learning_rate': 0.04016456043324279, 'min_child_weight': 1, 'subsample': 0.8248919423620533, 'colsample_bytree': 0.8166562884194573, 'gamma': 3.605294703645549, 'reg_alpha': 0.000761103106406897, 'reg_lambda': 0.1498676035266222, 'scale_pos_weight': 1.7405319873737088}. Best is trial 30 with value: 0.6714625395893774.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:25:14,614] Trial 34 finished with value: 0.6694163652555438 and parameters: {'n_estimators': 400, 'max_depth': 3, 'learning_rate': 0.04356174837110551, 'min_child_weight': 1, 'subsample': 0.8098879900652608, 'colsample_bytree': 0.8461983651417964, 'gamma': 3.9913121868502595, 'reg_alpha': 0.0023549087764337647, 'reg_lambda': 0.17570275712859962, 'scale_pos_weight': 1.4958779337043313}. Best is trial 30 with value: 0.6714625395893774.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:25:19,523] Trial 35 finished with value: 0.6698833008456426 and parameters: {'n_estimators': 375, 'max_depth': 3, 'learning_rate': 0.03840799272912195, 'min_child_weight': 1, 'subsample': 0.7948749045252261, 'colsample_bytree': 0.8420485994102506, 'gamma': 3.863409863884976, 'reg_alpha': 0.0013648706047594303, 'reg_lambda': 0.15988692344286567, 'scale_pos_weight': 1.3652586601228873}. Best is trial 30 with value: 0.6714625395893774.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:25:24,703] Trial 36 finished with value: 0.6706612553333117 and parameters: {'n_estimators': 400, 'max_depth': 3, 'learning_rate': 0.03659180987857414, 'min_child_weight': 1, 'subsample': 0.8389456924695684, 'colsample_bytree': 0.8210615597127745, 'gamma': 3.799153182578808, 'reg_alpha': 0.0005488377204583805, 'reg_lambda': 0.19319433544525033, 'scale_pos_weight': 1.527611796119143}. Best is trial 30 with value: 0.6714625395893774.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:25:29,616] Trial 37 finished with value: 0.6660670437866363 and parameters: {'n_estimators': 375, 'max_depth': 3, 'learning_rate': 0.0353013405015413, 'min_child_weight': 1, 'subsample': 0.8447475755137226, 'colsample_bytree': 0.83259290044479, 'gamma': 3.700021941069651, 'reg_alpha': 0.001762962075530211, 'reg_lambda': 0.12516567527459865, 'scale_pos_weight': 1.425047220198056}. Best is trial 30 with value: 0.6714625395893774.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:25:35,269] Trial 38 finished with value: 0.6742840102611682 and parameters: {'n_estimators': 450, 'max_depth': 3, 'learning_rate': 0.03169263099895088, 'min_child_weight': 1, 'subsample': 0.7816524076750944, 'colsample_bytree': 0.7950660358381656, 'gamma': 3.706704516605376, 'reg_alpha': 0.004749825692106681, 'reg_lambda': 0.35253189292857723, 'scale_pos_weight': 1.515053442659512}. Best is trial 38 with value: 0.6742840102611682.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:25:40,500] Trial 39 finished with value: 0.6648605269995994 and parameters: {'n_estimators': 400, 'max_depth': 3, 'learning_rate': 0.032614983668918976, 'min_child_weight': 1, 'subsample': 0.8304219312471823, 'colsample_bytree': 0.8369690955249622, 'gamma': 3.9884418848726204, 'reg_alpha': 0.0030305148521030906, 'reg_lambda': 0.23330385749870705, 'scale_pos_weight': 1.5009277644844163}. Best is trial 38 with value: 0.6742840102611682.

Mejor F1-Macro CV refinado: 0.6743

Mejores hiperparámetros:
  n_estimators: 450
  max_depth: 3
  learning_rate: 0.03169263099895088
  min_child_weight: 1
  subsample: 0.7816524076750944

======================================================================
CONFIGURACIÓN DEFINITIVA POR VARIANTE
======================================================================

In [5]:
# ============================================================
# RECUPERAR OPTUNA REFINADO SOLO PARA CU
# ============================================================

import optuna

variante = 'cu'

sampler = optuna.samplers.TPESampler(
    seed=RANDOM_STATE
)

study_cu = optuna.create_study(
    direction='maximize',
    sampler=sampler,
    study_name='xgboost_refinado_cu_recuperado'
)

study_cu.optimize(
    lambda trial: objective_xgboost_refinado(
        trial,
        variante
    ),
    n_trials=40,
    show_progress_bar=True
)

print('\nMejor F1-Macro CU:')
print(study_cu.best_value)

print('\nParámetros exactos CU:')

for parametro, valor in study_cu.best_params.items():
    print(f'{parametro}: {repr(valor)}')

[I 2026-09-21 17:25:40,547] A new study created in memory with name: xgboost_refinado_cu_recuperado

  0%|          | 0/40 [00:00<?, ?it/s]

Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:25:47,703] Trial 0 finished with value: 0.660488321764827 and parameters: {'n_estimators': 425, 'max_depth': 5, 'learning_rate': 0.03621056763954017, 'min_child_weight': 2, 'subsample': 0.7312037280884873, 'colsample_bytree': 0.7811989040672406, 'gamma': 1.6452090304204987, 'reg_alpha': 0.0396760507705299, 'reg_lambda': 0.3862689194653677, 'scale_pos_weight': 1.795650804457232}. Best is trial 0 with value: 0.660488321764827.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:25:53,907] Trial 1 finished with value: 0.6608323155450291 and parameters: {'n_estimators': 350, 'max_depth': 5, 'learning_rate': 0.040865594623548177, 'min_child_weight': 1, 'subsample': 0.73636499344142, 'colsample_bytree': 0.7866809019706867, 'gamma': 2.260605607398844, 'reg_alpha': 0.0037520558551242854, 'reg_lambda': 0.21727270548647376, 'scale_pos_weight': 1.5038603981386294}. Best is trial 1 with value: 0.6608323155450291.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:25:59,072] Trial 2 finished with value: 0.6509196801550343 and parameters: {'n_estimators': 475, 'max_depth': 2, 'learning_rate': 0.021322959710738644, 'min_child_weight': 2, 'subsample': 0.7912139968434072, 'colsample_bytree': 0.9070351922786026, 'gamma': 1.9991844553958993, 'reg_alpha': 0.003489018845491387, 'reg_lambda': 0.37500594752084926, 'scale_pos_weight': 1.3325152889039984}. Best is trial 1 with value: 0.6608323155450291.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:26:04,201] Trial 3 finished with value: 0.652851071673144 and parameters: {'n_estimators': 475, 'max_depth': 2, 'learning_rate': 0.016222035757973607, 'min_child_weight': 3, 'subsample': 0.8931264066149118, 'colsample_bytree': 0.9116794696232922, 'gamma': 2.2615344229334267, 'reg_alpha': 0.00019634341572933326, 'reg_lambda': 0.5124661108462079, 'scale_pos_weight': 1.608106745617721}. Best is trial 1 with value: 0.6608323155450291.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:26:09,223] Trial 4 finished with value: 0.654035785178653 and parameters: {'n_estimators': 375, 'max_depth': 3, 'learning_rate': 0.015634078412645306, 'min_child_weight': 3, 'subsample': 0.7517559963200033, 'colsample_bytree': 0.8825044568707964, 'gamma': 2.2792776902235277, 'reg_alpha': 0.0036324869566766076, 'reg_lambda': 0.32101651681489296, 'scale_pos_weight': 1.429398118867869}. Best is trial 1 with value: 0.6608323155450291.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:26:18,280] Trial 5 finished with value: 0.644076553314367 and parameters: {'n_estimators': 550, 'max_depth': 5, 'learning_rate': 0.046487403175345776, 'min_child_weight': 3, 'subsample': 0.819579995762217, 'colsample_bytree': 0.9343748470046234, 'gamma': 1.7212312551297988, 'reg_alpha': 0.0003872118032174585, 'reg_lambda': 0.0583144513696569, 'scale_pos_weight': 1.527731231534285}. Best is trial 1 with value: 0.6608323155450291.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:26:23,640] Trial 6 finished with value: 0.6539026314757194 and parameters: {'n_estimators': 425, 'max_depth': 3, 'learning_rate': 0.04068370419920864, 'min_child_weight': 2, 'subsample': 0.7561869019374762, 'colsample_bytree': 0.8585392166316497, 'gamma': 1.8523105624369065, 'reg_alpha': 0.025502980701628937, 'reg_lambda': 0.06443032835947, 'scale_pos_weight': 1.9908208556203622}. Best is trial 1 with value: 0.6608323155450291.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:26:29,015] Trial 7 finished with value: 0.6441231044801367 and parameters: {'n_estimators': 500, 'max_depth': 2, 'learning_rate': 0.015100059435535782, 'min_child_weight': 3, 'subsample': 0.8413714687695234, 'colsample_bytree': 0.8958014336081974, 'gamma': 3.4281758667148643, 'reg_alpha': 0.0001667761543019791, 'reg_lambda': 0.16922610206005692, 'scale_pos_weight': 1.3811083416675909}. Best is trial 1 with value: 0.6608323155450291.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:26:36,864] Trial 8 finished with value: 0.6630168928548159 and parameters: {'n_estimators': 525, 'max_depth': 4, 'learning_rate': 0.022341421548114658, 'min_child_weight': 1, 'subsample': 0.7621964643431324, 'colsample_bytree': 0.8150366644053494, 'gamma': 3.32401544584516, 'reg_alpha': 0.008178476574339543, 'reg_lambda': 1.0220939176246893, 'scale_pos_weight': 1.6305504476133645}. Best is trial 8 with value: 0.6630168928548159.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:26:42,397] Trial 9 finished with value: 0.6615748971905273 and parameters: {'n_estimators': 375, 'max_depth': 4, 'learning_rate': 0.03748776861762909, 'min_child_weight': 2, 'subsample': 0.8541934359909122, 'colsample_bytree': 0.8487591192728782, 'gamma': 2.806832073454985, 'reg_alpha': 0.0019170041589170674, 'reg_lambda': 0.05451514062685493, 'scale_pos_weight': 1.3755239988953132}. Best is trial 8 with value: 0.6630168928548159.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:26:49,807] Trial 10 finished with value: 0.659342442985765 and parameters: {'n_estimators': 500, 'max_depth': 4, 'learning_rate': 0.017245080648292846, 'min_child_weight': 1, 'subsample': 0.8041925071271754, 'colsample_bytree': 0.7567977225194816, 'gamma': 1.9590297318633045, 'reg_alpha': 0.029110795019504577, 'reg_lambda': 0.38678689878018696, 'scale_pos_weight': 1.4510418188690168}. Best is trial 8 with value: 0.6630168928548159.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:26:56,948] Trial 11 finished with value: 0.6574784299919715 and parameters: {'n_estimators': 500, 'max_depth': 4, 'learning_rate': 0.03556013345980787, 'min_child_weight': 2, 'subsample': 0.8701265054403874, 'colsample_bytree': 0.852681781781128, 'gamma': 3.1746978638329972, 'reg_alpha': 0.027743678172107208, 'reg_lambda': 1.2415767609247381, 'scale_pos_weight': 1.3743589160398264}. Best is trial 8 with value: 0.6630168928548159.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:27:02,425] Trial 12 finished with value: 0.6703311369209178 and parameters: {'n_estimators': 425, 'max_depth': 3, 'learning_rate': 0.03458651003666842, 'min_child_weight': 1, 'subsample': 0.7971986211947284, 'colsample_bytree': 0.8224822788942824, 'gamma': 3.7892393337168344, 'reg_alpha': 0.0037662570124544674, 'reg_lambda': 0.27579564728377115, 'scale_pos_weight': 1.4993140566482739}. Best is trial 12 with value: 0.6703311369209178.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:27:07,912] Trial 13 finished with value: 0.6659361587724522 and parameters: {'n_estimators': 525, 'max_depth': 2, 'learning_rate': 0.033112067054637276, 'min_child_weight': 1, 'subsample': 0.7434044214385354, 'colsample_bytree': 0.8150702423754055, 'gamma': 3.6621173625430403, 'reg_alpha': 0.005650350873662589, 'reg_lambda': 0.27170046149611965, 'scale_pos_weight': 1.5228181504845644}. Best is trial 12 with value: 0.6703311369209178.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:27:13,747] Trial 14 finished with value: 0.6609449570941969 and parameters: {'n_estimators': 450, 'max_depth': 3, 'learning_rate': 0.03202003845152873, 'min_child_weight': 1, 'subsample': 0.7825864410563783, 'colsample_bytree': 0.8757974143801499, 'gamma': 3.717158835895488, 'reg_alpha': 0.0019416100236548865, 'reg_lambda': 0.26195439321509806, 'scale_pos_weight': 1.3726471596156409}. Best is trial 12 with value: 0.6703311369209178.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:27:19,097] Trial 15 finished with value: 0.6631598651901054 and parameters: {'n_estimators': 400, 'max_depth': 3, 'learning_rate': 0.02801638041843335, 'min_child_weight': 1, 'subsample': 0.7613598356231058, 'colsample_bytree': 0.856019069097751, 'gamma': 3.9686298159017053, 'reg_alpha': 0.005765605697677418, 'reg_lambda': 0.437016409692555, 'scale_pos_weight': 1.5711315115138338}. Best is trial 12 with value: 0.6703311369209178.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:27:23,618] Trial 16 finished with value: 0.6639241888428099 and parameters: {'n_estimators': 425, 'max_depth': 2, 'learning_rate': 0.04331226859463392, 'min_child_weight': 1, 'subsample': 0.7813249829212092, 'colsample_bytree': 0.7863648055280452, 'gamma': 3.7802891321973497, 'reg_alpha': 0.0021840553509423974, 'reg_lambda': 0.28247072065348766, 'scale_pos_weight': 1.447945358461111}. Best is trial 12 with value: 0.6703311369209178.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:27:29,993] Trial 17 finished with value: 0.6609128995957849 and parameters: {'n_estimators': 525, 'max_depth': 3, 'learning_rate': 0.04007625021057906, 'min_child_weight': 1, 'subsample': 0.7811348093711238, 'colsample_bytree': 0.791483870358809, 'gamma': 3.850761118148553, 'reg_alpha': 0.006790810292964185, 'reg_lambda': 0.38748452735676264, 'scale_pos_weight': 1.665573136736147}. Best is trial 12 with value: 0.6703311369209178.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:27:35,318] Trial 18 finished with value: 0.6620815406754208 and parameters: {'n_estimators': 500, 'max_depth': 2, 'learning_rate': 0.03347421937404715, 'min_child_weight': 1, 'subsample': 0.7491560843933305, 'colsample_bytree': 0.8639775516901275, 'gamma': 3.1994735029949313, 'reg_alpha': 0.0012764779682959756, 'reg_lambda': 0.41776382338713697, 'scale_pos_weight': 1.492795265427742}. Best is trial 12 with value: 0.6703311369209178.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:27:41,756] Trial 19 finished with value: 0.6586235391383977 and parameters: {'n_estimators': 525, 'max_depth': 3, 'learning_rate': 0.03489683402941082, 'min_child_weight': 1, 'subsample': 0.7006392013593232, 'colsample_bytree': 0.8078170228667628, 'gamma': 3.4888890418494536, 'reg_alpha': 0.01895730562016014, 'reg_lambda': 0.32431814725602165, 'scale_pos_weight': 1.6324240414281352}. Best is trial 12 with value: 0.6703311369209178.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:27:47,309] Trial 20 finished with value: 0.6652180464139864 and parameters: {'n_estimators': 450, 'max_depth': 3, 'learning_rate': 0.028797340108387234, 'min_child_weight': 1, 'subsample': 0.8177150506687362, 'colsample_bytree': 0.7654680158517755, 'gamma': 3.9750277182994327, 'reg_alpha': 0.0010866109891510202, 'reg_lambda': 0.20480763654240328, 'scale_pos_weight': 1.4705420196403414}. Best is trial 12 with value: 0.6703311369209178.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:27:53,515] Trial 21 finished with value: 0.669073836849935 and parameters: {'n_estimators': 500, 'max_depth': 3, 'learning_rate': 0.026361793249827684, 'min_child_weight': 1, 'subsample': 0.8015288495710597, 'colsample_bytree': 0.7975904618917345, 'gamma': 3.719379922296184, 'reg_alpha': 0.0040034735989898165, 'reg_lambda': 0.3443324923040132, 'scale_pos_weight': 1.4260833642013366}. Best is trial 12 with value: 0.6703311369209178.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:27:58,956] Trial 22 finished with value: 0.6586754954335816 and parameters: {'n_estimators': 425, 'max_depth': 3, 'learning_rate': 0.02705939219677354, 'min_child_weight': 1, 'subsample': 0.7925946213336634, 'colsample_bytree': 0.7905332404317745, 'gamma': 3.73471642454543, 'reg_alpha': 0.00553629188173977, 'reg_lambda': 0.4755696615476101, 'scale_pos_weight': 1.3842462166073461}. Best is trial 12 with value: 0.6703311369209178.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:28:05,495] Trial 23 finished with value: 0.6655536335688674 and parameters: {'n_estimators': 525, 'max_depth': 3, 'learning_rate': 0.03202856458258713, 'min_child_weight': 1, 'subsample': 0.7341125758543021, 'colsample_bytree': 0.8322954895883015, 'gamma': 3.9119640642982496, 'reg_alpha': 0.0024707871952352697, 'reg_lambda': 0.5776862709965347, 'scale_pos_weight': 1.4985889556124108}. Best is trial 12 with value: 0.6703311369209178.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:28:11,132] Trial 24 finished with value: 0.6580923919140359 and parameters: {'n_estimators': 550, 'max_depth': 2, 'learning_rate': 0.03200938933831765, 'min_child_weight': 1, 'subsample': 0.8106802799807709, 'colsample_bytree': 0.8251608105382369, 'gamma': 3.269368871688732, 'reg_alpha': 0.0019232172392539292, 'reg_lambda': 0.19430530397096538, 'scale_pos_weight': 1.4178828641898509}. Best is trial 12 with value: 0.6703311369209178.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:28:16,225] Trial 25 finished with value: 0.6614770497113563 and parameters: {'n_estimators': 475, 'max_depth': 2, 'learning_rate': 0.029510672221535066, 'min_child_weight': 1, 'subsample': 0.7735901737154818, 'colsample_bytree': 0.8205150861726157, 'gamma': 3.6678361228560856, 'reg_alpha': 0.0009183116976082922, 'reg_lambda': 0.16941870978113277, 'scale_pos_weight': 1.6248638509761364}. Best is trial 12 with value: 0.6703311369209178.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:28:22,023] Trial 26 finished with value: 0.6622618194354334 and parameters: {'n_estimators': 475, 'max_depth': 3, 'learning_rate': 0.027971614620500386, 'min_child_weight': 1, 'subsample': 0.7621311351849596, 'colsample_bytree': 0.7597136775960733, 'gamma': 3.611510628133182, 'reg_alpha': 0.015327532596273603, 'reg_lambda': 0.1829424759985717, 'scale_pos_weight': 1.429518621376213}. Best is trial 12 with value: 0.6703311369209178.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:28:27,501] Trial 27 finished with value: 0.6636077923440471 and parameters: {'n_estimators': 525, 'max_depth': 2, 'learning_rate': 0.03829553059874481, 'min_child_weight': 1, 'subsample': 0.705050408015962, 'colsample_bytree': 0.8436530009881918, 'gamma': 3.9242358414757352, 'reg_alpha': 0.0034090986367986322, 'reg_lambda': 0.24586298898502973, 'scale_pos_weight': 1.5110833252865135}. Best is trial 12 with value: 0.6703311369209178.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:28:33,114] Trial 28 finished with value: 0.6654483769047388 and parameters: {'n_estimators': 550, 'max_depth': 2, 'learning_rate': 0.03558637864420926, 'min_child_weight': 1, 'subsample': 0.746127537736121, 'colsample_bytree': 0.8097883794777065, 'gamma': 3.214492298039532, 'reg_alpha': 0.013196943640317333, 'reg_lambda': 0.23002017394230725, 'scale_pos_weight': 1.3904856564815102}. Best is trial 12 with value: 0.6703311369209178.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:28:38,819] Trial 29 finished with value: 0.6673102287148455 and parameters: {'n_estimators': 450, 'max_depth': 3, 'learning_rate': 0.03139625501565025, 'min_child_weight': 1, 'subsample': 0.7941117852630485, 'colsample_bytree': 0.8298664515709696, 'gamma': 3.859032534104389, 'reg_alpha': 0.006149353079632054, 'reg_lambda': 0.31755042213651097, 'scale_pos_weight': 1.4758411562628824}. Best is trial 12 with value: 0.6703311369209178.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:28:44,066] Trial 30 finished with value: 0.6714625395893774 and parameters: {'n_estimators': 400, 'max_depth': 3, 'learning_rate': 0.040163152902984646, 'min_child_weight': 1, 'subsample': 0.81249264006384, 'colsample_bytree': 0.8318800076799352, 'gamma': 3.7385388146681655, 'reg_alpha': 0.0022890802590751352, 'reg_lambda': 0.1845069333257935, 'scale_pos_weight': 1.6100770173733678}. Best is trial 30 with value: 0.6714625395893774.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:28:49,604] Trial 31 finished with value: 0.6691972163458498 and parameters: {'n_estimators': 425, 'max_depth': 3, 'learning_rate': 0.043824139238215376, 'min_child_weight': 1, 'subsample': 0.7706190942618975, 'colsample_bytree': 0.8354627196096417, 'gamma': 3.761362629113185, 'reg_alpha': 0.0020841009806155976, 'reg_lambda': 0.30446768075165914, 'scale_pos_weight': 1.5776085791944126}. Best is trial 30 with value: 0.6714625395893774.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:28:55,000] Trial 32 finished with value: 0.6655760983270355 and parameters: {'n_estimators': 425, 'max_depth': 3, 'learning_rate': 0.04088468350846252, 'min_child_weight': 1, 'subsample': 0.7948870779025919, 'colsample_bytree': 0.8162632731396312, 'gamma': 3.7871377093271072, 'reg_alpha': 0.001105147648096976, 'reg_lambda': 0.3311041105544645, 'scale_pos_weight': 1.596733736851308}. Best is trial 30 with value: 0.6714625395893774.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:28:59,924] Trial 33 finished with value: 0.6694680163271883 and parameters: {'n_estimators': 375, 'max_depth': 3, 'learning_rate': 0.04016456043324279, 'min_child_weight': 1, 'subsample': 0.8248919423620533, 'colsample_bytree': 0.8166562884194573, 'gamma': 3.605294703645549, 'reg_alpha': 0.000761103106406897, 'reg_lambda': 0.1498676035266222, 'scale_pos_weight': 1.7405319873737088}. Best is trial 30 with value: 0.6714625395893774.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:29:05,151] Trial 34 finished with value: 0.6694163652555438 and parameters: {'n_estimators': 400, 'max_depth': 3, 'learning_rate': 0.04356174837110551, 'min_child_weight': 1, 'subsample': 0.8098879900652608, 'colsample_bytree': 0.8461983651417964, 'gamma': 3.9913121868502595, 'reg_alpha': 0.0023549087764337647, 'reg_lambda': 0.17570275712859962, 'scale_pos_weight': 1.4958779337043313}. Best is trial 30 with value: 0.6714625395893774.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:29:10,151] Trial 35 finished with value: 0.6698833008456426 and parameters: {'n_estimators': 375, 'max_depth': 3, 'learning_rate': 0.03840799272912195, 'min_child_weight': 1, 'subsample': 0.7948749045252261, 'colsample_bytree': 0.8420485994102506, 'gamma': 3.863409863884976, 'reg_alpha': 0.0013648706047594303, 'reg_lambda': 0.15988692344286567, 'scale_pos_weight': 1.3652586601228873}. Best is trial 30 with value: 0.6714625395893774.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:29:15,295] Trial 36 finished with value: 0.6706612553333117 and parameters: {'n_estimators': 400, 'max_depth': 3, 'learning_rate': 0.03659180987857414, 'min_child_weight': 1, 'subsample': 0.8389456924695684, 'colsample_bytree': 0.8210615597127745, 'gamma': 3.799153182578808, 'reg_alpha': 0.0005488377204583805, 'reg_lambda': 0.19319433544525033, 'scale_pos_weight': 1.527611796119143}. Best is trial 30 with value: 0.6714625395893774.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:29:20,208] Trial 37 finished with value: 0.6660670437866363 and parameters: {'n_estimators': 375, 'max_depth': 3, 'learning_rate': 0.0353013405015413, 'min_child_weight': 1, 'subsample': 0.8447475755137226, 'colsample_bytree': 0.83259290044479, 'gamma': 3.700021941069651, 'reg_alpha': 0.001762962075530211, 'reg_lambda': 0.12516567527459865, 'scale_pos_weight': 1.425047220198056}. Best is trial 30 with value: 0.6714625395893774.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:29:25,886] Trial 38 finished with value: 0.6742840102611682 and parameters: {'n_estimators': 450, 'max_depth': 3, 'learning_rate': 0.03169263099895088, 'min_child_weight': 1, 'subsample': 0.7816524076750944, 'colsample_bytree': 0.7950660358381656, 'gamma': 3.706704516605376, 'reg_alpha': 0.004749825692106681, 'reg_lambda': 0.35253189292857723, 'scale_pos_weight': 1.515053442659512}. Best is trial 38 with value: 0.6742840102611682.
Cargando: ../data/train_clean_stem_cu.csv
[I 2026-09-21 17:29:31,081] Trial 39 finished with value: 0.6648605269995994 and parameters: {'n_estimators': 400, 'max_depth': 3, 'learning_rate': 0.032614983668918976, 'min_child_weight': 1, 'subsample': 0.8304219312471823, 'colsample_bytree': 0.8369690955249622, 'gamma': 3.9884418848726204, 'reg_alpha': 0.0030305148521030906, 'reg_lambda': 0.23330385749870705, 'scale_pos_weight': 1.5009277644844163}. Best is trial 38 with value: 0.6742840102611682.

Mejor F1-Macro CU:
0.6742840102611682

Parámetros exactos CU:
n_estimators: 450
max_depth: 3
learning_rate: 0.03169263099895088
min_child_weight: 1
subsample: 0.7816524076750944